### ISSUE TITLE
issue with loading FUSE-mounted bam/bai in 2.10.3

### ISSUE THREAD

**Issue by sclan** [igvteam/igv#1016]
The partition containing the bam and bai files is mounted via FUSE onto the local filesystem. The OS is CentOS 7 running on virtualbox.

The files loaded successfully but when the user zooms in to visualize the pileup, the following error showed up and no alignment is rendered.

The content of the files are accessible in terminal using samtools view command. 

We unfortunately can't use the pre-authenticated URL load or local file load mechanisms to load the files due to security and storage limitation. 

```
$ bash igv.sh 

echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
WARN [2021-08-12T15:22:15,710]  [Globals.java:135] [main]  Development mode is enabled
INFO [2021-08-12T15:22:15,734]  [DirectoryManager.java:180] [main]  IGV Directory: /home/slan/igv
INFO [2021-08-12T15:22:16,321]  [Main.java:207] [AWT-EventQueue-0]  Startup  IGV Version 2.10.3 08/01/2021 12:12 AM
INFO [2021-08-12T15:22:16,330]  [Main.java:208] [AWT-EventQueue-0]  Java 11.0.10 (build 11.0.10+9) 2021-01-19
INFO [2021-08-12T15:22:16,331]  [Main.java:211] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2021-08-12T15:22:16,331]  [Main.java:213] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2021-08-12T15:22:16,397]  [Main.java:216] [AWT-EventQueue-0]  Default User Directory: /home/slan
INFO [2021-08-12T15:22:16,398]  [Main.java:217] [AWT-EventQueue-0]  OS: Linux 3.10.0-1160.36.2.el7.x86_64 amd64
INFO [2021-08-12T15:22:16,860]  [CommandListener.java:122] [Thread-3]  Listening on port 60151
INFO [2021-08-12T15:22:17,238]  [GenomeManager.java:183] [pool-3-thread-1]  Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
INFO [2021-08-12T15:22:17,507]  [IGV.java:1326] [pool-3-thread-1]  Loading 1 resources.
INFO [2021-08-12T15:22:17,511]  [TrackLoader.java:120] [pool-3-thread-1]  Loading resource, path https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz
Gtk-Message: 15:23:02.522: GtkDialog mapped without a transient parent. This is discouraged.
INFO [2021-08-12T15:23:30,998]  [IGV.java:1326] [pool-3-thread-2]  Loading 1 resources.
INFO [2021-08-12T15:23:30,999]  [TrackLoader.java:120] [pool-3-thread-2]  Loading resource, path /mnt/project/foobar/_Data/SRR504516_markdup.bam
ERROR [2021-08-12T15:24:40,020]  [BAMReader.java:139] [pool-2-thread-4]  Error querying for sequence: chr21
htsjdk.samtools.util.RuntimeIOException: No such device
	at htsjdk.samtools.MemoryMappedFileBuffer.<init>(MemoryMappedFileBuffer.java:28) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:64) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:46) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:419) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:931) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:612) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:550) ~[htsjdk-2.24.1.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:555) ~[htsjdk-2.24.1.jar:?]
	at org.broad.igv.sam.reader.BAMReader$PicardIterator.<init>(BAMReader.java:170) ~[igv.jar:?]
	at org.broad.igv.sam.reader.BAMReader.query(BAMReader.java:137) [igv.jar:?]
	at org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:165) [igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:419) [igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.load(AlignmentDataManager.java:366) [igv.jar:?]
	at org.broad.igv.sam.CoverageTrack.load(CoverageTrack.java:176) [igv.jar:?]
	at org.broad.igv.ui.IGV.lambda$repaint$12(IGV.java:2455) [igv.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: No such device
	at sun.nio.ch.FileChannelImpl.map0(Native Method) ~[?:?]
	at sun.nio.ch.FileChannelImpl.map(Unknown Source) ~[?:?]
	at htsjdk.samtools.MemoryMappedFileBuffer.<init>(MemoryMappedFileBuffer.java:23) ~[htsjdk-2.24.1.jar:?]
	... 18 more

```

**Comment by sclan** [comment]
I believe it's because of the memory mapping requirement are not met and require java setting change according to
https://github.com/samtools/htsjdk/issues/1470

**Comment by jrobinso** [comment]
I think this is an issue for the htsjdk, as seen from the stack trace.
