### ISSUE TITLE
Unhandled exception java.lang.IllegalStateException: Not a JSON Object: null

### ISSUE THREAD

**Issue by xiaonalu** [igvteam/igv#1022]
Hi,
I got this error. It's a JAVA problem? I am using java version "16.0.2" 2021-07-20. Thanks 

ERROR [2021-08-31T21:26:03,221]  [CommandListener.java:140] [Thread-3]  java.net.BindException: Address already in use
ERROR [2021-08-31T21:26:03,324]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[gson-2.8.5.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.getCachedGenomeList(GenomeListManager.java:255) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.rebuildGenomeItemMap(GenomeListManager.java:88) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.getGenomeItemMap(GenomeListManager.java:75) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeComboBox.getModelForGenomeListComboBox(GenomeComboBox.java:68) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeComboBox.refreshGenomeListComboBox(GenomeComboBox.java:42) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.lambda$refreshGenomeListComboBox$1(IGVCommandBar.java:212) ~[igv.jar:?]
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.refreshGenomeListComboBox(IGVCommandBar.java:211) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.<init>(IGVCommandBar.java:103) ~[igv.jar:?]
	at org.broad.igv.ui.IGVContentPane.<init>(IGVContentPane.java:73) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.<init>(IGV.java:253) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.createInstance(IGV.java:147) ~[igv.jar:?]
	at org.broad.igv.ui.Main.open(Main.java:351) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:120) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
INFO [2021-08-31T21:26:06,364]  [ShutdownThread.java:47] [Thread-1]  Shutting down
ERROR [2021-08-31T21:26:06,365]  [DefaultExceptionHandler.java:49] [Thread-1]  Unhandled exception
java.lang.NullPointerException: Cannot invoke "org.broad.igv.ui.IGVContentPane.getMainPanel()" because "this.contentPane" is null
	at org.broad.igv.ui.IGV.getTrackPanels(IGV.java:1050) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.getAllTracks(IGV.java:1709) ~[igv.jar:?]
	at org.broad.igv.ui.ShutdownThread.runS(ShutdownThread.java:52) ~[igv.jar:?]
	at org.broad.igv.ui.ShutdownThread.run(ShutdownThread.java:60) ~[igv.jar:?]
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jrobinso** [comment]
What version of IGV you are using?

This is not likely a Java problem.  What is in your "igv/genomes" folder?   A corrupt file in that folder might cause this.

**Comment by xiaonalu** [comment]
The version is IGV 2.11.0.
I have igv/igv-3.log and sequenceMap.txt in the "igv/genomes" folder. Should I clean it up? Thanks

**Comment by jrobinso** [comment]
@xiaonalu Sorry for the delay.   There shouldn't be any log files in the genomes folder.   Otherwise I'm not sure, it could be an IGV bug.  You can try quitting IGV, then delete or rename the "igv" folder and restart.   This will give you a clean start.

**Comment by xiaonalu** [comment]
Thanks. It works as a brand new one now. Thanks

**Comment by jrobinso** [comment]
I would like to know what caused it, otherwise it might recur or happen to others..   If you still have the old igv folder could you zip and attach the "sequenceMap.txt" file, and anything else that was in the "igv/genomes" folder?

**Comment by xiaonalu** [comment]
Yes, I have them. Could I email them to you? It might be a few versions mixed (IGV 2.8.0 - 2.11.0). Thanks

**Comment by jrobinso** [comment]
@xiaonalu Yes, email them to igv-team@broadinstitute.org.   Thanks.  

If the error above came from version 2.8.0 after you had ran version 2.11.0 it would be easier to understand.   It shouldn't happen but I can see how it might.

**Comment by xiaonalu** [comment]
Just sent. Thank you

**Comment by jrobinso** [comment]
From code inspection it looks like the only way for this to occur is if a file with a ".json" directory is in the genome directory, but the actual file contents are not json.   I'm going to add some validation to make it fail gracefully in that case.
