### ISSUE TITLE
Incomplete genome loading in IGV 2.11.9 ?

### ISSUE THREAD

**Issue by kentawan** [igvteam/igv#1079]
Hi, I got this error when trying to start IGV 2.11.9 - without bundled Java 11.

```
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
WARNING [Dec 28,2021 16:51] [Globals] Development mode is enabled
INFO [Dec 28,2021 16:51] [Main] Startup  IGV Version 2.11.9 12/21/2021 12:15 AM
INFO [Dec 28,2021 16:51] [Main] Java 11.0.13 (build 11.0.13+10-LTS-370) 2021-10-19
INFO [Dec 28,2021 16:51] [Main] Java Vendor: Oracle Corporation https://openjdk.java.net/
INFO [Dec 28,2021 16:51] [Main] JVM: Java HotSpot(TM) 64-Bit Server VM 18.9
INFO [Dec 28,2021 16:51] [Main] OS: Windows 10 10.0 amd64
INFO [Dec 28,2021 16:51] [Main] IGV Directory: C:\Users\me\igv
INFO [Dec 28,2021 16:51] [CommandListener] Listening on port 60151
INFO [Dec 28,2021 16:51] [GenomeManager] Loading genome: C:\Users\me\igv\genomes\hg19.json
INFO [Dec 28,2021 16:51] [GenomeManager] Loading genome: C:\Users\me\igv\genomes\hg19.json
INFO [Dec 28,2021 16:52] [IGV] Loading 1 resources.
INFO [Dec 28,2021 16:52] [TrackLoader] Loading resource, path https://s3.amazonaws.com/igv.org.genomes/hg19/ncbiRefSeq.sorted.txt.gz
SEVERE [Dec 28,2021 16:52] [IGVPreferences] No default value for: CIRC_VIEW_ENABLED
INFO [Dec 28,2021 16:53] [TrackLoader] Loading resource, path C:\Users\me\Downloads\sample.bam
SEVERE [Dec 28,2021 16:53] [DataPanelContainer] java.awt.datatransfer.UnsupportedFlavorException: Unicode String
        at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.getTransferData(SunDropTargetContextPeer.java:256)
        at java.desktop/sun.awt.datatransfer.TransferableProxy.getTransferData(TransferableProxy.java:73)
        at java.desktop/java.awt.dnd.DropTargetContext$TransferableProxy.getTransferData(DropTargetContext.java:386)
        at org.igv/org.broad.igv.ui.panel.DataPanelContainer$FileDropTargetListener.drop(DataPanelContainer.java:245)
        at java.desktop/java.awt.dnd.DropTarget.drop(DropTarget.java:452)
        at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:547)
        at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:863)
        at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:787)
        at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4876)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4621)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4483)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

While the genome seems to load fine, when I zoom in into some regions, the RefSeq tracks are missing (e.g. into BRAF on hg19), and IGV became non-responsive. What is the issue here? I can supply more information if need.

**Comment by jrobinso** [comment]
I couldn't really say since I can't reproduce that behavior.   The error above occurs with drag & drop, but really doesn't affect anything.   Its not the cause of the other behavior you describe.    This could be caused by a network or proxy blocking your access to the servers hosting hg19.

**Comment by jrobinso** [comment]
As a test you can download the following zip and set the reference up locally.   Just unzip this anywhere of your choosing.  Its ~3GB unzipped.  Then load it from the Genomes menu by selecting the "hg19.json" file from  "Genomes > Load from file".   Then try  zooming as you did before.    

Unfortunately you will have to select "hg19.json" each time you start IGV, but this will give us some information.

**Comment by kentawan** [comment]
Thanks jrobinso! I'm sorry I missed your zip file. Where can I download that?

**Comment by jrobinso** [comment]
@kentawan Sorry forgot the link.  You can download it here: [https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_local.zip](https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_local.zip).

If this works you can avoid having to select it everytime by copying the contents to ~/igv/genomes.   It has to be copied as-is, including the "hg19" subdirectory.   However I suggest first loading it manually from "Genomes > Load from file" to see if it helps.

**Comment by kentawan** [comment]
@jrobinso. Thanks! The downloaded hg19.json works and IGV is now snappy. Have a great new year!

**Comment by jrobinso** [comment]
@kentawan OK, thanks for getting back to us.    Yes it should be snappier with everything local.
