### ISSUE TITLE
Loading BAM via URL, Index file not found

### ISSUE THREAD

**Issue by olingerc** [igvteam/igv#109]
Hi,
I use the url load route to get my files and encounter the following issue:

```
http://localhost:60151/load?file=http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam
```

gives the following error: Index file not found. Enter path to index file.
When typing

```
http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai
```

in my browser, the file is correctly donwloaded.
When typing a bogus url:

```
http://localhost:60151/load?file=http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam.bogus
```

IGV complains: File not found. So i guess IGV finds my bam file but does not want to take the bai file which is at the exact same location.

Any ideas? 
Note: the index with a bam.bai extension is also in the same directory just to be sure

Log:

```
INFO [2014-11-27 09:10:54,671] [CommandListener.java:129]  GET /load?file=http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam HTTP/1.1
INFO [2014-11-27 09:10:54,672] [IGV.java:1593]  Loading 1 resources.
INFO [2014-11-27 09:10:54,672] [TrackLoader.java:112]  Loading resource, path http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam
ERROR [2014-11-27 09:10:56,913] [TrackLoader.java:270]  An error occurred while accessing:    http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai<br>Index file not found: http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai
org.broad.igv.exceptions.DataLoadException: An error occurred while accessing:    http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai<br>Index file not found: http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai
    at org.broad.igv.sam.reader.BAMHttpReader.loadIndexFile(BAMHttpReader.java:252)
    at org.broad.igv.sam.reader.BAMHttpReader.getIndexFile(BAMHttpReader.java:198)
    at org.broad.igv.sam.reader.BAMHttpReader.<init>(BAMHttpReader.java:65)
    at org.broad.igv.sam.reader.AlignmentReaderFactory.getReader(AlignmentReaderFactory.java:77)
    at org.broad.igv.sam.reader.AlignmentReaderFactory.getReader(AlignmentReaderFactory.java:45)
    at org.broad.igv.sam.AlignmentDataManager.<init>(AlignmentDataManager.java:66)
    at org.broad.igv.track.TrackLoader.loadAlignmentsTrack(TrackLoader.java:924)
    at org.broad.igv.track.TrackLoader.load(TrackLoader.java:192)
    at org.broad.igv.track.TrackLoader.load(TrackLoader.java:98)
    at org.broad.igv.ui.IGV.load(IGV.java:1700)
    at org.broad.igv.ui.IGV$11.run(IGV.java:1614)
    at org.broad.igv.ui.IGV.loadResources(IGV.java:1627)
    at org.broad.igv.ui.IGV$5.run(IGV.java:705)
    at org.broad.igv.util.LongRunningTask.submit(LongRunningTask.java:42)
    at org.broad.igv.ui.IGV.loadTracks(IGV.java:717)
    at org.broad.igv.batch.CommandExecutor.loadFiles(CommandExecutor.java:470)
    at org.broad.igv.batch.CommandListener.processGet(CommandListener.java:299)
    at org.broad.igv.batch.CommandListener.processClientSession(CommandListener.java:160)
    at org.broad.igv.batch.CommandListener.run(CommandListener.java:85)
    at java.lang.Thread.run(Thread.java:745)
ERROR [2014-11-27 09:10:56,914] [IGV.java:1618]  Error loading track
org.broad.igv.exceptions.DataLoadException: An error occurred while accessing:    http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam<br>An error occurred while accessing:    http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai<br>Index file not found: http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai
    at org.broad.igv.track.TrackLoader.load(TrackLoader.java:271)
    at org.broad.igv.track.TrackLoader.load(TrackLoader.java:98)
    at org.broad.igv.ui.IGV.load(IGV.java:1700)
    at org.broad.igv.ui.IGV$11.run(IGV.java:1614)
    at org.broad.igv.ui.IGV.loadResources(IGV.java:1627)
    at org.broad.igv.ui.IGV$5.run(IGV.java:705)
    at org.broad.igv.util.LongRunningTask.submit(LongRunningTask.java:42)
    at org.broad.igv.ui.IGV.loadTracks(IGV.java:717)
    at org.broad.igv.batch.CommandExecutor.loadFiles(CommandExecutor.java:470)
    at org.broad.igv.batch.CommandListener.processGet(CommandListener.java:299)
    at org.broad.igv.batch.CommandListener.processClientSession(CommandListener.java:160)
    at org.broad.igv.batch.CommandListener.run(CommandListener.java:85)
    at java.lang.Thread.run(Thread.java:745)
INFO [2014-11-27 09:10:56,914] [MessageUtils.java:60]  Error loading http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam: An error occurred while accessing:    http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bam<br>An error occurred while accessing:    http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai<br>Index file not found: http://localhost:84/bioseq/analysis_data/5475cc42de316d405bd0ec61/3_S3.bai
```

**Comment by olingerc** [comment]
Many thanks to whomever implemented the bypass proxy setting in the latest IGV version!!!
