### ISSUE TITLE
The icon should not be null 

### ISSUE THREAD

**Issue by ws6** [igvteam/igv#1237]
I got an exception in 2.14.1

`INFO [Oct 19,2022 15:09] [Main] Startup  IGV Version 2.14.1 09/02/2022 12:22 AM
INFO [Oct 19,2022 15:09] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [Oct 19,2022 15:09] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Oct 19,2022 15:09] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8   
INFO [Oct 19,2022 15:09] [Main] OS: Windows Server 2016 10.0 amd64
INFO [Oct 19,2022 15:09] [Main] IGV Directory: C:\Users\xxx\igv
SEVERE [Oct 19,2022 15:09] [DefaultExceptionHandler] Unhandled exception
SEVERE [Oct 19,2022 15:09] [DefaultExceptionHandler] java.lang.IllegalArgumentException: The icon should not be null.
	at jide.common@3.7.3/com.jidesoft.icons.MenuCheckIcon.<init>(MenuCheckIcon.java:29)
	at jide.common@3.7.3/com.jidesoft.plaf.vsnet.VsnetWindowsUtils.initComponentDefaultsWithMenu(VsnetWindowsUtils.java:650)
	at jide.common@3.7.3/com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:864)
	at jide.common@3.7.3/com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:632)
	at jide.common@3.7.3/com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:597)
	at org.igv/org.broad.igv.ui.Main.initializeLookAndFeel(Main.java:349)
	at org.igv/org.broad.igv.ui.Main.open(Main.java:285)
	at org.igv/org.broad.igv.ui.Main.lambda$main$0(Main.java:121)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
`

**Comment by jrobinso** [comment]
Thanks for the report.  Is this causing an issue, or just something you noticed in the log?   Have you made local changes to the Java or IGV "look and feel"?

**Comment by ws6** [comment]
Thanks for the reply.
it is causing an issue.
Let me provide a bit more details.
when clicked the igv icon(and we tried command line to open too), there is a console opened and closed. There is never any GUI showed up.
The log shows above errors. and it is being very consistent.

This is also a very strange error. Other users can use their installed/re-installed igv is just fine as a fresh user(no custom profile or genomes downloaded). but only this user(xxxx) has this issue. She has been using it in the past was just fine.
I traced down to jide GUI library. 
It looks like this line got this error 

https://github.com/jidesoft/jide-oss/blob/ed1e91b78d313a021573278248d34a6a2edf2861/src/com/jidesoft/plaf/vsnet/VsnetWindowsUtils.java#L654

Thanks,
-Jingtao

**Comment by jrobinso** [comment]
This is the first report of this, and I can't reproduce it, so at the moment I'm not sure what to suggest.   Leave this open, but I don't have a quick solution.

**Comment by ws6** [comment]
We can survive without fixing it.  
our work around  is to switch another windows user. 
I will let you know if it happened again with more details.
Thanks for such quick response.

**Comment by jrobinso** [comment]
One guess is the user has something in their global Java preferences that specifies a particular Java "Look and Feel".

**Comment by susan-sheehan** [comment]
We can report similar behavior on a Windows machine, I found this thred trying to trouble shoot.

**Comment by jrobinso** [comment]
@susan-sheehan There is not enough information there for us to work with.    At a minimum we need a stack trace, which you can find in the igv log.   It will be located in an "igv" folder in the users home directory.  Logs are named with the pattern "igvX.log.Y",  where X and Y are integers.   If there are multiple logs check the most recent one.   Or you can zip it and attach it here.

If IGV is working for one user and not another on the same machine then we probably need to examine differences in the user's environment variables, or "Java" settings that are stored in the users registry.   Obviously we can't do that from here.
