### ISSUE TITLE
O. sativa genome can't be loaded

### ISSUE THREAD

**Issue by tony-travis** [igvteam/igv#1253]
I've upgraded from Ubuntu-MATE 20.04 LTS to 22.04 LTS and IGV can no longer download the O. sativa genome. I'm using the IGV packaged by the Debian-Med project. The IGV version packaged in 20.04 works, but the version in 22.04 does not:

```codetype
manager@orca:~$ lsb_release -d
Description:	Ubuntu 20.04.5 LTS
manager@orca:~$ apt policy igv
igv:
  Installed: 2.4.17+dfsg-1
  Candidate: 2.4.17+dfsg-1
  Version table:
 *** 2.4.17+dfsg-1 500
        500 http://gb.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
        100 /var/lib/dpkg/status

manager@wildcat:~$ lsb_release -d
Description:	Ubuntu 22.04.1 LTS
manager@wildcat:~$ apt policy igv
igv:
  Installed: 2.12.0+dfsg-1
  Candidate: 2.12.0+dfsg-1
  Version table:
 *** 2.12.0+dfsg-1 500
        500 http://gb.archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu jammy/multiverse i386 Packages
        100 /var/lib/dpkg/status

```

I installed the 2.4.17 version manually under Ubuntu-MATE 22.04 LTS and I can download the O. sativa genome. However I get an error when trying the 2.12.0 version and the same error occurs using the latest 2.15.2 version:

```codetype
s03at9@wildcat:~$ /usr/bin/igv
INFO [Nov 09,2022 16:49] [Main] Startup  IGV Version user not_set
INFO [Nov 09,2022 16:49] [Main] Java 11.0.16 (build 11.0.16+8-post-Ubuntu-0ubuntu122.04) 2022-07-19
INFO [Nov 09,2022 16:49] [Main] Java Vendor: Ubuntu https://ubuntu.com/
INFO [Nov 09,2022 16:49] [Main] JVM: OpenJDK 64-Bit Server VM    
INFO [Nov 09,2022 16:49] [Main] OS: Linux 5.15.0-46-generic amd64
INFO [Nov 09,2022 16:49] [Main] IGV Directory: /home/s03at9/igv
INFO [Nov 09,2022 16:49] [GenomeManager] Loading genome: /home/s03at9/igv/genomes/osativa_7.genome
SEVERE [Nov 09,2022 16:49] [MessageUtils] Error loading genome: osativa_7
SEVERE [Nov 09,2022 16:49] [MessageUtils] java.io.FileNotFoundException: File not found: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/osativa_7.fai
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:862)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:649)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:645)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:324)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:318)
	at org.broad.igv.util.ParsingUtils.openInputStreamGZ(ParsingUtils.java:128)
	at org.broad.igv.util.ParsingUtils.openInputStream(ParsingUtils.java:103)
	at org.broad.igv.util.ParsingUtils.openBufferedReader(ParsingUtils.java:86)
	at org.broad.igv.feature.genome.fasta.FastaIndex.parseIndexFile(FastaIndex.java:89)
	at org.broad.igv.feature.genome.fasta.FastaIndex.<init>(FastaIndex.java:55)
	at org.broad.igv.feature.genome.fasta.FastaIndexedSequence.<init>(FastaIndexedSequence.java:65)
	at org.broad.igv.feature.genome.fasta.FastaIndexedSequence.<init>(FastaIndexedSequence.java:56)
	at org.broad.igv.feature.genome.load.DotGenomeLoader.loadGenome(DotGenomeLoader.java:104)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:197)
	at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:175)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:1946)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

SEVERE [Nov 09,2022 16:49] [MessageUtils] Error loading genome: osativa_7
SEVERE [Nov 09,2022 16:49] [IGV] Error loading genome: osativa_7
SEVERE [Nov 09,2022 16:49] [IGV] java.io.FileNotFoundException: File not found: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/osativa_7.fai
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:862)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:649)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:645)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:324)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:318)
	at org.broad.igv.util.ParsingUtils.openInputStreamGZ(ParsingUtils.java:128)
	at org.broad.igv.util.ParsingUtils.openInputStream(ParsingUtils.java:103)
	at org.broad.igv.util.ParsingUtils.openBufferedReader(ParsingUtils.java:86)
	at org.broad.igv.feature.genome.fasta.FastaIndex.parseIndexFile(FastaIndex.java:89)
	at org.broad.igv.feature.genome.fasta.FastaIndex.<init>(FastaIndex.java:55)
	at org.broad.igv.feature.genome.fasta.FastaIndexedSequence.<init>(FastaIndexedSequence.java:65)
	at org.broad.igv.feature.genome.fasta.FastaIndexedSequence.<init>(FastaIndexedSequence.java:56)
	at org.broad.igv.feature.genome.load.DotGenomeLoader.loadGenome(DotGenomeLoader.java:104)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:197)
	at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:175)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:1946)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

INFO [Nov 09,2022 16:49] [GenomeManager] Loading genome: /home/s03at9/igv/genomes/hg19.genome
INFO [Nov 09,2022 16:49] [ShutdownThread] Shutting down
```

**Comment by jrobinso** [comment]
Yes, it appears that this genome will not work with newer versions of IGV.  I think this one dates back to 2009, and is one of a few  for which supporting files are no longer compatible.   I will treat this as a request for support for O. Sativa v7 in newer versions of IGV.  This might take a few days.

**Comment by jrobinso** [comment]
Could you confirm that this is the assembly requested?

https://phytozome-next.jgi.doe.gov/info/Osativa_v7_0

**Comment by jrobinso** [comment]
Actually this might be a problem, the files at the link above are protected.    I think actually this might be the reason it was dropped.  I have found what I think is the same assembly available through NCBI,  here,  if you know could you confirm this is the case? 
https://www.ncbi.nlm.nih.gov/genome/?term=txid39947

**Comment by tony-travis** [comment]
> Could you confirm that this is the assembly requested?
> 
> https://phytozome-next.jgi.doe.gov/info/Osativa_v7_0

Hi, Jim.

Yes, it's the MSU v7 assembly of O. sativa Nipponbare that I want to use.

Thanks,

  Tony.

**Comment by tony-travis** [comment]
I'm using IGV to view alignments from the 3K Rice genomes project:
https://academic.oup.com/gigascience/article/3/1/2047-217X-3-7/2682915
These were aligned using BWA to the temperate japonica Nipponbare reference genome:
Unified-build release Os-Nipponbare-Reference-IRGSP-1.0 (IRGSP-1.0)
Kawahara Y,  De la Bastide M,  Hamilton JP,  Kanamori H,  McCombie WR,  Ouyang S,  Schwartz DC,  Tanaka T,  Wu J,  Zhou S,  Childs KL,  Davidson RM,  Lin H,  Quesada-Ocampo L,  Vaillancourt B,  Sakai H,  Lee SS,  Kim J,  Numa H,  Itoh T,  Buell CR,  Matsumoto T. , 2013Improvement of the Oryza sativa Nipponbare reference genome using next generation sequence and optical map data, Rice, vol. 6 pg. 4  10.1186/1939-8433-6-4

**Comment by tony-travis** [comment]
This is the NCBI entry:
https://www.ncbi.nlm.nih.gov/assembly/GCF_001433935.1/

**Comment by tony-travis** [comment]
It would be very useful to have the MSU v7 assembly and annotations as well:
http://rice.uga.edu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_7.0/

**Comment by jrobinso** [comment]
I do not see a fasta file in the link for the rice genome you supplied, if I have missed it please point me to a specific file.  

We should be able to host the NCBI entry.

**Comment by tony-travis** [comment]
Sorry, I wasn't clear: MSU v7 are annotations of the IRGSP-1.0 (o.sativa Nipponbare) assembly

**Comment by jrobinso** [comment]
Ahh, so if they are annotations of the sam sequence yes it should work.  You know you can load any annotation from the file menu,  but first I need to add the sequence.  I'll try to do it next week.

**Comment by jrobinso** [comment]
There are 2 naming conventions for the chromosomes of this assembly,

*  Chromosome numbers:  chr1, chr2, ....
*  Genbank:  AP014957.1, AP014958.1, ...
*  Refseq: NC_029256.1, NC_029257.1, ...

They can be aliased, but which convention will be more natural?   UCSC uses the refseq names in their browser.


[AP014957.1](https://www.ncbi.nlm.nih.gov/nuccore/AP014957.1)

<img width="754" alt="Screen Shot 2022-11-14 at 8 43 28 PM" src="https://user-images.githubusercontent.com/933148/201828406-ecfeb14e-2281-48ea-96ea-0c4df0868cde.png">

**Comment by jrobinso** [comment]
I'm inclined to go with "1, 2, 3, ..." for what the user sees.   All these names will be aliased internally so its just a presentation thing.

**Comment by maximilianh** [comment]
UCSC will show "chr1", "chr2", etc. soon, we just haven't found the time
yet. The chromAlias system is in place and you can load annotations with
"chr1" as custom tracks and track hubs, just the display of the chrom name
on the main page has not changed yet.

**Comment by tony-travis** [comment]
The O. sativa (release 7.0) genome in older versions of IGV use Chr1, Chr2...

**Comment by maximilianh** [comment]
I see that UCSC indeed uses the NC_xxxx numbers instead of chr1. This is a
configuration error, sorry. We'll fix this.
https://genome.ucsc.edu/h/GCF_001433935.1

**Comment by jrobinso** [comment]
@tony-travis This is now added.  Thanks to tremendous work by @maximilianh  and the UCSC GenArk team there are a number of tracks available from "Load from Server" that weren't available before.   These are hosted at the GenArk site https://hgdownload.soe.ucsc.edu/hubs/.    Also, you should be able to blat this genome using UCSC servers with the next IGV release.
