### ISSUE TITLE
IGVTools GUI: Headless Exception on Mac

### ISSUE THREAD

**Issue by gailrosen** [igvteam/igv#1280]
Anyone know what's causing this?  Just igv.sh seems to run fine

MacBook-Pro:IGV_2.16.0 username$ ./igvtools gui
Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
INFO [Jan 30,2023 16:15] [Globals] Development mode is enabled
SEVERE [Jan 30,2023 16:15] [IgvTools] null
SEVERE [Jan 30,2023 16:15] [IgvTools] java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
	at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:276)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:210)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:158)
	at org.igv/org.broad.igv.ui.IGVDialog.<init>(IGVDialog.java:11)
	at org.igv/org.broad.igv.tools.IgvToolsGui.<init>(IgvToolsGui.java:75)
	at org.igv/org.broad.igv.tools.IgvToolsGui.launch(IgvToolsGui.java:577)
	at org.igv/org.broad.igv.tools.IgvToolsGui.main(IgvToolsGui.java:571)
	at org.igv/org.broad.igv.tools.IgvTools.launchGUI(IgvTools.java:1278)
	at org.igv/org.broad.igv.tools.IgvTools.run(IgvTools.java:285)
	at org.igv/org.broad.igv.tools.IgvTools.main(IgvTools.java:254)

**Comment by jrobinso** [comment]
I'm not sure, probably an outdated igvtools gui script.   However you can
open the igvtools gui from IGV itself from the tools menu.   The "gui"
option for igvtools might be removed in the next release.

**Comment by gailrosen** [comment]
lol.. that did it -- Thanks!

________________________________________
