### ISSUE TITLE
Errors when opening saved session files

### ISSUE THREAD

**Issue by RichardCorbett** [igvteam/igv#1285]
Hi there.

I am trying to create sessions in IGV to share with others on my network.    I can load my reference and bam without problem as well as save to a session file without error.     When I start a new session and try to load my recently saved session file i get a dialog saying "Error loading track: [Track : null]".

is there something I should be changing?   I tried also with 2.14.0 and got similar results.

Here is the full trace on the command line during my loading, saving, and loading.

```
/home/rcorbett/bin/IGV_Linux_2.16.0/igv.sh 
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
INFO [Feb. 16,2023 07:22] [Globals] Development mode is enabled
INFO [Feb. 16,2023 07:22] [Main] Startup  IGV Version 2.16.0 01/25/2023 01:50 PM
INFO [Feb. 16,2023 07:22] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [Feb. 16,2023 07:22] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Feb. 16,2023 07:22] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8   
INFO [Feb. 16,2023 07:22] [Main] OS: Linux 3.10.0-957.5.1.el7.x86_64 amd64
INFO [Feb. 16,2023 07:22] [Main] IGV Directory: /home/rcorbett/igv
INFO [Feb. 16,2023 07:22] [Main] Resoluction scale = 2.2369621E7
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO [Feb. 16,2023 07:22] [AmazonUtils] AWS default credentials found. AWS support enabled.
INFO [Feb. 16,2023 07:22] [CommandListener] Listening on port 60151
INFO [Feb. 16,2023 07:22] [GenomeManager] Loading genome: /projects/alignment_references/Homo_sapiens/hg38_no_alt_TCGA_HTMCP_HPVs/genome/fasta/hg38_no_alt_TCGA_HTMCP_HPVs.fa
Gtk-Message: 07:22:57.413: GtkDialog mapped without a transient parent. This is discouraged.

(java:163692): dconf-WARNING **: 07:23:06.902: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c455ae7eeb61435787a489ee5ea70617 --binary-syntax --close-stderr”: Child process exited with code 1
INFO [Feb. 16,2023 07:23] [TrackLoader] Loading resource:  /projects/rcorbettprj2/rader/duplicate_integration_check/HTMCP-03-06-02341-01A-01R_A71871.bam
Gtk-Message: 07:24:15.033: GtkDialog mapped without a transient parent. This is discouraged.

(java:163692): dconf-WARNING **: 07:24:22.745: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c455ae7eeb61435787a489ee5ea70617 --binary-syntax --close-stderr”: Child process exited with code 1
Gtk-Message: 07:24:35.898: GtkDialog mapped without a transient parent. This is discouraged.

(java:163692): dconf-WARNING **: 07:24:41.063: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c455ae7eeb61435787a489ee5ea70617 --binary-syntax --close-stderr”: Child process exited with code 1
INFO [Feb. 16,2023 07:24] [GenomeManager] Loading genome: /projects/alignment_references/Homo_sapiens/hg38_no_alt_TCGA_HTMCP_HPVs/genome/fasta/hg38_no_alt_TCGA_HTMCP_HPVs.fa
INFO [Feb. 16,2023 07:24] [TrackLoader] Loading resource:  /projects/analysis34/A71871/merge85708_star-2.5.2b-XSv1-sb0.7.1/125bp/hg38_no_alt_TCGA_HTMCP_HPVs_ensembl100_gsc_v1/A71871_1_lane_dupsFlagged.bam
SEVERE [Feb. 16,2023 07:24] [IGVSessionReader] Error restoring track: [Track: null]
SEVERE [Feb. 16,2023 07:24] [IGVSessionReader] java.lang.NullPointerException
	at org.igv/org.broad.igv.sam.SpliceJunctionTrack.unmarshalXML(SpliceJunctionTrack.java:387)
	at org.igv/org.broad.igv.session.IGVSessionReader.processTrack(IGVSessionReader.java:934)
	at org.igv/org.broad.igv.session.IGVSessionReader.processPanel(IGVSessionReader.java:832)
	at org.igv/org.broad.igv.session.IGVSessionReader.process(IGVSessionReader.java:373)
	at org.igv/org.broad.igv.session.IGVSessionReader.process(IGVSessionReader.java:1089)
	at org.igv/org.broad.igv.session.IGVSessionReader.processRootNode(IGVSessionReader.java:295)
	at org.igv/org.broad.igv.session.IGVSessionReader.loadSession(IGVSessionReader.java:192)
	at org.igv/org.broad.igv.ui.IGV.loadSessionFromStream(IGV.java:1039)
	at org.igv/org.broad.igv.ui.IGV.loadSession(IGV.java:975)
	at org.igv/org.broad.igv.ui.action.OpenSessionMenuAction.lambda$actionPerformed$0(OpenSessionMenuAction.java:89)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Here is my session file:
```
cat igv_session_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Session genome="../../../alignment_references/Homo_sapiens/hg38_no_alt_TCGA_HTMCP_HPVs/genome/fasta/hg38_no_alt_TCGA_HTMCP_HPVs.fa" locus="chr2:145677076-145677646" version="8">
    <Resources>
        <Resource path="HTMCP-03-06-02341-01A-01R_A71871.bam" type="bam"/>
    </Resources>
    <Panel height="8283" name="Panel1676560987505" width="1901">
        <Track attributeKey="HTMCP-03-06-02341-01A-01R_A71871.bam Coverage" autoScale="true" clazz="org.broad.igv.sam.CoverageTrack" fontSize="10" id="/projects/rcorbettprj2/rader/duplicate_integration_check/HTMCP-03-06-02341-01A-01R_A71871.bam_coverage" name="HTMCP-03-06-02341-01A-01R_A71871.bam Coverage" snpThreshold="0.8" visible="true">
            <DataRange baseline="0.0" drawBaseline="true" flipAxis="false" maximum="11865.0" minimum="0.0" type="LINEAR"/>
        </Track>
        <Track attributeKey="HTMCP-03-06-02341-01A-01R_A71871.bam Junctions" autoScale="false" clazz="org.broad.igv.sam.SpliceJunctionTrack" fontSize="10" groupByStrand="false" height="60" id="/projects/rcorbettprj2/rader/duplicate_integration_check/HTMCP-03-06-02341-01A-01R_A71871.bam_junctions" maxdepth="50" name="HTMCP-03-06-02341-01A-01R_A71871.bam Junctions" visible="true"/>
        <Track attributeKey="HTMCP-03-06-02341-01A-01R_A71871.bam" clazz="org.broad.igv.sam.AlignmentTrack" color="185,185,185" displayMode="SQUISHED" experimentType="RNA" fontSize="10" id="/projects/rcorbettprj2/rader/duplicate_integration_check/HTMCP-03-06-02341-01A-01R_A71871.bam" name="HTMCP-03-06-02341-01A-01R_A71871.bam" visible="true">
            <RenderOptions sortOption="MATE_CHR"/>
        </Track>
    </Panel>
    <Panel height="87" name="FeaturePanel" width="1901">
        <Track attributeKey="Reference sequence" clazz="org.broad.igv.track.SequenceTrack" fontSize="10" id="Reference sequence" name="Reference sequence" sequenceTranslationStrandValue="POSITIVE" shouldShowTranslation="false" visible="true"/>
    </Panel>
    <PanelLayout dividerFractions="0.007281553398058253,0.8883495145631068"/>
    <HiddenAttributes>
        <Attribute name="DATA FILE"/>
        <Attribute name="DATA TYPE"/>
        <Attribute name="NAME"/>
    </HiddenAttributes>
</Session>
```

**Comment by jrobinso** [comment]
I'll look into it.  Is this rna-seq data?

**Comment by RichardCorbett** [comment]
Yessir.  The bam contains illumina reads aligned by STAR to a reference containing hg38 and HPV.

thanks!
Richard

**Comment by jrobinso** [comment]
I'm not able to reproduce this yet, or see a path that would cause this to occur.   Have you hand-edited the XML in any way?   Also, have you change preferences in the Alignments or RNA tabs?  Specifically preferences related to the Splice Junction track.

I think I can build in protections against this error, but I would feel better if I could reproduce it.

**Comment by RichardCorbett** [comment]
Oooh.  I may be that I had deleted the split-junction track! (sorry for the delay, I was travelling).

**Comment by RichardCorbett** [comment]
Just tested by loading a sample and saving the session without deleting the junction track but got the same error.

Not sure if it matters, but I'm running igv through an x-connection.

**Comment by jrobinso** [comment]
First aplogoies for the long delay in responding.  I can't reproduce it in the latest release (2.16.0),  and I can't correlate the line numbers in your stack trace with the current code.   If this is still an issue and you can reproduce this with the current code or latest release please reopen.

**Comment by kpalin** [comment]
I think I've come across this same issue and it seems to be due to paths in the Resource section of the session file.  Below, the '<' rows are from igv and produce NullPointerException and after hand editing to '>' lines, the session load fine.

```
4,7c4,7
<         <Resource path="Fam_s205_1_04-0217TK_T.final.cram-filtered.chm13v2.vcf.gz" type="vcf"/>
<         <Resource path="somatic/longshot/Fam_s205_1_04_0217TK.longshot.snv.chr20.filtered.vcf.gz" type="vcf"/>
<         <Resource path="../../../../mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s205_1_19_0707NK/align/Fam_s205_1_19_0707NK.phased.raw.cram" type="cram"/>
<         <Resource path="../../../../mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s205_1_04_0217TK/align/Fam_s205_1_04_0217TK.phased.raw.cram" type="cram"/>
---
>         <Resource path="//home/kpalin/software/ONT_hg_somatic/Fam_s205_1_04-0217TK_T.final.cram-filtered.chm13v2.vcf.gz" type="vcf"/>
>         <Resource path="/home/kpalin/software/ONT_hg_somatic/somatic/longshot/Fam_s205_1_04_0217TK.longshot.snv.chr20.filtered.vcf.gz" type="vcf"/>
>         <Resource path="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s205_1_19_0707NK/align/Fam_s205_1_19_0707NK.phased.raw.cram" type="cram"/>
>         <Resource path="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s205_1_04_0217TK/align/Fam_s205_1_04_0217TK.phased.raw.cram" type="cram"/>
17c17
```
The track lines (and the id:s) are like 
```
<Track attributeKey="Fam_s205_1_19_0707NK.phased.raw.cram" clazz="org.broad.igv.sam.AlignmentTrack" color="185,185,185" displayMode="EXPANDED" experimentType="THIRD_GEN" fontSize="10" id="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s205_1_19_0707NK/align/Fam_s205_1_19_0707NK.phased.raw.cram" name="Fam_s205_1_19_0707NK.phased.raw.cram" visible="true">
```

Both writing and reading the session file is done on same environment with IGV version 2.16.1


The exception backtrace is 
```
SEVERE [Oct 02,2023 09:10] [IGVSessionReader] Error restoring track: [Track: null]
SEVERE [Oct 02,2023 09:10] [IGVSessionReader] java.lang.NullPointerException
	at org.igv/org.broad.igv.sam.SpliceJunctionTrack.unmarshalXML(SpliceJunctionTrack.java:387)
	at org.igv/org.broad.igv.session.IGVSessionReader.processTrack(IGVSessionReader.java:934)
	at org.igv/org.broad.igv.session.IGVSessionReader.processPanel(IGVSessionReader.java:832)
	at org.igv/org.broad.igv.session.IGVSessionReader.process(IGVSessionReader.java:373)
	at org.igv/org.broad.igv.session.IGVSessionReader.process(IGVSessionReader.java:1089)
	at org.igv/org.broad.igv.session.IGVSessionReader.processRootNode(IGVSessionReader.java:295)
	at org.igv/org.broad.igv.session.IGVSessionReader.loadSession(IGVSessionReader.java:192)
	at org.igv/org.broad.igv.ui.IGV.loadSessionFromStream(IGV.java:1039)
	at org.igv/org.broad.igv.ui.IGV.loadSession(IGV.java:975)
	at org.igv/org.broad.igv.ui.action.OpenSessionMenuAction.lambda$actionPerformed$0(OpenSessionMenuAction.java:89)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jrobinso** [comment]
@kpalin Thanks for the stack trace, that's really helpful.   

Unless you have a need for relative paths in sessions I suggest switching to absolute paths.  This will become the default in the next release.  To do this select "View > Preferences" and uncheck "Use relative paths in session files".  


<img width="300" alt="Screen Shot 2023-10-01 at 11 45 04 PM" src="https://github.com/igvteam/igv/assets/933148/3fadce96-8766-482a-9733-2435d276bab8">

**Comment by kpalin** [comment]
Can confirm unticking the relative paths option appeared to solve the issue.  Thanks.

**Comment by jrobinso** [comment]
@kpalin Can I ask you what the absolute path to your session file was/is?   And was it moved after creation?   I'm trying to figure out what went wrong.

The relative paths are relative to the session file.  Its useful if you want to share sessions with users who might have drives mapped differently that the creator.  For example one is on a Mac and one on a PC,  both using the same shared session.   Of course its not useful at all when it doesn't work.

**Comment by kpalin** [comment]
Here's a diff of two sessions files just created and not moved, one with relative other with absolute paths.  The absolute path version works, relative doesn't. Same even with no '../' paths.

```
/mnt/cgnano/projects/promethion/230502/ont_pipe_chm13v2/Fam_s1550_1_18_0764TK$ diff igv_session_relative.xml igv_session.xml 
2c2
< <Session genome="chm13v2.0" locus="chr9:103564571-103565268" nextAutoscaleGroup="3" version="8">
---
> <Session genome="chm13v2.0" locus="chr9:103564571-103565268" nextAutoscaleGroup="2" version="8">
5,8c5,8
<         <Resource path="sv/Fam_s1550_1_18_0764TK.phased.raw.cutesv.vcf.gz" type="vcf"/>
<         <Resource path="align/Fam_s1550_1_18_0764TK.phased.raw.cram" type="cram"/>
<         <Resource path="../Fam_s1550_1_18_0746NK/sv/Fam_s1550_1_18_0746NK.phased.raw.cutesv.vcf.gz" type="vcf"/>
<         <Resource path="../Fam_s1550_1_18_0746NK/align/Fam_s1550_1_18_0746NK.phased.raw.cram" type="cram"/>
---
>         <Resource path="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s1550_1_18_0764TK/sv/Fam_s1550_1_18_0764TK.phased.raw.cutesv.vcf.gz" type="vcf"/>
>         <Resource path="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s1550_1_18_0764TK/align/Fam_s1550_1_18_0764TK.phased.raw.cram" type="cram"/>
>         <Resource path="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s1550_1_18_0746NK/sv/Fam_s1550_1_18_0746NK.phased.raw.cutesv.vcf.gz" type="vcf"/>
>         <Resource path="/mnt/cgnano/projects/promethion/ont_pipe_pass_chm13v2-current/Fam_s1550_1_18_0746NK/align/Fam_s1550_1_18_0746NK.phased.raw.cram" type="cram"/>
```

**Comment by jrobinso** [comment]
OK, thanks.    And what is the absolute path to the session file?

**Comment by kpalin** [comment]
It's where I ran the `diff` command:  `/mnt/cgnano/projects/promethion/230502/ont_pipe_chm13v2/Fam_s1550_1_18_0764TK/`

**Comment by jrobinso** [comment]
Sessions are saved with absolute file paths for the next release, that should fix this sort of problem.   I don't know why your session(s) were not working,  the relative paths are correct to my eyes, but absolute paths avoid the problem altogether.
