### ISSUE TITLE
Loading CRAM files failed with release 2.16.0 

### ISSUE THREAD

**Issue by antonylebechec** [igvteam/igv#1286]
Dear IGVTeam,

Dealing with CRAM files, I used to open them with IGV (release 2.12.13). However, IGV release 2.16.0 doesn't open correctly CRAM files.

These CRAM files were generated using samtools (1.15.1) and these parameters: "version=3.0,level=9,no_ref" (version 3.0, compression level 9 and include references, i.e. all bases, no need reference genome)
and are indexed in crai

OS: Mac (intel)
IGV: MacApp 2.16.0 (with Java)

I tried also releases 2.13.2, 2.14.0, 2.15.4, and they failed too.

Do you have more information about this issue?

IGV [2.16.0]
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/40463532/219425314-34faaefa-22ec-49e2-a70f-edbba772596a.png">

IGV [2.12.13]
<img width="1562" alt="image" src="https://user-images.githubusercontent.com/40463532/219425094-4d19b4ae-8f26-4e66-92bd-4aefbdccb883.png">

**Comment by jrobinso** [comment]
It's hard to say what the problem is with screenshots, and this is the first report of this we have had.   All crams that I have tried load without error.    Could you share your igv.log file, it should have some diagnostic information.  Its located in an "igv" folder under your home directory, and will have a name like. "igv0.log" or similiar.   There could be several, we just need the log for the time you experienced the issue.   You can zip and attach here, or if you'd rather not have it public email  to igvteam (at) broadinstitute.org

**Comment by antonylebechec** [comment]
Dear @jrobinso,

Sure, screenshots were just to illustrate, in case you already had this issue.

So, here is the log file (IGV 2.16.0):

```
INFO [févr. 17,2023 12:20] [Main] Startup  IGV Version 2.16.0 01/25/2023 01:50 PM
INFO [févr. 17,2023 12:20] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [févr. 17,2023 12:20] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [févr. 17,2023 12:20] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8
INFO [févr. 17,2023 12:20] [Main] OS: Mac OS X 13.1 x86_64
INFO [févr. 17,2023 12:20] [Main] IGV Directory: /Users/lebechea/igv
INFO [févr. 17,2023 12:20] [CommandListener] Listening on port 60151
INFO [févr. 17,2023 12:20] [GenomeManager] Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
INFO [févr. 17,2023 12:20] [TrackLoader] Loading resource:  https://s3.amazonaws.com/igv.org.genomes/hg19/ncbiRefSeq.sorted.txt.gz
INFO [févr. 17,2023 12:21] [TrackLoader] Loading resource:  /Users/lebechea/STARK/output/repository/SOMATIC/SOLIDTUMOR/RUN_TEST_920/Sample4/STARK/Sample4.archive.cram
SEVERE [févr. 17,2023 12:21] [TrackLoader] null
SEVERE [févr. 17,2023 12:21] [TrackLoader] java.lang.NullPointerException
        at htsjdk@3.0.0/htsjdk.samtools.cram.structure.CRAMRecordReadFeatures.getByteOrDefault(CRAMRecordReadFeatures.java:498)
        at htsjdk@3.0.0/htsjdk.samtools.cram.structure.CRAMRecordReadFeatures.restoreReadBases(CRAMRecordReadFeatures.java:419)
        at htsjdk@3.0.0/htsjdk.samtools.cram.structure.CRAMCompressionRecord.restoreReadBases(CRAMCompressionRecord.java:468)
        at htsjdk@3.0.0/htsjdk.samtools.cram.structure.Slice.normalizeCRAMRecords(Slice.java:507)
        at htsjdk@3.0.0/htsjdk.samtools.cram.structure.Container.getSAMRecords(Container.java:322)
        at htsjdk@3.0.0/htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:112)
        at htsjdk@3.0.0/htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:204)
        at htsjdk@3.0.0/htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:608)
        at org.igv/org.broad.igv.sam.reader.WrappedIterator.hasNext(WrappedIterator.java:49)
        at org.igv/org.broad.igv.sam.AlignmentUtils.firstAlignments(AlignmentUtils.java:243)
        at org.igv/org.broad.igv.sam.AlignmentDataManager.inferType(AlignmentDataManager.java:400)
        at org.igv/org.broad.igv.sam.AlignmentTrack.init(AlignmentTrack.java:352)
        at org.igv/org.broad.igv.track.TrackLoader.loadAlignmentsTrack(TrackLoader.java:966)
        at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:161)
        at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1249)
        at org.igv/org.broad.igv.ui.IGV.loadResources(IGV.java:1179)
        at org.igv/org.broad.igv.ui.IGV$2.run(IGV.java:409)
        at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

SEVERE [févr. 17,2023 12:21] [IGV] Error loading track
SEVERE [févr. 17,2023 12:21] [IGV] java.lang.NullPointerException
        at org.igv/org.broad.igv.exceptions.DataLoadException.<init>(DataLoadException.java:38)
        at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:272)
        at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1249)
        at org.igv/org.broad.igv.ui.IGV.loadResources(IGV.java:1179)
        at org.igv/org.broad.igv.ui.IGV$2.run(IGV.java:409)
        at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Here are also the CRAM and CRAI files I used (just a test sample for devel):
[Sample4.archive.cram.zip](https://github.com/igvteam/igv/files/10766173/Sample4.archive.cram.zip)
[Sample4.archive.cram.crai.zip](https://github.com/igvteam/igv/files/10766175/Sample4.archive.cram.crai.zip)

Thanks for your help!

**Comment by antonylebechec** [comment]
I just test release 2.16.0 on a Windows system. It seems that the same issue append.

[igv0.log](https://github.com/igvteam/igv/files/10766301/igv0.log)

**Comment by antonylebechec** [comment]
Another test with Samtools shoxs that the CRAM file can be view:

```
$ samtools view Sample4.archive.cram | tail -n2
M01656:13:000000000-D02HD:1:1101:5314:6291	77	*	0	0	*	*	0	0	TTGCCAGTTAACGTCTTAAAAAGAAAGAGGAAAAAGGGAAAAAGGAAAAAAGAAGGGGAGAAAGTAAAAAGGACCGGCGCTAAAAAGGAATGAAGAGAAGCAACAACAAGGAAAGCCAACAAGGAAAGACTAGAAGTGAGAGAAGGCTCCGCTGCGCGGGGGTCCATGGGAAAGAAAAAAAGGAACAACCAAAAGAGGGAGAACAGTGAAGAAAGAATGGGACCTAGGAAGAAGTTAAGGAGAAAGAAGGC	;;;.;<<<<2<>9>??<22///200;<021000002110000010000000100210;<;0>/2<3444/100<</0,/;;/0///1000121/2120/;=00<;0.1;2000<?==@@;?02000020:;02:/2;2121;2;2;;?;;0.<0..-.....;;;1<<>.000100000001.00;10;-1000001..01;<;??>?>010001;0;;<>>><</10;01001<;/010;100;1001;;	BC:Z:CAGTAGTT-ACTTGAGT	OQ:Z:>>>1>BBB@3DFEFGGC33111000AB0000000000000000//00000///000/ABE/G11D22221//0BB////>E//111//00111111001<F10B<///<0/00@FFGHHEF/0/00000?<11?11>1111<.<0><G<<..C-.-------9AA/:BF--/--/-/-------/9--;-----/------;:9FFFFF//////9-9;:FFFBB///9/--//:;////9---9//-/;;	AS:i:0	XS:i:0	RG:Z:1-2138C620
M01656:13:000000000-D02HD:1:1101:5314:6291	141	*	0	0	*	*	0	0	GAGAAAAGGTGGGCGGGAGGAGAAGAGAAAGGGACCCAAAAAAAGAAAAGCAGAAAAGAAGATGGAGGATGGGAGAGGAGGCAACAGGAGAAGGTGCTGCTCGAAAAAAACGGATAGCGAGGGGAAAGAAAAAGTTCTCACCGGAAGGGATCCAGAGTAAAAAAGACAGAGAGAGAAGGAAGAGGAAAAACGGCAAAGGAGAGGAGGAGGAGGAAAGGGGAGGGGGAGACGAAAGGGGGGAGAGAAAGGGG	11;1/<<?10=;;=01001001002120//210<;;:1000000;00<=2<0?00/0<0021<2<>?>>?20001010010:10:0200100;1:2;>2.:?90000000/.;2<;??.01...211<010012;;1<<0;-0;002002;;.;<>;>/00000;;<??>?><>0001.00101.00000;;.-;001.0;0;.0;.01.01.0001...01.;../10;.0/<1....-01010001...	BC:Z:CAGTAGTT-ACTTGAGT	OQ:Z:11>11CCF11CAEG10///////001001110/BAE?//0////>/0BF0B1F0010B/001B1BFFGGH1//0////0//?/0?00/0//0<0?1CF11?F?/0//0--.->.CCFH------...:/.//..;;0=C09..9--....;;/;BFEF/////-;;BFFFFFBF--//--/------/--99--9--/--9-9--9---------/-------;-----;---:-----------///---	AS:i:0	XS:i:0	RG:Z:1-2138C620
```

Do you think there is a problem with the format? With tags on this file?

**Comment by jrobinso** [comment]
Thanks for the sample data, we will look into it.

**Comment by lbergelson** [comment]
@antonylebechec Thank you so much for the helpful bug report and the test data. 

It's a simple bug in the underlying htsjdk library.  I just built and tested a patch that should fix it.  I'll have to release a new htsjdk and then incorporate that into IGV.

**Comment by antonylebechec** [comment]
Thanks a lot IGV Team!!!
