### ISSUE TITLE
Can't save igv sessions

### ISSUE THREAD

**Issue by vinod1981** [igvteam/igv#1299]
I am using igv 2.13.1. I can't save igv sessions, it is giving an error. I have to reload all my files again and again to see them in igv.
Session error:
```
SEVERE [Mar 15,2023 16:11] [SaveSessionMenuAction] java.lang.RuntimeException: java.lang.NullPointerException
	at org.igv/org.broad.igv.session.SessionWriter.createXmlFromSession(SessionWriter.java:183)
	at org.igv/org.broad.igv.session.SessionWriter.saveSession(SessionWriter.java:91)
	at org.igv/org.broad.igv.ui.IGV.saveSession(IGV.java:1060)
	at org.igv/org.broad.igv.ui.action.SaveSessionMenuAction.actionPerformed(SaveSessionMenuAction.java:105)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.igv/org.broad.igv.util.FileUtils.getRelativePath(FileUtils.java:135)
	at org.igv/org.broad.igv.util.FileUtils.getRelativePath(FileUtils.java:196)
	at org.igv/org.broad.igv.session.SessionWriter.createXmlFromSession(SessionWriter.java:127)
	... 41 more
```
I could save only one session but after that every time it is giving this error.
Please see in to it.
Thanks,

**Comment by vinod1981** [comment]
@helgathorv Thanks for the quick reply. I am updating it and will let you know if still I can't save the sessions. Actually, I tried various session where I have loaded .bam files  with ref genome and gff file to track SNP variation. 
Thanks

**Comment by vinod1981** [comment]
@helgathorv ,
Today I updated to igv 2.16 but creating the session error persists. 
Here is the log:
```
INFO [Mar 16,2023 16:42] [CommandListener] Listening on port 60151
INFO [Mar 16,2023 16:42] [GenomeManager] Loading genome: ../AHAL_2.03_assembly.fasta
INFO [Mar 16,2023 16:43] [TrackLoader] Loading resource:  /prj/Alpine/gwas_log10_alpine/kmers/bowtie_align/pass_threshold_10per_filtered_kmers1.sort.bam
INFO [Mar 16,2023 16:43] [TrackLoader] Loading resource:  /prj/namefixed_plate4/80_EKDL190132027-2a-AK963-AK6693_HJFGTDSXX_L2.dedup.bam
INFO [Mar 16,2023 16:44] [TrackLoader] Loading resource:  /prj/namefixed_plate5/107_EKDL190132218-2a-AK5848-AK5137_HJHHCDSXX_L3.dedup.bam
INFO [Mar 16,2023 16:44] [TrackLoader] Loading resource:  /prj/namefixed_plate7/D639_EKDL200000637-1a-AK6507-AK6667_H2KGYDSXY_L4.dedup.bam
INFO [Mar 16,2023 16:44] [TrackLoader] Loading resource:  /prj/namefixed_plate3/451_EKDL190031784-2a-AK5160-AK6737_HJFGTDSXX_L1.dedup.bam
INFO [Mar 16,2023 16:44] [TrackLoader] Loading resource:  /prj/namefixed_plate3/79_EKDL190031784-2a-AK5156-AK6704_HJFGTDSXX_L1.dedup.bam
INFO [Mar 16,2023 16:44] [TrackLoader] Loading resource:  /prj/namefixed_plate3/181_EKDL190031784-2a-AK5845-AK6676_HJFGTDSXX_L1.dedup.bam
INFO [Mar 16,2023 16:45] [TrackLoader] Loading resource:  /prj/postGWAS_edit/20220520_AHAL_v.2.1.0_final_JGI2.gff3
SEVERE [Mar 16,2023 16:46] [SessionWriter] Error creating session.
SEVERE [Mar 16,2023 16:46] [SessionWriter] java.lang.NullPointerException
	at org.igv/org.broad.igv.util.FileUtils.getRelativePath(FileUtils.java:135)
	at org.igv/org.broad.igv.util.FileUtils.getRelativePath(FileUtils.java:196)
	at org.igv/org.broad.igv.session.SessionWriter.createXmlFromSession(SessionWriter.java:127)
	at org.igv/org.broad.igv.session.SessionWriter.saveSession(SessionWriter.java:91)
	at org.igv/org.broad.igv.ui.IGV.saveSession(IGV.java:1059)
	at org.igv/org.broad.igv.ui.action.SaveSessionMenuAction.actionPerformed(SaveSessionMenuAction.java:105)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```
I am using igv.sh file to open new session. 
Thanks,
Vinod

**Comment by jrobinso** [comment]
Its failing trying to decode a file path.   Can you share the session itself, or just the "resources" section at the top of the file?

**Comment by vinod1981** [comment]
@helgathorv,
I even don't know, how to share the session or about resource section. I couldn't find these options in my session.
Vinod

**Comment by vinod1981** [comment]
@jrobinso,
I am saving my session in a shared HPC cluster. 
Vinod

**Comment by jrobinso** [comment]
Where is the path you are saving to relative to your fasta path, which from the log is "../AHAL_2.03_assembly.fasta"?

A workaround for this would be to use absolute paths in your session.   You can enable this from your Preferences window, select View > Preferences and uncheck "Use relative paths in session files".   Of course if you want relative paths this is not a good workaround.

**Comment by vinod1981** [comment]
@jrobinso,
Yes, it worked. 
Thank you very much.
Vinod

**Comment by jrobinso** [comment]
How was this fasta (AHAL_2.03_assembly.fasta) loaded originally?  The path to a fasta should be absolute,  a relative path is indicative of another issue which is probably the root cause.

**Comment by jrobinso** [comment]
Thanks, but how did you actually load it? If you use the File browser it would report an absolute path.  Did you supply this path via a command line option, or some other way?

**Comment by vinod1981** [comment]
@jrobinso, 
I search all the files using browser, through File and than Load from File.

**Comment by jrobinso** [comment]
OK, thanks for following up.
