### ISSUE TITLE
NumberFormatException: For input string: "30000000000"

### ISSUE THREAD

**Issue by kcleal** [igvteam/igv#1301]
Im trying to open a pacbio HiFi bam (minimap2 aligned), but I am running into this error:

```
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
INFO [Mar 20,2023 12:46] [Globals] Development mode is enabled
INFO [Mar 20,2023 12:46] [Main] Startup  IGV Version 2.16.0 01/25/2023 01:50 PM
INFO [Mar 20,2023 12:46] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [Mar 20,2023 12:46] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Mar 20,2023 12:46] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8   
INFO [Mar 20,2023 12:46] [Main] OS: Linux 6.1.0-16-generic amd64
INFO [Mar 20,2023 12:46] [Main] IGV Directory: /home/kez/igv
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO [Mar 20,2023 12:46] [CommandListener] Listening on port 60151
INFO [Mar 20,2023 12:46] [GenomeManager] Loading genome: /home/kez/igv/genomes/hg19.json
INFO [Mar 20,2023 12:46] [TrackLoader] Loading resource:  https://s3.amazonaws.com/igv.org.genomes/hg19/ncbiRefSeq.sorted.txt.gz
INFO [Mar 20,2023 12:48] [TrackLoader] Loading resource:  /home/kez/Desktop/HG002.pacbio.bam
SEVERE [Mar 20,2023 12:48] [IGV] Error loading track data
SEVERE [Mar 20,2023 12:48] [IGV] java.util.concurrent.CompletionException: java.lang.NumberFormatException: For input string: "30000000000"
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: "30000000000"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.<init>(Unknown Source)
	at org.igv/org.broad.igv.prefs.IGVPreferences.getAsInt(IGVPreferences.java:158)
	at org.igv/org.broad.igv.sam.AlignmentDataManager.load(AlignmentDataManager.java:326)
	at org.igv/org.broad.igv.sam.CoverageTrack.load(CoverageTrack.java:186)
	at org.igv/org.broad.igv.ui.IGV.lambda$repaint$16(IGV.java:2267)
	... 4 more
```

Also a bit strange, if I load a paired-end sample first, and then load the pacbio data, everything works fine. I have tested with a local reference genome and the "Human GRCh37/hg19" from the drop down menu.

Thanks!

**Comment by jrobinso** [comment]
It looks like this is being thrown trying to read your user preferences.   Could you zip and attach them here, or if you prefer mail them to igvteam (at) broadinstitute.org?  You'll fin them in an "igv" folder in your home directory,  filename "prefs.properties".

**Comment by kcleal** [comment]
Ah ok, I have tried to configure IGV to run with a large max visible range, I guess this is causing an overflow. I reduced the max visible range and it resolved the issue, thanks!
