### ISSUE TITLE
Exporting tracks in SVG format are truncated on the right side and bottom part

### ISSUE THREAD

**Issue by mchlou** [igvteam/igv#1421]
Hi,

I encounter a bug. 

OS: Windows 10 Home
IGV Version: 2.16.2 07/14/23 Windows Version

I am trying to make an SVG snapshot of my read coverage graph, but I notice that when I export using SVG using right click option, the image is truncated.

![coverage_track_right_click_export](https://github.com/igvteam/igv/assets/68099529/e5193ad6-db53-4256-ad2b-e6e1ea33366e)

I tried using batch scripting but the problem persists and I also cannot save just a single track even if only one track is selected. I used the script below the resulting image is attached. 

`snapshotDirectory C:\Users\mchlo\Downloads\`
`maxPanelHeight 10000`
`goto NODE_22_length_8463_cov_181.909793`
`scrolltotrack Read Coverage`
`setDataRange auto`
`snapshot node22.svg`

![coverage_track_batch_scripting](https://github.com/igvteam/igv/assets/68099529/2eb3ff0c-5de7-4d4e-9060-ebd0f214a8b4)

Seems like the problem is only happens when saving a snapshot in SVG format and not with PNG as seen in the third image below. 
![coverage_track_PNG_right_click_export](https://github.com/igvteam/igv/assets/68099529/759d96f0-978b-49d7-9ccd-748d1b40f6fa)

I also notice that this happens when saving in IGV installed in WSL2 and computer seems like not a factor since I also tried this in IGV installed in Windows 11 on a separate computer. 

Solutions in these issues also failed to solve the problem :  #974, #1336

**Comment by jrobinso** [comment]
OK thanks for the report.  SVG in very zoomed out views, such as seen in this screenshot, is problematic.   That is a huge number of svg objects.    Can you see if there are any error messages in your igv.log file. (usually <user home>/igv/igv0.log)?

Unfortunately I can't give you any workaround other than using "png" output.

**Comment by mchlou** [comment]
Hello,

I can't seem to find the log file anywhere. Any other way to get the error messages?
Thorough search cannot find any log files within IGV installation folder. 

Sorry for that.

**Comment by jrobinso** [comment]
Its not in the installation folder, it should be in an "igv" folder in your home directory.   Usually C:\users\<your user name>\igv.

**Comment by mchlou** [comment]
Oh, thanks for that! I'm sorry I am not familiar with IGV 

Here is the entire content of the log file: 

```
INFO [Oct 23,2023 14:33] [Main] Startup  IGV Version 2.16.2 07/14/2023 12:24 AM
INFO [Oct 23,2023 14:33] [Main] Java 11.0.13 (build 11.0.13+8) 2021-10-19
INFO [Oct 23,2023 14:33] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Oct 23,2023 14:33] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8   
INFO [Oct 23,2023 14:33] [Main] OS: Windows 10 10.0 amd64
INFO [Oct 23,2023 14:33] [Main] IGV Directory: C:\Users\mchlo\igv
SEVERE [Oct 23,2023 14:33] [CommandListener] java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.PlainSocketImpl.bind0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketBind(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.<init>(Unknown Source)
	at java.base/java.net.ServerSocket.<init>(Unknown Source)
	at org.igv/org.broad.igv.batch.CommandListener.run(CommandListener.java:136)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by jrobinso** [comment]
Well that doesn't tell us much, it looks like you have 2 IGVs running (the NET_BIND message),  however that would not affect the SVG output.    Leave the issue open,  but I don't have any further suggestions at the moment, other than use PNG.   SVG is not going to work well for such a dense view, even if it completes few programs are going to handle it nicely due to the size.

**Comment by mchlou** [comment]
Thank you very much anyway. Your inputs are of big help.

**Comment by giovannabloise** [comment]
Hi! I'm facing the same issue...

PNG File
<img width="1854" height="928" alt="Image" src="https://github.com/user-attachments/assets/1ef937a7-4bf2-47ce-a845-eb076bbe44ca" />

SVG File

![Image](https://github.com/user-attachments/assets/0e1f2667-0261-4391-a183-d379fe00e998)

**Comment by jrobinso** [comment]
@giovannabloise What version of IGV are you using?
