### ISSUE TITLE
RefGet track doesn't migrate to new endpoints on newer versions?

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#1424]
Hello Jim,

One of our cancer curators noticed that her RefGet IGV track was gone, she had this configuration under `$HOME/igv/genomes/hg38.json`:

![Screenshot 2023-10-30 at 9 31 53 am](https://github.com/igvteam/igv/assets/175587/5ab515b4-3890-42c6-9c0a-30ba68e8f737)

I compared with mine and I had these (working) endpoints instead:

```
% cat igv/genomes/hg38.json
{
  "id": "hg38",
  "name": "Human (hg38)",
  "fastaURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
  "indexURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa.fai",
  "cytobandURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz",
  "tracks": [
    {
      "name": "Refseq Genes",
      "format": "refgene",
      "url": "https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz",
      "indexed": false,
      "visibilityWindow": -1,
      "removable": false,
      "order": 1000000
    }
  ]
}
```

We ended up fixing it by simply running `rm -rf $HOME/igv/genomes` and restarting IGV. 

Would it make sense to add some extra warning/messaging to the user or directly replace those S3 urls on disk if old non-working ones are detected?

Cheers!

**Comment by jrobinso** [comment]
Thanks for the report, the removal of that file was not intentional.  I
will restore it for backward compatibility.   We do not currently remove
files we think are being used.   The time will come when we have to do
that, but have not done so yet (intentionally).

There is a general problem of "stale" genome json files in users "igv"
directories.   This is partly intentional,  I don't like disturbing users
setups without explicit action on their part.   But it is a problem,  we
might need to add an opt-in auto-update or other messaging.    We are
slowly migrating all our amazon hosted files to UCSC hosted equivalents.

In the meantime users can always update to the latest genome json by
re-downloading it from the "Genomes" menu.

Leave this issue open as a reminder to self to deal with this stale-ness
issue.  I am also going to restore the missing files.

-- Jim

**Comment by brainstorm** [comment]
For the record, the paths that used to work for me on 2023, do no longer work:

```
INFO [Nov 28,2024 10:57] [TrackLoader] Loading resource:  https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz
SEVERE [Nov 28,2024 10:57] [TrackLoader] Unable to parse header with error: Access forbidden <br> , for input source: https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz
SEVERE [Nov 28,2024 10:57] [TrackLoader] htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Access forbidden <br> , for input source: https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz
	at htsjdk@4.1.2-module/htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:265)
	at htsjdk@4.1.2-module/htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:104)
	at htsjdk@4.1.2-module/htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:129)
	at htsjdk@4.1.2-module/htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:121)
	at htsjdk@4.1.2-module/htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:90)
	at org.igv/org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:132)
	at org.igv/org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:76)
	at org.igv/org.broad.igv.track.TrackLoader.loadTribbleFile(TrackLoader.java:454)
	at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:223)
	at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1277)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.restoreGenomeTracks(GenomeManager.java:258)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.setCurrentGenome(GenomeManager.java:217)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:194)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:142)
	at org.igv/org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:1981)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:73)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.broad.igv.exceptions.HttpResponseException: Access forbidden <br>
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:882)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:665)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:661)
	at org.igv/org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:368)
	at org.igv/org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:362)
	at org.igv/org.broad.igv.util.stream.IGVUrlHelper.openInputStream(IGVUrlHelper.java:42)
	at htsjdk@4.1.2-module/htsjdk.tribble.util.ParsingUtils.openInputStream(ParsingUtils.java:112)
	at htsjdk@4.1.2-module/htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:255)
	... 20 more

SEVERE [Nov 28,2024 10:57] [GenomeManager] Error loading genome annotations
SEVERE [Nov 28,2024 10:57] [GenomeManager] org.broad.igv.exceptions.DataLoadException: Unable to parse header with error: Access forbidden <br> , for input source: https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz
	at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:295)
	at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1277)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.restoreGenomeTracks(GenomeManager.java:258)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.setCurrentGenome(GenomeManager.java:217)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:194)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:142)
	at org.igv/org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:1981)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:73)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

So again, I had to `rm -rf $HOME/igv/genomes` to avoid those errors.

**Comment by jrobinso** [comment]
See my comment on #1625.   We have decided not to try to refresh "stale" genomes automatically.   Users can place their own modified genome files in igv/genomes,  and it would be bad form for us to write over them.   However, you do not need to remove genomes from the command line, simply refreshing from the "Genomes > Select Hosted Genome" menu should suffice.

**Comment by brainstorm** [comment]
Thanks Jim, closing here then!
