### ISSUE TITLE
Using IGVtools offline

### ISSUE THREAD

**Issue by gitMakeCoffee** [igvteam/igv#1463]
I have been trying to run IGVtools count offline.

It requires a genome file as input, which I have created with IGV, in accordance with the documentation:
https://github.com/igvteam/igv/wiki/Downloading-Hosted-Genomes-for-Offline-Use

Therefore, I have tried running the following command:
```igvtools count -w 5000 --minMapQuality 1 --pairs test.bam test.wig hg38.genome```

However, it looks like igvtools still tries to use an internet connection:
```
Using system JDK.
WARN [2023-12-25T14:11:14,215]  [Globals.java:135] [main]  Development mode is enabled
INFO [2023-12-25T14:11:14,242]  [DirectoryManager.java:180] [main]  IGV Directory: /home/user/igv
IGV Directory: /home/user/igv
INFO [2023-12-25T14:11:14,243]  [GenomeManager.java:183] [main]  Loading genome: /lustre/project/123/user/hg38.genome
Loading genome: /lustre/project/123/user/hg38.genome
ERROR [2023-12-25T14:11:34,773]  [GenomeListManager.java:378] [main]  Error fetching genome list: 
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:782) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:636) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:632) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:311) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:305) ~[igv.jar:?]
        at org.broad.igv.ui.commandbar.GenomeListManager.getServerGenomeMap(GenomeListManager.java:350) [igv.jar:?]
        at org.broad.igv.ui.commandbar.GenomeListManager.getServerGenomeIDs(GenomeListManager.java:279) [igv.jar:?]
        at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:206) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.loadGenome(IgvTools.java:1191) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.doCount(IgvTools.java:848) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.run(IgvTools.java:371) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.main(IgvTools.java:254) [igv.jar:?]
Error fetching genome list: 
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:782) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:636) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:632) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:311) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:305) ~[igv.jar:?]
        at org.broad.igv.ui.commandbar.GenomeListManager.getServerGenomeMap(GenomeListManager.java:350) [igv.jar:?]
        at org.broad.igv.ui.commandbar.GenomeListManager.getServerGenomeIDs(GenomeListManager.java:279) [igv.jar:?]
        at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:206) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.loadGenome(IgvTools.java:1191) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.doCount(IgvTools.java:848) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.run(IgvTools.java:371) [igv.jar:?]
        at org.broad.igv.tools.IgvTools.main(IgvTools.java:254) [igv.jar:?]
Done
```

The documentation says the count command can accept a file path instead of a genome name.
I have also tried using the FASTA file as well as the JSON file as input, not working.
Is there anything else I need to provide so that the command runs offline?
Thanks

**Comment by gitMakeCoffee** [comment]
Duplicate of #1088 
Outputs a wig file as expected
Error messages are likely not errors, but warnings

**Comment by jrobinso** [comment]
Thanks for the report.  I will look into supressing these messages.

**Comment by jrobinso** [comment]
Also, BTW,  you can use a "chrom.sizes" file instead of a ".genome" file.   The latter is an obsolete format.
