### ISSUE TITLE
Cert Fail

### ISSUE THREAD

**Issue by HoyMart** [igvteam/igv#1536]
Hello,
i am trying to use the IGV Browser but there is an error appearing.
sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: denyAfter constraint check failed: SHA1 used with Constraint date: 2019-01-01; params date: 2024-07-18T12:27:26.553Z used with certificate: CN=thawte Primary Root CA, OU="(c) 2006 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
	at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at com.sun.deploy.security.TrustDecider.getValidationState(Unknown Source)
	at com.sun.deploy.security.TrustDecider.validateChain(Unknown Source)
	at com.sun.deploy.security.TrustDecider.isAllPermissionGrantedInt(Unknown Source)
	at com.sun.deploy.security.TrustDecider.isAllPermissionGranted(Unknown Source)
	at com.sun.javaws.security.AppPolicy.grantUnrestrictedAccess(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.security.cert.CertPathValidatorException: denyAfter constraint check failed: SHA1 used with Constraint date: 2019-01-01; params date: 2024-07-18T12:27:26.553Z used with certificate: CN=thawte Primary Root CA, OU="(c) 2006 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	... 21 more
Caused by: java.security.cert.CertPathValidatorException: denyAfter constraint check failed: SHA1 used with Constraint date: 2019-01-01; params date: 2024-07-18T12:27:26.553Z used with certificate: CN=thawte Primary Root CA, OU="(c) 2006 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
	at sun.security.util.DisabledAlgorithmConstraints$DenyAfterConstraint.permits(Unknown Source)
	at sun.security.util.DisabledAlgorithmConstraints$Constraint.next(Unknown Source)
	at sun.security.util.DisabledAlgorithmConstraints$UsageConstraint.permits(Unknown Source)
	at sun.security.util.DisabledAlgorithmConstraints$Constraints.permits(Unknown Source)
	at sun.security.util.DisabledAlgorithmConstraints.permits(Unknown Source)
	at sun.security.util.DisabledAlgorithmConstraints.permits(Unknown Source)
	at sun.security.provider.certpath.AlgorithmChecker.check(Unknown Source)
	... 26 more

**Comment by jrobinso** [comment]
We need more information.    

* What version of IGV are you trying to run?
* Where did you obtain IGV?
* If you downloaded from our site, which package did you download (platform, and with java or without java)?
*  How are you starting IGV, from the command line or by double-clicking the icon?

**Comment by HoyMart** [comment]
Sure, here's the revised text:

Thank you for the quick response.

I am using version 2.17.4, which I found on https://igv.org/doc/desktop/#DownloadPage/. I downloaded the Windows installation with Java included, and I am trying to launch IGV by double-clicking it. My Windows version is 1809.

**Comment by jrobinso** [comment]
I'm puzzled by this,  I do not see this error on my Windows 10 machine and our certificates are valid.  Web searches on this error haven't uncovered anything particularly useful.   

Do you see the IGV window at all?

As an experiment you might try installing Java independently,  Java 17 or later, then using the "without Java" package.   You can obtain a free open-source Java build from here, among other places: https://adoptium.net/temurin/releases/?version=17
