### ISSUE TITLE
Access forbidden when trying to load T2T CHM13-v1.1 and T2T CHM13-v2.0/hs1

### ISSUE THREAD

**Issue by cheehongsg** [igvteam/igv#1556]
Unsure if this is the correct place to report..

When running IGV Desktop v2.18.2 and 2.16.2, there is no problem loading genome hg19 and hg38.
I will get error message "Access forbidden" when I try T2T CHM13-v1.1 or T2T CHM13-v2.0/hs1
Is this a setup issue on IGV's Amazon infrastructure? Have been such for >20 min.

Cheers, Chee

console log below:
```
INFO [Sep 03,2024 12:15] [Main] Startup  IGV Version 2.18.2 08/21/2024 12:06 PM
INFO [Sep 03,2024 12:15] [Main] Java 17.0.9 (build 17.0.9+9) 2023-10-17
INFO [Sep 03,2024 12:15] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Sep 03,2024 12:15] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9   
INFO [Sep 03,2024 12:15] [Main] OS: Mac OS X 14.6.1 x86_64
INFO [Sep 03,2024 12:15] [Main] IGV Directory: /Users/cheehong/igv
INFO [Sep 03,2024 12:15] [CommandListener] Listening on port 60151
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO [Sep 03,2024 12:15] [GenomeManager] Loading genome: https://igv-genepattern-org.s3.amazonaws.com/genomes/hg38/hg38.json
INFO [Sep 03,2024 12:15] [TrackLoader] Loading resource:  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz
INFO [Sep 03,2024 12:15] [GenomeManager] Loading genome: https://igv.org/genomes/json/hs1.json
SEVERE [Sep 03,2024 12:15] [MessageUtils] Error loading genome Human (T2T CHM13-v2.0/hs1)
SEVERE [Sep 03,2024 12:15] [MessageUtils] org.broad.igv.exceptions.HttpResponseException: Access forbidden <br> 
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:882)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:665)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:661)
	at org.igv/org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:368)
	at org.igv/org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:362)
	at org.igv/org.broad.igv.util.ParsingUtils.openInputStreamGZ(ParsingUtils.java:128)
	at org.igv/org.broad.igv.util.ParsingUtils.openInputStream(ParsingUtils.java:103)
	at org.igv/org.broad.igv.util.ParsingUtils.openBufferedReader(ParsingUtils.java:86)
	at org.igv/org.broad.igv.feature.genome.fasta.FastaIndex.parseIndexFile(FastaIndex.java:88)
	at org.igv/org.broad.igv.feature.genome.fasta.FastaIndex.<init>(FastaIndex.java:55)
	at org.igv/org.broad.igv.feature.genome.Genome.<init>(Genome.java:145)
	at org.igv/org.broad.igv.feature.genome.load.JsonGenomeLoader.loadGenome(JsonGenomeLoader.java:52)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:197)
	at org.igv/org.broad.igv.ui.commandbar.GenomeComboBox.lambda$loadGenomeFromServer$1(GenomeComboBox.java:237)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:73)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:43)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by helgathorv** [comment]
Thanks for letting us know. There are issues with our AWS buckets where some of the genomes are stored. We are working on resolving this.

**Comment by jrobinso** [comment]
@cheehongsg Could you try refreshing your genome? You can do this from the `Genomes > Select Hosted Genome...` menu.  That should resolve the problem with the T2T genome, still working through others.   Let us know if it does not.

The webapp should also be fixed for this genome.

**Comment by cheehongsg** [comment]
Thanks.
T2T-CHM13v2.0 works for Desktop and WebApp.
T2T CHM13-v1.1 still gives "Access forbidden".

**Comment by jrobinso** [comment]
Right, I was referring to v2.0.   There aren't quick solutions for all genome, v1.1 being one of those.

**Comment by cheehongsg** [comment]
No problem. I am working with v2.0.
Thanks for getting the resources back online.

**Comment by lbergelson** [comment]
@jrobinso I'm seeing `https://s3.amazonaws.com/igv.org.genomes/hg38/hg38_annotations.xml Access forbidden` When opening the "load from server" menu.  
<img width="876" alt="Screenshot 2024-09-03 at 6 56 45 PM" src="https://github.com/user-attachments/assets/d367e41d-dbf8-4a43-8c25-c67c368797c1">

**Comment by jrobinso** [comment]
@lbergelson There will be problems with "load from server" for sure,  or anything that references "igv.org.genomes".   I'm concentrating on the essential genome reference files for now.

**Comment by jrobinso** [comment]
@lbergelson load from server for hg38 is fixed.

**Comment by zhanglw05** [comment]
we are using igv web version. getting this error recently. Access forbidden: https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz.tbi: https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz. Will this be resolved soon or we should think other solutions, like hosting ourselves.

**Comment by mwalker174** [comment]
Hi, I'm also seeing a problem with Google oAuth:

```
echo Using bundled JDK.
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
WARNING: Unknown module: jide.common specified to --add-exports
WARNING: Unknown module: jide.common specified to --add-exports
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)
INFO [Sep 04,2024 11:10] [Main] Startup  IGV Version 2.18.2 08/21/2024 12:06 PM
INFO [Sep 04,2024 11:10] [Main] Java 17.0.9 (build 17.0.9+9) 2023-10-17
INFO [Sep 04,2024 11:10] [Main] Java Vendor: Eclipse Adoptium https://adoptium.net/
INFO [Sep 04,2024 11:10] [Main] JVM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9
INFO [Sep 04,2024 11:10] [Main] OS: Mac OS X 14.5 x86_64
INFO [Sep 04,2024 11:10] [Main] IGV Directory: /Users/markw/igv
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO [Sep 04,2024 11:10] [CommandListener] Listening on port 60151
INFO [Sep 04,2024 11:10] [GenomeManager] Loading genome: /Users/markw/igv/genomes/hg38_1kg.json
WARNING [Sep 04,2024 11:10] [LoadFromServerAction] No data found for current genome.
INFO [Sep 04,2024 11:10] [TrackLoader] Loading resource:  https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz
INFO [Sep 04,2024 11:10] [OAuthUtils] Loading Google oAuth properties
SEVERE [Sep 04,2024 11:10] [OAuthUtils] Error loading Google oAuth properties
SEVERE [Sep 04,2024 11:10] [OAuthUtils] java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/igv.org.app/desktop_google
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.igv/org.broad.igv.oauth.OAuthUtils.openInputStream(OAuthUtils.java:265)
	at org.igv/org.broad.igv.oauth.OAuthUtils.loadAsString(OAuthUtils.java:171)
	at org.igv/org.broad.igv.oauth.OAuthUtils.loadDefaultOauthProperties(OAuthUtils.java:145)
	at org.igv/org.broad.igv.oauth.OAuthUtils.getGoogleProvider(OAuthUtils.java:126)
	at org.igv/org.broad.igv.ui.IGVMenuBar$27.menuSelected(IGVMenuBar.java:1080)
	at java.desktop/javax.swing.JMenu.fireMenuSelected(Unknown Source)
	at java.desktop/javax.swing.JMenu$MenuChangeListener.stateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setSelected(Unknown Source)
	at java.desktop/javax.swing.JMenu.setSelected(Unknown Source)
	at java.desktop/com.apple.laf.ScreenMenu$2.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

SEVERE [Sep 04,2024 11:10] [MessageUtils] Error loading Google oAuth properties
SEVERE [Sep 04,2024 11:10] [MessageUtils] java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/igv.org.app/desktop_google
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.igv/org.broad.igv.oauth.OAuthUtils.openInputStream(OAuthUtils.java:265)
	at org.igv/org.broad.igv.oauth.OAuthUtils.loadAsString(OAuthUtils.java:171)
	at org.igv/org.broad.igv.oauth.OAuthUtils.loadDefaultOauthProperties(OAuthUtils.java:145)
	at org.igv/org.broad.igv.oauth.OAuthUtils.getGoogleProvider(OAuthUtils.java:126)
	at org.igv/org.broad.igv.ui.IGVMenuBar$27.menuSelected(IGVMenuBar.java:1080)
	at java.desktop/javax.swing.JMenu.fireMenuSelected(Unknown Source)
	at java.desktop/javax.swing.JMenu$MenuChangeListener.stateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setSelected(Unknown Source)
	at java.desktop/javax.swing.JMenu.setSelected(Unknown Source)
	at java.desktop/com.apple.laf.ScreenMenu$2.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

SEVERE [Sep 04,2024 11:10] [MessageUtils] Error loading Google oAuth properties
```

**Comment by helgathorv** [comment]
There are issues with some of our AWS buckets and we are working on resolving them. In the meantime, try the following workaround: 
From the menu select View > Preferences > Advanced and enter the following for the "OAuth provisioning URL":
https://igv.org/services/desktop_google

Let us know if that doesn't work for you.

**Comment by helgathorv** [comment]
@zhanglw05 The hg38 genome works for me now at igv.org/app. Try clearing the browser cache and selecting a different genome and then back to hg38. Note that not all the genomes currently work.

**Comment by zhanglw05** [comment]
@helgathorv , thank you. it is working for us now.
