### ISSUE TITLE
Error loading bigwigs by http

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#158]
Loading bigwigs by http sometimes fails with the errors below. Reported against 2.3.57

java.lang.RuntimeException: Error reading zoom level data records (Table O)
    at org.broad.igv.bbfile.BBZoomLevelFormat.<init>(BBZoomLevelFormat.java:118)
    at org.broad.igv.bbfile.BBZoomLevels.<init>(BBZoomLevels.java:111)
    at org.broad.igv.bbfile.BBFileReader.<init>(BBFileReader.java:141)
    at org.broad.igv.track.TrackLoader.loadBWFile(TrackLoader.java:710)
    at org.broad.igv.track.TrackLoader.load(TrackLoader.java:186)
    at org.broad.igv.track.TrackLoader.load(TrackLoader.java:99)
    at org.broad.igv.ui.IGV.load(IGV.java:1746)
    at org.broad.igv.ui.IGV$11.run(IGV.java:1660)
    at org.broad.igv.ui.IGV.loadResources(IGV.java:1673)
    at org.broad.igv.ui.IGV$5.run(IGV.java:723)
    at org.broad.igv.util.LongRunningTask.submit(LongRunningTask.java:42)
    at org.broad.igv.ui.IGV.loadTracks(IGV.java:735)
    at org.broad.igv.batch.CommandExecutor.loadFiles(CommandExecutor.java:547)
    at org.broad.igv.batch.CommandListener.processGet(CommandListener.java:346)
    at org.broad.igv.batch.CommandListener.processClientSession(CommandListener.java:186)
    at org.broad.igv.batch.CommandListener.run(CommandListener.java:96)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.MeteredStream.read(MeteredStream.java:134)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3335)
    at org.broad.igv.util.stream.IGVSeekableHTTPStream.read(IGVSeekableHTTPStream.java:95)
    at org.broad.igv.util.stream.IGVSeekableBufferedStream.read(IGVSeekableBufferedStream.java:166)
    at org.broad.igv.util.stream.IGVSeekableBufferedStream.fillBuffer(IGVSeekableBufferedStream.java:243)
    at org.broad.igv.util.stream.IGVSeekableBufferedStream.read(IGVSeekableBufferedStream.java:172)
    at htsjdk.samtools.seekablestream.SeekableStream.readFully(SeekableStream.java:61)
    at org.broad.igv.bbfile.BBZoomLevelFormat.<init>(BBZoomLevelFormat.java:104)
    ... 16 more
E

**Comment by jrobinso** [comment]
The underlying cause is "java.net.SocketException: Connection reset"

Here's an explanation of the error from https://www.ibm.com/developerworks/community/blogs/738b7897-cd38-4f24-9f05-48dd69116837/entry/understanding_some_common_socketexceptions_in_java3?lang=en


This exception appears when the remote connection is unexpectedly and forcefully closed due to various reasons like application crash, system reboot, hard close of remote host. Kernel from the remote system sends out a packets with RST bit to the local system. The local socket on performing any SEND (could be a Keep-alive packet) or RECEIVE operations subsequently fail with this error. Certain combinations of linger settings can also result in packets with RST bit set.

**Comment by jrobinso** [comment]
And a comment on the above post

https://www.ibm.com/developerworks/community/blogs/738b7897-cd38-4f24-9f05-48dd69116837/entry/understanding_some_common_socketexceptions_in_java3?lang=en#threadid=b4860008-8161-4195-8ac3-386c23f18e18
