### ISSUE TITLE
can't load the Genome of the susScr11 online and in the windows terminate

### ISSUE THREAD

**Issue by shiyu-ay** [igvteam/igv#1614]
Unexpected error: Cannot invok
"org.broad.igv.feature.Cromosome.getLength(）" because "Chr" is null
See igv.log for more details

igv.log
[LongRunningTask] Exception running task
SEVERE [11月 13,2024 12:16] [LongRunningTask] java.lang.NullPointerException: Cannot invoke "org.broad.igv.feature.Chromosome.getLength()" because "chr" is null
	at org.igv/org.broad.igv.feature.genome.Genome.getWGLength(Genome.java:619)
	at org.igv/org.broad.igv.ui.panel.ReferenceFrame.getChromosomeLength(ReferenceFrame.java:749)
	at org.igv/org.broad.igv.ui.panel.ReferenceFrame.getChromosomeLength(ReferenceFrame.java:621)
	at org.igv/org.broad.igv.ui.panel.ReferenceFrame.computeLocationScale(ReferenceFrame.java:694)
	at org.igv/org.broad.igv.ui.panel.ReferenceFrame.setZoom(ReferenceFrame.java:232)
	at org.igv/org.broad.igv.ui.panel.ReferenceFrame.setChromosomeName(ReferenceFrame.java:357)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.setCurrentGenome(GenomeManager.java:145)
	at org.igv/org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:223)
	at org.igv/org.broad.igv.ui.commandbar.GenomeComboBox.lambda$loadGenomeFromServer$1(GenomeComboBox.java:233)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:73)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:43)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr1' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr2' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr3' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr4' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr5' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr6' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr7' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr8' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr9' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr10' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr11' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr12' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr13' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr14' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr15' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr16' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr17' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chr18' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chrX' not found
INFO [11月 13,2024 12:16] [RulerPanel] Chromosome 'chrY' not found

**Comment by shiyu-ay** [comment]
I think that this condition maybe the problem of the version 2.17,2.18.When I use the version 2.12 ,it didn't happen.But I don't know how to solve this problem.

**Comment by jrobinso** [comment]
Thanks for the report.  Could you try again?  I made a change to the genome config (json) file that fixed the problem for me.

**Comment by shiyu-ay** [comment]
> Thanks for the report. Could you try again? I made a change to the genome config (json) file that fixed the problem for me.

Thank you very much ! I try it again and this problem has been solved successfully. Have a nice day!
