### ISSUE TITLE
Error encountered querying alignments: java.lang.RuntimeException: java.net.SocketTimeoutException: Connect timed out

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#1625]
While testing the snapshot 2024/11/26 with our cancer curators, I'm encountering the following backtrace (the accompanying tracks drop and the curator has to reload all of them again):

![image](https://github.com/user-attachments/assets/b385d3b7-c1b3-4b9b-8dc2-f3cf2e07ac80)

For the record, this also happened with IGV release 2.18.4. This is a relatively new error that curators have only noticed recently, just now I managed to get a backtrace since it takes a while for it to manifest. Both of the reports were running OSX (intel) machines.

```
INFO [Nov 28,2024 10:35] [TrackLoader] Loading resource: https://<PRESIGNED_URL_TO_BAM>
2024-11-28 10:36:00.492 java[2512:82963] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-28 10:36:00.492 java[2512:82963] +[IMKInputSession subclass]: chose IMKInputSession_Modern
SEVERE [Nov 28,2024 10:36] [AlignmentTileLoader] Error loading alignment data
SEVERE [Nov 28,2024 10:36] [AlignmentTileLoader] java.lang.RuntimeException: java.net.SocketTimeoutException: Connect timed out
	at org.igv/org.broad.igv.ucsc.twobit.TwoBitSequence.readSequence(TwoBitSequence.java:189)
	at org.igv/org.broad.igv.ucsc.twobit.TwoBitSequence.getSequence(TwoBitSequence.java:79)
	at org.igv/org.broad.igv.feature.genome.SequenceWrapper.loadTiles(SequenceWrapper.java:223)
	at org.igv/org.broad.igv.feature.genome.SequenceWrapper.getSequenceTiles(SequenceWrapper.java:213)
	at org.igv/org.broad.igv.feature.genome.SequenceWrapper.getSequence(SequenceWrapper.java:117)
	at org.igv/org.broad.igv.feature.genome.Genome.getSequence(Genome.java:581)
	at org.igv/org.broad.igv.feature.genome.Genome.getSequence(Genome.java:563)
	at org.igv/org.broad.igv.sam.BisulfiteCounts.incrementCounts(BisulfiteCounts.java:75)
	at org.igv/org.broad.igv.sam.BaseAlignmentCounts.incCounts(BaseAlignmentCounts.java:129)
	at org.igv/org.broad.igv.sam.AlignmentTileLoader$AlignmentTile.addRecord(AlignmentTileLoader.java:497)
	at org.igv/org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:248)
	at org.igv/org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:349)
	at org.igv/org.broad.igv.sam.AlignmentDataManager.load(AlignmentDataManager.java:283)
	at org.igv/org.broad.igv.sam.CoverageTrack.load(CoverageTrack.java:185)
	at org.igv/org.broad.igv.ui.IGV.lambda$repaint$17(IGV.java:2323)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:760)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.[www.http.HttpClient.openServer](http://www.http.httpclient.openserver/)(HttpClient.java:531)
	at java.base/sun.net.[www.http.HttpClient.openServer](http://www.http.httpclient.openserver/)(HttpClient.java:636)
	at java.base/sun.net.[www.protocol.https.HttpsClient](http://www.protocol.https.httpsclient/).<init>(HttpsClient.java:264)
	at java.base/sun.net.[www.protocol.https.HttpsClient.New](http://www.protocol.https.httpsclient.new/)(HttpsClient.java:377)
	at java.base/sun.net.[www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient](http://www.protocol.https.abstractdelegatehttpsurlconnection.getnewhttpclient/)(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.[www.protocol.http.HttpURLConnection.plainConnect0](http://www.protocol.http.httpurlconnection.plainconnect0/)(HttpURLConnection.java:1243)
	at java.base/sun.net.[www.protocol.http.HttpURLConnection.plainConnect](http://www.protocol.http.httpurlconnection.plainconnect/)(HttpURLConnection.java:1129)
	at java.base/sun.net.[www.protocol.https.AbstractDelegateHttpsURLConnection.connect](http://www.protocol.https.abstractdelegatehttpsurlconnection.connect/)(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.[www.protocol.http.HttpURLConnection.getInputStream0](http://www.protocol.http.httpurlconnection.getinputstream0/)(HttpURLConnection.java:1691)
	at java.base/sun.net.[www.protocol.http.HttpURLConnection.getInputStream](http://www.protocol.http.httpurlconnection.getinputstream/)(HttpURLConnection.java:1615)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at java.base/sun.net.[www.protocol.https.HttpsURLConnectionImpl.getResponseCode](http://www.protocol.https.httpsurlconnectionimpl.getresponsecode/)(HttpsURLConnectionImpl.java:307)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:790)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:665)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:661)
	at org.igv/org.broad.igv.util.stream.IGVSeekableHTTPStream.openInputStreamForRange(IGVSeekableHTTPStream.java:211)
	at org.igv/org.broad.igv.util.stream.IGVSeekableHTTPStream._read(IGVSeekableHTTPStream.java:125)
	at org.igv/org.broad.igv.util.stream.IGVSeekableHTTPStream.read(IGVSeekableHTTPStream.java:85)
	at htsjdk@4.1.2-module/htsjdk.samtools.seekablestream.SeekableStream.readFully(SeekableStream.java:84)
	at org.igv/org.broad.igv.ucsc.twobit.UnsignedByteBufferImpl.loadBinaryBuffer(UnsignedByteBufferImpl.java:21)
	at org.igv/org.broad.igv.ucsc.twobit.TwoBitSequence.loadBinaryBuffer(TwoBitSequence.java:50)
	at org.igv/org.broad.igv.ucsc.twobit.TwoBitSequence.getSequenceRecord(TwoBitSequence.java:208)
	at org.igv/org.broad.igv.ucsc.twobit.TwoBitSequence.readSequence(TwoBitSequence.java:132)
	... 18 more
```

**Comment by brainstorm** [comment]
The fact that most of the backtrace points to `TwoBitSequence.readSequence` instead of BAM-reading makes me think if it's a stale config file similar to what I reported in https://github.com/igvteam/igv/issues/1424?

**Comment by jrobinso** [comment]
The error is a timeout on the Socket Connection to the server (UCSC in this case).  We haven't seen this here but you are a bit further away.     We are eliminating dependence on our own S3 stored files, and eventually they will go away altogether.  We cannot fund the egress indefinitely.    For genomes that has meant a change from our S3 hosted fastas to UCSC hosted twobit files.      So I suspect the problems are connected with the change of servers for the sequence files,  from S3 to UCSC, and not fasta vs twobit.   

With the 2.19 release, and also the snapshot, there is the option to download the sequence files locally.     This is now (or will be post release) our recommended configuration for everyone.    A 1 GB file is not so big as it was 10 years ago.    I recommend your curators try this.     From the "Genomes > Select Hosted Genome" option search for your genome of interest, then select the "Download Sequence" and "Download Annotations" options.     On completion all files will be cached locally.   This will eliminate dependency on the network, and performance should also be significantly improved.

<img width="363" alt="Screenshot 2024-11-27 at 4 41 08 PM" src="https://github.com/user-attachments/assets/28310b6a-7515-4f54-8694-9d061ea732dc">

Alternatively,  you could setup your own genome file server for everyone, and change the IGV configuration to point to your hosted files.    For a few genomes this would not be difficult,  I can guide you through this if you are interested.

**Comment by brainstorm** [comment]
Thanks Jim, that explains and helps us a lot!
