### ISSUE TITLE
"Error Accessing Resource" for readgroupsets to reference set mismatch

### ISSUE THREAD

**Issue by mbookman** [igvteam/igv#181]
When opening a Read Group Set in IGV desktop where the RGS has no associated Reference Set ID, if the reference currently selected in the UI does not match, then drilling down to view reads will ultimately generate "Error Accessing Resource".

The console shows:

    ERROR [2015-10-06 08:56:22,415]  [MessageUtils.java:74] [pool-1-thread-9]  Error accessing resource
    ERROR [2015-10-06 08:56:24,272]  [Ga4ghAPIHelper.java:307] [pool-1-thread-9]  Error accessing resource
    java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.googleapis.com/genomics/v1beta2/reads/search?key=[REDACTED]&
            at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
            at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
            at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
            at org.broad.igv.ga4gh.Ga4ghAPIHelper.doPost(Ga4ghAPIHelper.java:280)
            at org.broad.igv.ga4gh.Ga4ghAPIHelper.searchReads(Ga4ghAPIHelper.java:202)
            at org.broad.igv.ga4gh.Ga4ghAlignmentReader.query(Ga4ghAlignmentReader.java:96)
            at org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:138)
            at org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:342)
            at org.broad.igv.sam.AlignmentDataManager$1.run(AlignmentDataManager.java:307)
            at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

The underlying cause in my test case was that the reads/search call had the wrong reference_name, "chr22", instead of "22".

When I change the reference in the UI from "Human hg18" to "Human (b37)", then I was able to browse the reads just fine.

Below is an example exchange that shows the error information returned from the reads/search call:

Request

    POST https://www.googleapis.com/genomics/v1beta2/reads/search?key={YOUR_API_KEY}
    {
     "readGroupSetIds": [
      "<REDACTED>"
     ],
     "referenceName": "chr22",
     "start": "24812441",
     "end": "24878991",
     "pageSize": 3
    }
 
Response
 
    400 OK
    {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "invalidArgument",
        "message": "The given read group sets are not aligned to any reference with
                    referenceName \"chr22\". Did you mean \"22\"? Wanted one of [\"1\" \"2\"
    <etc>

None of that detail was visible to me, so to figure this out I needed to build IGV and add some debugging.

hg18 is probably a reasonable guess when Reference Set ID is missing, but perhaps right thing to do in that case is to prompt the user to select a reference.

**Comment by jrobinso** [comment]
Sorry for the delayed response,  I'll look into this.

**Comment by jrobinso** [comment]
There's something curious about this readgroupset if the reference set ID is missing.   The server seems to know the sequence names in the readgroup set,  it gives a message enumerating them.   Where does it get this information?

**Comment by mbookman** [comment]
We've only recently backfilled our public data (like 1000genomes and Platinum Genomes) to all have reference set ids. The dataset I had problems with also did not have them, though we will be updating it as well.

The error message appears to know a lot about the reference, but it doesn't. The reads/search API cleverly suggests if someone put in "22" and it was not found "did you mean chr22" and vice-versa.

**Comment by jrobinso** [comment]
I see, its the "Wanted one of..."  that made me think it knew.  Generally we always do these translations for people in IGV if we know the sequence names in the source we are querying.   That's why this works transparently when reference set ID is set.   

I'm considering putting some code in to try the opposite convention if it fails with a "400",  then present an error message.  Asking the user to specify the reference will just confuse them,  I suspect,  they are not going to know which refrence uses which convention.

**Comment by jrobinso** [comment]
The "fix" for this is to display the error message properly,  to give the user an idea of what's going on.  I considered but decided not to try to guess the chr names if referenceSet id is not set.
