### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by yfarjoun** [igvteam/igv#183]
in the knowledge-base plugin (for the GATK NA12878 knowledgeBase) one cannot add a review to a multiallelic site (the dialogue box doesn't accept). It would be good if in this case the plugin would  subcontext the variant to genotype that was clicked when attempting to submit the review.

I am aware that this feature is only aimed ad the GATK team at broad, and so we will implement it. I just wanted to document the feature here.

**Comment by jrobinso** [comment]
OK Yossi, let me know if you need anything from me.

**Comment by ldgauthier** [comment]
I'm seeing some test failures when I run on the master branch (namely RunPluginTest, CoverageTrackTest, TrackLoaderTestHeaded, and PreferencesEditorTest).  My Java version is 1.7.0_51.  Is that a problem?

**Comment by jrobinso** [comment]
The java version is fine.  Could you post the test results?

**Comment by ldgauthier** [comment]
Here are some excerpts from the results:
  ```
    <testcase classname="org.broad.igv.sam.CoverageTrackTest" name="testAfterBAMRemoved" time="0.402">
          <failure message="expected:&lt;4&gt; but was:&lt;5&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;4&gt; but was:&lt;5&gt;
        at org.broad.igv.sam.CoverageTrackTest.testAfterBAMRemoved(CoverageTrackTest.java:79)

     <testcase classname="org.broad.igv.session.IGVSessionReaderTestHeaded" name="testLoadCombinedDataSourceSession" time="1.359">
          <error message="java.lang.IllegalStateException: Could not find track with ID test/data/seg/Broad.080528.subtypes.seg.gz_TRIBE_p_TCGAaffx_B1_2_GBM_Nsp_GenomeWideSNP_6_E11_155884" type="java.lang.RuntimeException">java.lang.RuntimeException: java.lang.IllegalStateException: Could not find track with ID test/data/seg/Broad.080528.subtypes.seg.gz_TRIBE_p_TCGAaffx_B1_2_GBM_Nsp_GenomeWideSNP_6_E11_155884
        at org.broad.igv.ui.IGV.restoreSessionSynchronous(IGV.java:1463)
        at org.broad.igv.ui.IGV$8.run(IGV.java:1397)
        at org.broad.igv.util.LongRunningTask.submit(LongRunningTask.java:57)
        at org.broad.igv.ui.IGV.doRestoreSession(IGV.java:1400)
        at org.broad.igv.ui.AbstractHeadedTest.rewriteRestoreSession(AbstractHeadedTest.java:177)
        at org.broad.igv.session.IGVSessionReaderTestHeaded.testLoadCombinedDataSourceSession(IGVSessionReaderTestHeaded.java:187)
Caused by: java.lang.IllegalStateException: Could not find track with ID test/data/seg/Broad.080528.subtypes.seg.gz_TRIBE_p_TCGAaffx_B1_2_GBM_Nsp_GenomeWideSNP_6_E11_155884
        at org.broad.igv.data.CombinedDataSource.updateTrackReference(CombinedDataSource.java:100)
        at org.broad.igv.data.CombinedDataSource.updateTrackReferences(CombinedDataSource.java:92)
        at org.broad.igv.track.DataSourceTrack.updateTrackReferences(DataSourceTrack.java:185)
        at org.broad.igv.session.IGVSessionReader.processPanel(IGVSessionReader.java:1020)
        at org.broad.igv.session.IGVSessionReader.process(IGVSessionReader.java:550)
        at org.broad.igv.session.IGVSessionReader.process(IGVSessionReader.java:1254)
        at org.broad.igv.session.IGVSessionReader.processRootNode(IGVSessionReader.java:471)
        at org.broad.igv.session.IGVSessionReader.loadSession(IGVSessionReader.java:324)
        at org.broad.igv.ui.IGV.restoreSessionSynchronous(IGV.java:1428)
</error>

      <testcase classname="org.broad.igv.track.TrackLoaderTestHeaded" name="testLoadBAMFtpHeaded" time="1.38">
          <failure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
        at org.broad.igv.track.TrackLoaderTest.tstLoadFi(TrackLoaderTest.java:218)
        at org.broad.igv.track.TrackLoaderTestHeaded.testLoadBAMFtpHeaded(TrackLoaderTestHeaded.java:86)

      <testcase classname="org.broad.igv.ui.PreferencesEditorTest" name="testChangeAlignmentReload" time="0.335">
          <error message="org.broad.igv.sam.SpliceJunctionTrack cannot be cast to org.broad.igv.sam.AlignmentTrack" type="java.lang.ClassCastException">java.lang.ClassCastException: org.broad.igv.sam.SpliceJunctionTrack cannot be cast to org.broad.igv.sam.AlignmentTrack
        at org.broad.igv.ui.PreferencesEditorTest.testChangeAlignmentReload(PreferencesEditorTest.java:64)

<testcase classname="org.broad.igv.cli_plugin.ui.RunPluginTest" name="testCatPlugin" time="0.363">
          <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
        at org.broad.igv.cli_plugin.ui.RunPluginTest.testCatPlugin(RunPluginTest.java:65)
</failure>
```

Please let me know if you need more details.

**Comment by ldgauthier** [comment]
You probably wanted the HTML.  Sorry.  Here it is:

![image](https://cloud.githubusercontent.com/assets/6578548/12332458/922c5876-babc-11e5-9d20-4f709a15cb24.png)
![image](https://cloud.githubusercontent.com/assets/6578548/12332475/9fc75666-babc-11e5-9713-077af6bcfc7a.png)

**Comment by jrobinso** [comment]
OK, I’ll look into this.  We have a CI server and they are passing there, but I haven’t tried from a local install in a while.

**Comment by ldgauthier** [comment]
Thanks!

**Comment by jrobinso** [comment]
OK,  I see the problem.   These tests were not being run by the CI server because they require opening a UI.  I examined them and they didn’t test anything useful, so they have been removed.

**Comment by ldgauthier** [comment]
RunPluginTest is still causing problems and I have a new failure in TrackLoaderTestHeaded
![image](https://cloud.githubusercontent.com/assets/6578548/12334031/b3d3b72c-bac5-11e5-9f24-e6f7f380c5fa.png)
Is it possible those are also being skipped by your CI server?

**Comment by jrobinso** [comment]
Yes,  all “headed” tests are skipped (tests that require a UI).   I will look further into this, apologies.

**Comment by jrobinso** [comment]
Hi,

These 2 are fixed.
