### ISSUE TITLE
Error in displaying application

### ISSUE THREAD

**Issue by 18209018** [igvteam/igv#221]
Hello, I use IGV 2.3.72 in Linux Ubuntu KDE Plasma. I got an error in displaying the application (basically, the GUI is messed up, the menu is not shown, the click action is not working,etc.) like below:

`INFO [2016-04-07 11:13:17,690]  [DirectoryManager.java:163] [main]  IGV Directory: /home/bharata/igv
INFO [2016-04-07 11:13:17,690] [DirectoryManager.java:163]  IGV Directory: /home/bharata/igv
INFO [2016-04-07 11:13:17,694]  [Main.java:99] [main]  Startup  IGV Version 2.3.72 (105)04/01/2016 11:33 AM
INFO [2016-04-07 11:13:17,694]  [Main.java:100] [main]  Java 1.8.0_45
INFO [2016-04-07 11:13:17,694]  [DirectoryManager.java:72] [main]  Fetching user directory... 
INFO [2016-04-07 11:13:17,804]  [Main.java:101] [main]  Default User Directory: /home/bharata
INFO [2016-04-07 11:13:17,804]  [Main.java:102] [main]  OS: Linux
INFO [2016-04-07 11:13:30,088]  [GenomeManager.java:145] [main]  Loading genome: /home/local/EnsembleHG38-80/Ch38.cdna.all.fa.fai
INFO [2016-04-07 11:13:30,635]  [GenomeManager.java:192] [main]  Genome loaded.  id= /home/local/EnsembleHG38-80/Ch38.cdna.all.fa
INFO [2016-04-07 11:13:31,345]  [CommandListener.java:106] [Thread-6]  Listening on port 60151
ERROR [2016-04-07 11:13:31,699]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NegativeArraySizeException
        at org.broad.igv.ui.panel.ZoomSliderPanel.updateTickCount(ZoomSliderPanel.java:103)
        at org.broad.igv.ui.panel.ZoomSliderPanel.paintComponent(ZoomSliderPanel.java:112)
        at javax.swing.JComponent.paint(JComponent.java:1056)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5226)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1572)
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1495)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
        at javax.swing.JComponent.paint(JComponent.java:1042)
        at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
        at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
        at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)                                                                                                 
        at java.awt.Container.paint(Container.java:1973)                                                                                                                           
        at java.awt.Window.paint(Window.java:3912)                                                                                                                                 
        at javax.swing.RepaintManager$4.run(RepaintManager.java:835)                                                                                                               
        at javax.swing.RepaintManager$4.run(RepaintManager.java:807)                                                                                                               
        at java.security.AccessController.doPrivileged(Native Method)                                                                                                              
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)                                                                                      
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)                                                                                                   
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)                                                                                                   
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)                                                                                                
        at javax.swing.RepaintManager.access$1300(RepaintManager.java:64)                                                                                                          
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)                                                                                             
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR [2016-04-07 11:13:31,713]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException
        at org.broad.igv.ui.panel.ZoomSliderPanel.paintHorizontal(ZoomSliderPanel.java:182)
        at org.broad.igv.ui.panel.ZoomSliderPanel.paintComponent(ZoomSliderPanel.java:114)
        at javax.swing.JComponent.paint(JComponent.java:1056)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5226)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1572)
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1495)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
        at javax.swing.JComponent.paint(JComponent.java:1042)
        at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
        at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
        at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
        at java.awt.Container.paint(Container.java:1973)
        at java.awt.Window.paint(Window.java:3912)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:835)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:807)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)
        at javax.swing.RepaintManager.access$1300(RepaintManager.java:64)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

I attached the screenshot of the application display.
![igv error](https://cloud.githubusercontent.com/assets/1442522/14338552/c1c6e33e-fcb2-11e5-8fe7-32779961b6ae.png)

My Java environtment is version 1.8.0_45 and support 64-bit.

**Comment by jrobinso** [comment]
Hi,

It looks like you perhaps tried to use a fasta index file (the .fai 
file) in place of the fasta file.   Try deleting your "prefs.properties" 
file and starting over,  do not use an index file as the reference, you 
must use the fasta file.

Jim

**Comment by 18209018** [comment]
Thank you. Removing prefs.properties really help although I'm not really sure I load .fai or not because I think I load fasta file. Anyway, thank you. At least I know how to fix this kind of problem.

**Comment by jrobinso** [comment]
The log indicated an attempt to load the .fai file directly.  I'm going to reopen this ticket as a reminder to add a check for that,  we should be able to detect it and give an error.
