### ISSUE TITLE
IGV Java Web Start failed to start with Java 8 on windows

### ISSUE THREAD

**Issue by zhiliangc** [igvteam/igv#310]
Shown as 'Unable to launch the application' on Windows 7 with Java 8
Tested on mac and IGV started without any issue

Launch File
`<?xml version="1.0" encoding="utf-8"?>
<jnlp
  spec="6.0+"
  codebase="http://data.broadinstitute.org/igv/projects/current"
  href="http://data.broadinstitute.org/igv/projects/current/igv.jnlp">
  <information>
    <title>IGV 2.3</title>
    <vendor>The Broad Institute</vendor>
    <homepage href="http://www.broadinstitute.org/igv"/>
    <description>IGV Software</description>
    <description kind="short">IGV</description>
    <icon href="IGV_64.gif"/>
    <icon kind="splash" href="IGV_64.gif"/>
    <offline-allowed/>
	<shortcut online="true">
	  <desktop/>
	  <menu submenu="IGV"/>
	</shortcut>
  </information>
  <security>
      <all-permissions/>
  </security>
  <update check="always"/>
  <resources>
    <java version="1.6+"
          initial-heap-size="256m" 
          max-heap-size="750m" />
    <jar href="igv.jar" download="eager" main="true"/>
    <jar href="batik-codec__V1.7.jar" download="eager"/>
    <jar href="goby-io-igv__V1.0.jar" download="eager"/>   
    <property name="java.net.preferIPv4Stack" value="true"/>     
    <property name="apple.laf.useScreenMenuBar" value="true"/>
    <property name="com.apple.mrj.application.growbox.intrudes" value="false"/>
    <property name="com.apple.mrj.application.live-resize" value="true"/>
    <property name="com.apple.macos.smallTabs" value="true"/>    
    <property name="http.agent" value="IGV"/>
    <property name="development" value="false"/>
  </resources>
  <application-desc main-class="org.broad.igv.ui.Main"/>
</jnlp>`

Exception
`com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://data.broadinstitute.org/igv/projects/current/batik-codec__V1.7.jar
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.LaunchDownload$DownloadTask.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

Wrapped Exception
`java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.MeteredStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.PushbackInputStream.read(Unknown Source)
	at java.util.zip.InflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.util.zip.ZipInputStream.read(Unknown Source)
	at com.sun.deploy.net.HttpDownloadHelper.decompressWrite(Unknown Source)
	at com.sun.deploy.net.HttpDownloadHelper.download(Unknown Source)
	at com.sun.deploy.cache.Cache.downloadResourceToTempFile(Unknown Source)
	at com.sun.deploy.cache.Cache.downloadResourceToCache(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.LaunchDownload$DownloadTask.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by jrobinso** [comment]
Please clear your browser cache and try again.  If it still doesn't work you might need to use the packaged application, Java Web Start does not work for all users.

**Comment by zhiliangc** [comment]
thanks

**Comment by jrobinso** [comment]
Does it work now?

**Comment by zhiliangc** [comment]
yep, only trouble is I need to clear the cache again after a couple launches, but at least it's launching now.

**Comment by jrobinso** [comment]
You might have a better experience with the packaged window app.  The only downside is you have to manually update it occasionally, it does not automatically update to new releases.

**Comment by zhiliangc** [comment]
Thanks.

Yes, I do have a windows app. I was launching from Illumina BaseSpace and that gave me error. I was told it's more about the IGV java web start itself rather than BaseSpace, so I tried the one from Broad's website. They had exactly the same issue for me.
After clearing the cache, both worked, so I have everything working in place now.
