### ISSUE TITLE
exception thrown on "export alignments"

### ISSUE THREAD

**Issue by rvalieris** [igvteam/igv#358]
right click alignment track -> "export alignments" feature throws this exception:

```
ERROR [2017-01-10 14:41:00,333]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for visibleData.sam.
Sort order is coordinate. Offending records are at [chr17:7576444] and [chr17:7576437]
	at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:192)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:179)
	at org.broad.igv.sam.SAMWriter.writeAlignments(SAMWriter.java:86)
	at org.broad.igv.sam.SAMWriter.writeToFile(SAMWriter.java:65)
	at org.broad.igv.sam.SAMWriter.writeAlignmentFilePicard(SAMWriter.java:261)
	at org.broad.igv.track.TrackMenuUtils.exportVisibleAlignments(TrackMenuUtils.java:636)
	at org.broad.igv.track.TrackMenuUtils$13.actionPerformed(TrackMenuUtils.java:604)
[....]
```

**Comment by jrobinso** [comment]
Hi, is "show soft clips" turned on?

**Comment by rvalieris** [comment]
yes it is, I didn't expected it would make a difference for export though.

turning it off works !

**Comment by jrobinso** [comment]
OK, that's a bug, but I know what's going on.  Apparently the htsjdk wants
to see the alignments in coordinate sorted order.  The start is the aligned
start,  but IGV reorders alignments when soft-clipping is on so you can see
the clips.

I will fix it,  in the meantime you'll have to turn that off to do exports.

**Comment by rvalieris** [comment]
I see, thanks !
