### ISSUE TITLE
Hang when using remote interface

### ISSUE THREAD

**Issue by Lenbok** [igvteam/igv#360]
I got the following hang when using the remote control interface to instruct IGV to go to a coordinate. It looks like the command execution thread ends up issuing swing commands, even though these must be executed by the AWT event queue, and that is probably what is causing the deadlock:

"Thread-7" #26 prio=5 os_prio=0 tid=0x00007fa02c0a7000 nid=0x52c3 in Object.wait() [0x00007fa034bc1000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at javax.swing.text.AbstractDocument.readLock(AbstractDocument.java:1387)
        - locked <0x00000000832261d8> (a javax.swing.text.PlainDocument)
        at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:878)
        at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
        at javax.swing.JComponent.paintComponent(JComponent.java:780)
        at javax.swing.JComponent.paint(JComponent.java:1056)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at javax.swing.JComponent.paintChildren(JComponent.java:889)
        - locked <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(JComponent.java:1065)
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
        at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
        at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
        at javax.swing.JComponent.paintImmediately(JComponent.java:4981)
        at org.broad.igv.ui.IGV.revalidateTrackPanels(IGV.java:2574)
        at org.broad.igv.ui.IGV.receiveEvent(IGV.java:2529)
        at org.broad.igv.ui.event.IGVEventBus.post(IGVEventBus.java:84)
        at org.broad.igv.ui.panel.ReferenceFrame.jumpTo(ReferenceFrame.java:457)
        at org.broad.igv.ui.panel.ReferenceFrame.jumpTo(ReferenceFrame.java:420)
        at org.broad.igv.ui.action.SearchCommand.showSearchResult(SearchCommand.java:218)
        at org.broad.igv.ui.action.SearchCommand.execute(SearchCommand.java:145)
        at org.broad.igv.ui.IGVCommandBar.searchByLocus(IGVCommandBar.java:906)
        at org.broad.igv.ui.IGV.goToLocus(IGV.java:1369)
        at org.broad.igv.batch.CommandExecutor.goto1(CommandExecutor.java:759)
        at org.broad.igv.batch.CommandExecutor.execute(CommandExecutor.java:135)
        at org.broad.igv.batch.CommandListener.processClientSession(CommandListener.java:220)
        at org.broad.igv.batch.CommandListener.run(CommandListener.java:112)
        at java.lang.Thread.run(Thread.java:745)

And the event queue itself:

"AWT-EventQueue-0" #19 prio=6 os_prio=0 tid=0x00007fa0ac700000 nid=0x528a waiting for monitor entry [0x00007fa08ad8a000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.awt.Component.invalidate(Component.java:2929)
        - waiting to lock <0x0000000083025938> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.invalidate(Container.java:1587)
        at javax.swing.JComponent.revalidate(JComponent.java:4848)
        at javax.swing.plaf.basic.BasicTextUI$RootView.preferenceChanged(BasicTextUI.java:1406)
        at javax.swing.text.View.preferenceChanged(View.java:288)
        at javax.swing.text.PlainView.updateDamage(PlainView.java:575)
        at javax.swing.text.PlainView.removeUpdate(PlainView.java:464)
        at javax.swing.text.FieldView.removeUpdate(FieldView.java:307)
        at javax.swing.plaf.basic.BasicTextUI$RootView.removeUpdate(BasicTextUI.java:1624)
        at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.removeUpdate(BasicTextUI.java:1884)
        at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:259)
        at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:622)
        at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:590)
        at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:666)
        at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
        at org.broad.igv.ui.IGVCommandBar$5.run(IGVCommandBar.java:352)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I assume that in this case, org.broad.igv.ui.IGV.revalidateTrackPanels should be using invokeAndWait (or perhaps it should be happening higher up the stack). 

Do other remote commands have the same problem?

**Comment by jrobinso** [comment]
Yes I think you are correct.  What version are you using?

**Comment by Lenbok** [comment]
Compiled from git a days or so ago. 80bea6c50ee plus a couple of local changes.

**Comment by jrobinso** [comment]
BTW this usually doesn't happen, obviously, or it would have been fixed.
Do you have a script that I could run that reliably reproduces this?   Or
if you are controlling from a another program talking to the port a set of
steps I could emulate in a test program?   You analysis is correct, but
without a means to reproduce I can't test potential fixes.


On Wed, Jan 18, 2017 at 7:31 PM, James Robinson <jrobinso@broadinstitute.org

**Comment by jrobinso** [comment]
Well,  the tip of master in GIT is in a huge state of flux right now.  A
development branch was merged a little prematurely.   Sorting this out will
take a few days to a week.    While I sort that out I suggest you pull from
the tag "PRE_INS"  https://github.com/igvteam/igv/tree/PRE_INS.    If the
problem occurs there see my previous comment about steps to reproduce.
I've just put on my list to review all Swing library calls for thread
safety.

**Comment by Lenbok** [comment]
Yeah, I had never had it happen before either until I updated my IGV git repo (my previous version was from 8 months or so ago). I wonder if it is also related to mousing around (I also use focus-follows mouse), which would possibly invoke events from the regular event queue, at the same time as commands are being processed.

**Comment by Lenbok** [comment]
Thanks, will try that other tag in the meantiime.

**Comment by jrobinso** [comment]
OK, thanks for the report.   When it's all done the new code should be more
stable.     I will update this thread when its safe to return.

**Comment by jrobinso** [comment]
Great tool for finding these problems.   https://github.com/jikuja/SwingEDTCheckAgent

**Comment by jrobinso** [comment]
I think I fixed the issue with that particular command (goto).   Could you pull from master and test again at your convenience?    I will continue to look for EDT problems,  but if you find other hanging commands could you update this issue?   Thanks for your patience.

**Comment by Lenbok** [comment]
Hi Jim, I've tried a few things out with the latest from master and haven't had any problems so far! Thanks for looking into this so quickly!

**Comment by jrobinso** [comment]
The master has a lot of new features not fully baked,  but hopefully all the old features still work as expected.   I'll close this for now,  reopen or open a new one if you encounter further issues.
