### ISSUE TITLE
htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0

### ISSUE THREAD

**Issue by mmokrejs** [igvteam/igv#362]
Hi Jim,
  is this an igvtools issue of htsjdk issue?

```
java -Djavaio.tmpdir=. -Xmx93g -jar /scratch/mmokrejs/IGVTools_2.3.89/igvtools.jar index /scratch/mmokrejs/db/ftp.ensembl.org/pub/release-86/variation/vcf/homo_sapiens/CSHL-HAPMAP-HapMap-CEU.vcf
ERROR [2017-01-20 23:30:23,817]  [IgvTools.java:264] [main]  htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0
java.lang.RuntimeException: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0
        at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:998)
        at org.broad.igv.tools.IgvTools.run(IgvTools.java:393)
        at org.broad.igv.tools.IgvTools.main(IgvTools.java:259)
Caused by: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0
        at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:784)
        at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:569)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseSingleAltAllele(AbstractVCFCodec.java:609)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:539)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:336)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:279)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:257)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:60)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
        at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
        at org.broad.igv.feature.tribble.VCFWrapperCodec.decodeLoc(VCFWrapperCodec.java:58)
        at org.broad.igv.feature.tribble.VCFWrapperCodec.decodeLoc(VCFWrapperCodec.java:43)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:502)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:464)
        at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:338)
        at htsjdk.tribble.index.IndexFactory.createLinearIndex(IndexFactory.java:223)
        at org.broad.igv.tools.IgvTools.createTribbleIndex(IgvTools.java:1062)
        at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:981)
```

Here I show the lines, with a line number in the first column:
```

3793128 X       2772786 rs311154        C       G       .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.0
3793129 X       2775583 rs311159        A       G       .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.522523
3793130 X       2777299 rs6655035       A       G       .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.0
3793131 X       2782116 rs5939319       G       A,0     .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;E_ESP;E_ExAC;AF=0.0833333,0.25
3793132 X       2785350 rs1486175       T       0,C     .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.254237,0.5
3793133 X       2785592 rs1419931       A       0,G     .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.25,0.491667
3793134 X       2787421 rs5982858       G       A       .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.3
3793135 X       2788903 rs11152546      A       G       .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.0
3793136 X       2789693 rs17090623      C       T       .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;E_ESP;E_ExAC;AF=0.0
```

What are those zeroes?

**Comment by jrobinso** [comment]
Either htsjdk or an issue with the VCF file.  .   I suggest posting on
htsjdk and see what they say.   I don't know what those zeroes are,  it
could be an error in the file which is what the htsjdk is complaining
about.   I would post there and see what they say.

**Comment by lbergelson** [comment]
Looks like an invalid VCF to me.  I don't know what the zeroes are meant to represent.  Possibly miss-encoded spanning deletions?
