### ISSUE TITLE
igvtools doesn't count insertion in reverse strand 

### ISSUE THREAD

**Issue by bisnow33** [igvteam/igv#372]
Hi ,
I'am using bash igvtools count with the options --strands and --bases and the results seem good excepted for the reverse strand insertions which looks like add to the forwards. 
Example of my command line : 
bash igvtools count --query=chr7:65444350-65444370 --strands read -w 1 --bases result.wig hg19.fa

Best regards, 

Tristan

**Comment by jrobinso** [comment]
Could you try the following build and let us know if it fixes the problem?

http://www.broadinstitute.org/igv/projects/downloads/snapshot/igvtools_snapshot.zip

**Comment by bisnow33** [comment]
I tried this build but i got some error and the igv.log is empty.

**Comment by jrobinso** [comment]
Could you describe the error,  and also what your command line was?

**Comment by bisnow33** [comment]
My command was :
 bash /home/tdubos/NGS/IGVTools/igvtools count --query=chr7:65444355-65444365 --strands read -w 1 --bases /home/tdubos/Bureau/DI_exom/DI_500_V2/puce_63/IonXpress_010_puce_63/IonXpress_010_puce_63_sorted.bam 186576_Pere_puce_63_64.wig /home/tdubos/NGS/ref/hg19.fa

I had a first error using java 7 so i upgrade for jre1.8.0_101. Then i have the following error starting by :
 ERROR [2017-02-13 09:28:04,113]  [GenomeManager.java:837] [main]  Error fetching genome list: 
java.net.NoRouteToHostException: Aucun chemin d'accès pour atteindre l'hôte cible

ERROR [2017-02-13 09:28:04,132]  [IgvTools.java:264] [main]  
java.lang.NullPointerException

**Comment by jrobinso** [comment]
OK, thanks for the info.  Will look into it.

**Comment by jrobinso** [comment]
Hi, you're missing the output file argument in your command line.  You need
to specify the output file after the "bam" and before the fasta.   It
should end with a ".wig" format if you want a text file.

**Comment by bisnow33** [comment]
Hi i think i already put the wig file in the command : 186576_Pere_puce_63_64.wig
and it's between the 
IonXpress_010_puce_63_sorted.bam
And 
hg19.fa

The command worked with the other build i had i just changed the path to the igvtools you gave to me.
Do i need to put something before the .wig to indicate it or the position is good enough ? 

I give you the complete message error i got  i hope it could help : 
 INFO [2017-02-15 09:02:46,300]  [IgvTools.java:829] [main]  Computing coverage.  File = /home/tdubos/Bureau/DI_exom/DI_500_V2/puce_63/IonXpress_010_puce_63/IonXpress_010_puce_63_sorted.bam
Computing coverage.  File = /home/tdubos/Bureau/DI_exom/DI_500_V2/puce_63/IonXpress_010_puce_63/IonXpress_010_puce_63_sorted.bam
INFO [2017-02-15 09:02:46,302]  [IgvTools.java:830] [main]  Max zoom = 7
Max zoom = 7
INFO [2017-02-15 09:02:46,302]  [IgvTools.java:831] [main]  Window size = 1
Window size = 1
INFO [2017-02-15 09:02:46,302]  [IgvTools.java:836] [main]  Window functions: mean 
Window functions: mean 
INFO [2017-02-15 09:02:46,302]  [IgvTools.java:837] [main]  Ext factor = 0
Ext factor = 0
INFO [2017-02-15 09:02:46,306]  [GenomeManager.java:159] [main]  Loading genome: /home/tdubos/NGS/ref/hg19.fa
Loading genome: /home/tdubos/NGS/ref/hg19.fa
INFO [2017-02-15 09:02:46,399]  [DirectoryManager.java:168] [main]  IGV Directory: /home/tdubos/igv
IGV Directory: /home/tdubos/igv
INFO [2017-02-15 09:02:46,409]  [IGVEventBus.java:80] [main]  No observers for event type: class org.broad.igv.ui.event.GenomeChangeEvent
No observers for event type: class org.broad.igv.ui.event.GenomeChangeEvent
INFO [2017-02-15 09:02:46,466]  [HttpUtils.java:645] [main]  Open connection
Open connection
ERROR [2017-02-15 09:03:06,531]  [GenomeManager.java:837] [main]  Error fetching genome list: 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:727)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:630)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:626)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:232)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:226)
	at org.broad.igv.feature.genome.GenomeManager.getServerGenomeArchiveList(GenomeManager.java:799)
	at org.broad.igv.feature.genome.GenomeManager.getServerGenomeIDs(GenomeManager.java:772)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:203)
	at org.broad.igv.tools.IgvTools.loadGenome(IgvTools.java:1183)
	at org.broad.igv.tools.IgvTools.doCount(IgvTools.java:840)
	at org.broad.igv.tools.IgvTools.run(IgvTools.java:376)
	at org.broad.igv.tools.IgvTools.main(IgvTools.java:259)
Error fetching genome list: 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:727)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:630)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:626)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:232)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:226)
	at org.broad.igv.feature.genome.GenomeManager.getServerGenomeArchiveList(GenomeManager.java:799)
	at org.broad.igv.feature.genome.GenomeManager.getServerGenomeIDs(GenomeManager.java:772)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:203)
	at org.broad.igv.tools.IgvTools.loadGenome(IgvTools.java:1183)
	at org.broad.igv.tools.IgvTools.doCount(IgvTools.java:840)
	at org.broad.igv.tools.IgvTools.run(IgvTools.java:376)
	at org.broad.igv.tools.IgvTools.main(IgvTools.java:259)
ERROR [2017-02-15 09:03:06,546]  [IgvTools.java:264] [main]  
java.lang.NullPointerException
	at org.broad.igv.feature.genome.GenomeManager.getServerGenomeIDs(GenomeManager.java:772)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:203)
	at org.broad.igv.tools.IgvTools.loadGenome(IgvTools.java:1183)
	at org.broad.igv.tools.IgvTools.doCount(IgvTools.java:840)
	at org.broad.igv.tools.IgvTools.run(IgvTools.java:376)
	at org.broad.igv.tools.IgvTools.main(IgvTools.java:259)

java.lang.NullPointerException
	at org.broad.igv.feature.genome.GenomeManager.getServerGenomeIDs(GenomeManager.java:772)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:203)
	at org.broad.igv.tools.IgvTools.loadGenome(IgvTools.java:1183)
	at org.broad.igv.tools.IgvTools.doCount(IgvTools.java:840)
	at org.broad.igv.tools.IgvTools.run(IgvTools.java:376)
	at org.broad.igv.tools.IgvTools.main(IgvTools.java:259)

Tristan

**Comment by jrobinso** [comment]
OK,  the full output was helpful.  IGVTools is trying to update the genome
list from our server, even though in this case it does not need to.   This
is causing a network timeout because apparently the computer you are
running this on is not able to connect.

I will remove this unneeded server call and update you here when a new
version is ready.

**Comment by jrobinso** [comment]
OK, could you try downloading and running again?  I tested with my computer
disconnected from the network.

http://www.broadinstitute.org/igv/projects/downloads/snapshot/igvtools_snapshot.zip



On Wed, Feb 15, 2017 at 1:39 PM, James Robinson <jrobinso@broadinstitute.org
> wrote:

> OK,  the full output was helpful.  IGVTools is trying to update the genome
> list from our server, even though in this case it does not need to.   This
> is causing a network timeout because apparently the computer you are
> running this on is not able to connect.
>
> I will remove this unneeded server call and update you here when a new
> version is ready.
>
>

**Comment by bisnow33** [comment]
Hi , 
Thanks a lot this build work find and solved the problem ! My 22 port is locked i think it's why i couldn’t download the genome. 

Best ,

Tristan
