### ISSUE TITLE
Misleading documentation about running in igvtools in a headless environment

### ISSUE THREAD

**Issue by moskalenko** [igvteam/igv#375]
http://software.broadinstitute.org/software/igv/igvtools_commandline implies that igv.jar can be used in a headless environment. However, that statement doesn't appear to be quite correct. Any attempt to run igv like that will result in a java.awt.HeadlessException.

java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:181)
        at org.broad.igv.ui.Main$1.run(Main.java:95)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:702)
        at java.awt.EventQueue$3.run(EventQueue.java:696)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jrobinso** [comment]
The statement is about igvtools specifically,  not "igv.jar".   What
command line did you use?

**Comment by moskalenko** [comment]
Sorry about this. It looks like my colleague and I missed the igvtools zip download location and the igv source from github doesn't have a build configuration for igvtools. After seeing your comment I double-checked the Broad website and found http://data.broadinstitute.org/igv/projects/downloads/igvtools_2.3.91.zip . Please close this issue. However, if possible, please point me to the build procedure for igvtools.

Thank you!

**Comment by jrobinso** [comment]
The script is in the "scripts" folder.  You must include the bcel-6.0.jar
in your ant classpath, or use the "-lib" option.   For example

ant -lib ant/bcel-6.0.jar -buildfile scripts/build-tools.xml
