### ISSUE TITLE
Issues loading data from GCS

### ISSUE THREAD

**Issue by jstjohn** [igvteam/igv#381]
I am having issues loading data through GCS, when I load the URL of a bam file's GCS URI after logging in to Google through IGV, nothing happens in the UI, and it looks like there is an error in the log. I followed the setup instructions for getting going with the google URIs as described here [http://googlegenomics.readthedocs.io/en/staging/use_cases/browse_genomic_data/igv.html#igv-desktop](). When I try to load some of my `gs://...` bam files I get an error in the log that looks like: `ERROR [2017-03-22 12:59:24,082] [HttpUtils.java:724]  Range header removed by proxy or ignored by server for url: `. I also get this same error for the public example file they have listed on the previous link if you would like to reproduce what I am seeing.

Here is my error message from the IGV log when trying to load `gs://genomics-public-data/platinum-genomes/bam/NA12877_S1.bam` for example:
```
ERROR [2017-03-22 12:59:24,082] [HttpUtils.java:724]  Range header removed by proxy or ignored by server for url: https://www.googleapis.com/storage/v1/b/genomics-public-data/o/platinum-genomes%2Fbam%2FNA12877_S1.bam?alt=media
ERROR [2017-03-22 12:59:24,082] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:726)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:626)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:622)
	at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:228)
	at org.broad.igv.ui.action.LoadFromURLMenuAction.ping(LoadFromURLMenuAction.java:169)
	at org.broad.igv.ui.action.LoadFromURLMenuAction.actionPerformed(LoadFromURLMenuAction.java:98)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

Thanks for your time!

**Comment by jstjohn** [comment]
Also I just verified that those public GS links to both the bam and bam index seem to still be valid:

```
> gsutil ls gs://genomics-public-data/platinum-genomes/bam/NA12877_S1.bam*
gs://genomics-public-data/platinum-genomes/bam/NA12877_S1.bam
gs://genomics-public-data/platinum-genomes/bam/NA12877_S1.bam.bai
```

**Comment by jrobinso** [comment]
@yfarjoun is this the same issue you are experiencing?   There's either a firewall / proxy  between you and the google server that is removing range headers,   OR,  something has changed at google.  If @jstjohn is not at the Broad Institute it is probably the latter.   Will investigate.

**Comment by jrobinso** [comment]
Something has changed at google, and recently, their server is not recognizing range requests.  I'll contact them,  don't know how quick the fix will be.   There's nothing we can do on this end.   If either @yfarjon or @jstjohn have contacts there you might try them as well.

**Comment by jrobinso** [comment]
OK,  my bad!  We were incorrectly formatting the range header for 1 call in a way that google tolerated up till now.  I fixed the header and its working again.    I will push this change this evening, release number will be 2.3.92

**Comment by jstjohn** [comment]
Thanks @jrobinso! I am not at the broad FYI if it helps. Sounds like you tracked down the issue and all already though.

**Comment by jstjohn** [comment]
I just built IGV and verified that your fix works for me. Thanks again @jrobinso! See my PR for a minor change I had to make to file names to get the build working on OSX with my versions of ANT and java at least (https://github.com/igvteam/igv/pull/382)
