### ISSUE TITLE
Debian 9 : Unable to launch IGV

### ISSUE THREAD

**Issue by dridk** [igvteam/igv#434]
I have a fresh install of Debian 9 with XFCE. 
I m unable to launch IGV with oracle java 8 or openjdk . 

```

INFO [2017-06-29 10:44:42,451]  [DirectoryManager.java:169] [AWT-EventQueue-1]  IGV Directory: /home/sacha/igv
INFO [2017-06-29 10:44:42,451] [DirectoryManager.java:169]  IGV Directory: /home/sacha/igv
INFO [2017-06-29 10:44:42,455]  [Main.java:150] [AWT-EventQueue-1]  Startup  IGV Version 2.3.94 (152)06/11/2017 07:09 PM
INFO [2017-06-29 10:44:42,456]  [Main.java:151] [AWT-EventQueue-1]  Java 1.8.0_131
INFO [2017-06-29 10:44:42,456]  [DirectoryManager.java:72] [AWT-EventQueue-1]  Fetching user directory... 
INFO [2017-06-29 10:44:42,473]  [Main.java:152] [AWT-EventQueue-1]  Default User Directory: /home/sacha
INFO [2017-06-29 10:44:42,473]  [Main.java:153] [AWT-EventQueue-1]  OS: Linux
INFO [2017-06-29 10:44:46,658]  [IGV.java:1185] [AWT-EventQueue-1]  Warning: could not create fistCursor
ERROR [2017-06-29 10:44:46,659]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-1]  Unhandled exception
java.lang.IllegalArgumentException: Width (0) and height (0) must be non-zero
	at java.awt.image.ReplicateScaleFilter.<init>(ReplicateScaleFilter.java:102)
	at java.awt.Image.getScaledInstance(Image.java:174)
	at sun.awt.CustomCursor.<init>(CustomCursor.java:69)
	at sun.awt.X11CustomCursor.<init>(X11CustomCursor.java:43)
	at sun.awt.X11.XCustomCursor.<init>(XCustomCursor.java:42)
	at sun.awt.X11.XToolkit.createCustomCursor(XToolkit.java:1140)
	at org.broad.igv.ui.IGV.createZoomCursors(IGV.java:1129)
	at org.broad.igv.ui.IGV.<init>(IGV.java:277)
	at org.broad.igv.ui.IGV.createInstance(IGV.java:182)
	at org.broad.igv.ui.Main.open(Main.java:290)
	at org.broad.igv.ui.Main$1.run(Main.java:105)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
INFO [2017-06-29 10:44:47,662]  [ShutdownThread.java:51] [Thread-2]  Shutting down
ERROR [2017-06-29 10:44:47,666]  [DefaultExceptionHandler.java:49] [Thread-2]  Unhandled exception
java.lang.NullPointerException
	at org.broad.igv.ui.IGV.getTrackPanels(IGV.java:1392)
	at org.broad.igv.ui.IGV.getAllTracks(IGV.java:2083)
	at org.broad.igv.ui.ShutdownThread.runS(ShutdownThread.java:56)
	at org.broad.igv.ui.ShutdownThread.run(ShutdownThread.java:64)
```

**Comment by jrobinso** [comment]
This is an old linux bug which seemingly occurs at random, by random I mean
affects a few users but not most.    If you do a websearch you will find
many instances,  the root cause seems to be some missing or misconfigured
X11 libraries.   See
https://forums.opensuse.org/showthread.php/489277-java-problems-opensuse-12-3-ahttps://forums.opensuse.org/showthread.php/489277-java-problems-opensuse-12-3-a
 for example, there are many others.

This doesn't help you of course.   I will add a workaround for this,  the
consequence will be that IGV starts up but you will loose all custom
cursors.  Probably not a serious loss just letting you know.

**Comment by jrobinso** [comment]
Could you try the snapshot version and tell us if it solves the problem?  If it does I'll release as 2.3.95.  You can install from here, or just pull from master and build.   http://software.broadinstitute.org/software/igv/download_snapshot

**Comment by jrobinso** [comment]
@dridk ping -- have you been able to try the snapshot version?

**Comment by dridk** [comment]
i will try monday. I was not avaible for a test this week.

**Comment by dridk** [comment]
It works !!!!!

```
WARN [2017-07-10 15:03:54,674]  [Globals.java:138] [AWT-EventQueue-1]  Development mode is enabled
INFO [2017-07-10 15:03:54,862]  [DirectoryManager.java:168] [AWT-EventQueue-1]  IGV Directory: /home/sacha/igv
INFO [2017-07-10 15:03:54,862] [DirectoryManager.java:168]  IGV Directory: /home/sacha/igv
INFO [2017-07-10 15:03:54,864]  [Main.java:154] [AWT-EventQueue-1]  Startup  IGV Version snapshot 07/06/2017 04:45 PM
INFO [2017-07-10 15:03:54,876]  [Main.java:155] [AWT-EventQueue-1]  Java 1.8.0_131
INFO [2017-07-10 15:03:54,877]  [DirectoryManager.java:73] [AWT-EventQueue-1]  Fetching user directory... 
INFO [2017-07-10 15:03:55,001]  [Main.java:156] [AWT-EventQueue-1]  Default User Directory: /home/sacha
INFO [2017-07-10 15:03:55,001]  [Main.java:157] [AWT-EventQueue-1]  OS: Linux


INFO [2017-07-10 15:03:55,396]  [HttpUtils.java:626] [Thread-3]  Open connection
juil. 10, 2017 3:03:55 PM java.util.prefs.FileSystemPreferences$6 run
AVERWARN [2017-07-10 15:03:54,674]  [Globals.java:138] [AWT-EventQueue-1]  Development mode is enabled
INFO [2017-07-10 15:03:54,862]  [DirectoryManager.java:168] [AWT-EventQueue-1]  IGV Directory: /home/sacha/igv
INFO [2017-07-10 15:03:54,862] [DirectoryManager.java:168]  IGV Directory: /home/sacha/igv
INFO [2017-07-10 15:03:54,864]  [Main.java:154] [AWT-EventQueue-1]  Startup  IGV Version snapshot 07/06/2017 04:45 PM
INFO [2017-07-10 15:03:54,876]  [Main.java:155] [AWT-EventQueue-1]  Java 1.8.0_131
INFO [2017-07-10 15:03:54,877]  [DirectoryManager.java:73] [AWT-EventQueue-1]  Fetching user directory... 
INFO [2017-07-10 15:03:55,001]  [Main.java:156] [AWT-EventQueue-1]  Default User Directory: /home/sacha
INFO [2017-07-10 15:03:55,001]  [Main.java:157] [AWT-EventQueue-1]  OS: Linux


INFO [2017-07-10 15:03:55,396]  [HttpUtils.java:626] [Thread-3]  Open connection
juil. 10, 2017 3:03:55 PM java.util.prefs.FileSystemPreferences$6 run
AVERTISSEMENT: Prefs file removed in background /home/sacha/.java/.userPrefs/prefs.xml
INFO [2017-07-10 15:03:55,408]  [HttpUtils.java:626] [Thread-3]  Open connection
INFO [2017-07-10 15:03:57,832]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Move
INFO [2017-07-10 15:03:57,833]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Zoom in
INFO [2017-07-10 15:03:57,834]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Zoom out
INFO [2017-07-10 15:03:57,835]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Drag and Drop
INFO [2017-07-10 15:04:04,595]  [GenomeManager.java:1099] [pool-2-thread-1]  java.io.FileNotFoundException: /home/sacha/igv/genomes/user-defined-genomes.txt (Aucun fichier ou dossier de ce type)
INFO [2017-07-10 15:04:04,723]  [IGVCommandBar.java:460] [pool-2-thread-1]  Selecting genome hg19
INFO [2017-07-10 15:04:04,738]  [IGVCommandBar.java:234] [AWT-EventQueue-1]  Enter genome combo box
INFO [2017-07-10 15:04:04,738]  [IGVCommandBar.java:240] [AWT-EventQueue-1]  Loading hg19  Human hg19   http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
INFO [2017-07-10 15:04:04,740]  [IGVCommandBar.java:251] [pool-2-thread-2]  Loading hg19
INFO [2017-07-10 15:04:04,763]  [GenomeManager.java:180] [pool-2-thread-2]  Loading genome: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
INFO [2017-07-10 15:04:04,798]  [URLDownloader.java:89] [pool-2-thread-2]  Downloading http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome to /home/sacha/igv/genomes/hg19.genome
INFO [2017-07-10 15:04:04,800]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:05,038]  [CommandListener.java:120] [Thread-8]  Listening on port 60151
INFO [2017-07-10 15:04:09,408]  [URLDownloader.java:134] [pool-2-thread-2]  Download complete.  Total bytes downloaded = 6418326
INFO [2017-07-10 15:04:09,579]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:09,743]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:09,940]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:12,743]  [IGVCommandBar.java:234] [AWT-EventQueue-1]  Enter genome combo box
INFO [2017-07-10 15:04:12,767]  [GenomeManager.java:246] [pool-2-thread-2]  Genome loaded.  id= hg19
TISSEMENT: Prefs file removed in background /home/sacha/.java/.userPrefs/prefs.xml
INFO [2017-07-10 15:03:55,408]  [HttpUtils.java:626] [Thread-3]  Open connection
INFO [2017-07-10 15:03:57,832]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Move
INFO [2017-07-10 15:03:57,833]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Zoom in
INFO [2017-07-10 15:03:57,834]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Zoom out
INFO [2017-07-10 15:03:57,835]  [IGV.java:964] [AWT-EventQueue-1]  Could not create cursor: Drag and Drop
INFO [2017-07-10 15:04:04,595]  [GenomeManager.java:1099] [pool-2-thread-1]  java.io.FileNotFoundException: /home/sacha/igv/genomes/user-defined-genomes.txt (Aucun fichier ou dossier de ce type)
INFO [2017-07-10 15:04:04,723]  [IGVCommandBar.java:460] [pool-2-thread-1]  Selecting genome hg19
INFO [2017-07-10 15:04:04,738]  [IGVCommandBar.java:234] [AWT-EventQueue-1]  Enter genome combo box
INFO [2017-07-10 15:04:04,738]  [IGVCommandBar.java:240] [AWT-EventQueue-1]  Loading hg19  Human hg19   http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
INFO [2017-07-10 15:04:04,740]  [IGVCommandBar.java:251] [pool-2-thread-2]  Loading hg19
INFO [2017-07-10 15:04:04,763]  [GenomeManager.java:180] [pool-2-thread-2]  Loading genome: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
INFO [2017-07-10 15:04:04,798]  [URLDownloader.java:89] [pool-2-thread-2]  Downloading http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome to /home/sacha/igv/genomes/hg19.genome
INFO [2017-07-10 15:04:04,800]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:05,038]  [CommandListener.java:120] [Thread-8]  Listening on port 60151
INFO [2017-07-10 15:04:09,408]  [URLDownloader.java:134] [pool-2-thread-2]  Download complete.  Total bytes downloaded = 6418326
INFO [2017-07-10 15:04:09,579]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:09,743]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:09,940]  [HttpUtils.java:626] [pool-2-thread-2]  Open connection
INFO [2017-07-10 15:04:12,743]  [IGVCommandBar.java:234] [AWT-EventQueue-1]  Enter genome combo box
INFO [2017-07-10 15:04:12,767]  [GenomeManager.java:246] [pool-2-thread-2]  Genome loaded.  id= hg19

```
