### ISSUE TITLE
Errors in the log when loading genome from dropdown menu (IGV 3.0 beta)

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#436]
IGV 3.0 beta build 6/29/17 1:45pm

Selecting any genome for the dropdown menu produces the following errors in the log. However the genome does load correctly, but does this error indicate it's trying to download the genome file every time it's selected from the menu? In this example from the log it's hg19, but I get the same error for any genome in the menu.  I don't see the same errors when I first load a genome from the server.

INFO [2017-06-30 12:17:10,640] [URLDownloader.java:89]  Downloading http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome to /Users/helga/http:/s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
ERROR [2017-06-30 12:17:10,746] [URLDownloader.java:70]  http:/s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome (No such file or directory)
java.io.FileNotFoundException: http:/s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.broad.igv.util.URLDownloader.doDownload(URLDownloader.java:108)
        at org.broad.igv.util.URLDownloader.run(URLDownloader.java:68)
        at org.broad.igv.util.HttpUtils.downloadFile(HttpUtils.java:446)
        at org.broad.igv.util.HttpUtils.downloadFile(HttpUtils.java:431)
        at org.broad.igv.feature.genome.GenomeManager.refreshCache(GenomeManager.java:676)
        at org.broad.igv.feature.genome.GenomeManager.checkCacheForId(GenomeManager.java:620)
        at org.broad.igv.ui.IGVCommandBar$GenomeBoxActionListener$1.run(IGVCommandBar.java:266)
        at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jrobinso** [comment]
That's a bug obviously.   It checks the file date and downloads if the
server is newer,  but look at the url, obviously wrong.  I think its
failing on the remote modified check due to the bad URL, then it downloads
since the check failed.
