### ISSUE TITLE
Saving snapshot error

### ISSUE THREAD

**Issue by pengyu1608** [igvteam/igv#438]
When using the "Save image" function, the console got errors. 

The log file is as following:

INFO [2017-07-05 09:54:59,416] [Main.java:135]  Startup  IGV Version 2.3.92 (147)04/27/2017 10:54 PM
INFO [2017-07-05 09:54:59,416] [Main.java:136]  Java 1.8.0_101
INFO [2017-07-05 09:54:59,417] [Main.java:137]  Default User Directory: C:\Users\yp\Documents
INFO [2017-07-05 09:54:59,418] [Main.java:138]  OS: Windows 10
INFO [2017-07-05 09:55:05,725] [Main.java:185]  A later version of IGV is available (2.3.93)
INFO [2017-07-05 09:55:16,776] [GenomeManager.java:145]  Loading genome: C:\Users\yp\igv\genomes\mm9.genome
INFO [2017-07-05 09:55:19,134] [GenomeManager.java:192]  Genome loaded.  id= mm9
INFO [2017-07-05 09:55:19,602] [CommandListener.java:106]  Listening on port 60151
INFO [2017-07-05 09:55:46,095] [TrackLoader.java:126]  Loading resource, path http://172.31.202.11/yupengBAM/mm_VSMC_FBS_PolII.bigWig
INFO [2017-07-05 09:55:46,096] [TrackLoader.java:126]  Loading resource, path http://172.31.202.11/yupengBAM/mm_VSMC_shH2AZ_Med1.bigWig
INFO [2017-07-05 09:55:46,108] [HttpUtils.java:856]  Range-byte request succeeded
ERROR [2017-07-05 09:57:12,310] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.NullPointerException
	at org.broad.igv.ui.util.SnapshotFileChooser.getSnapshotFileType(SnapshotFileChooser.java:90)
	at org.broad.igv.ui.IGV.createSnapshotNonInteractive(IGV.java:1071)
	at org.broad.igv.ui.IGV.createSnapshot(IGV.java:1038)
	at org.broad.igv.ui.IGV.saveImage(IGV.java:1020)
	at org.broad.igv.ui.panel.TrackPanelComponent.saveImage(TrackPanelComponent.java:283)
	at org.broad.igv.ui.panel.TrackPanelComponent$2.actionPerformed(TrackPanelComponent.java:219)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI.doClick(VsnetMenuItemUI.java:1395)
	at com.jidesoft.plaf.vsnet.VsnetMenuItemUI$MouseInputHandler.mouseReleased(VsnetMenuItemUI.java:1190)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by jrobinso** [comment]
Thanks for the report.  When saving an image you must give the file an extension,  for example .png.
