### ISSUE TITLE
IGV Java Webstart not working after Java update

### ISSUE THREAD

**Issue by valamates** [igvteam/igv#442]
I have been using IGV on Java Web Start successfully on my PC (IGV 2.3, Windows 7 Pro, 32 bits system) until yesterday. This morning, when trying to launch it, I was requested to update my Java version. I did it, uploading the last Java version (build 1.8.0_141-b15), and now IGV cannot launch anymore, I got an errror message saying:
Impossible to check a signature in the ressource :
https://data.broadinstitute.org/igv/projects/current/igv.jar

java.lang.SecurityException: digest missing for org/broad/igv
	at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarVerifier$VerifierStream.<init>(Unknown Source)
	at java.util.jar.JarFile.getInputStream(Unknown Source)
	at com.sun.deploy.security.JarVerifier.authenticateJarEntry(Unknown Source)
	at com.sun.deploy.security.EnhancedJarVerifier.validate(Unknown Source)
	at com.sun.deploy.cache.CacheEntry.processJar(Unknown Source)
	at com.sun.deploy.cache.CacheEntry.access$2700(Unknown Source)
	at com.sun.deploy.cache.CacheEntry$7.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.deploy.cache.CacheEntry.writeFileToDisk(Unknown Source)
	at com.sun.deploy.cache.CacheEntry.writeFileToDisk(Unknown Source)
	at com.sun.deploy.cache.Cache.downloadResourceToTempFile(Unknown Source)
	at com.sun.deploy.cache.Cache.downloadResourceToCache(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.LaunchDownload$DownloadTask.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jrobinso** [comment]
Try clearing your java cache (search "clear java cache" for instructions).

**Comment by jrobinso** [comment]
I think I have found and fixed the problem, please try again.   There was a change in Java 8 1.4.1 wrt the Manifest.

**Comment by valamates** [comment]
Dear Jim
Thanks a lot ! I am on holidays right now, I will try it as soon as I come back to work.
Best regards,
Valerie

-----Message d'origine-----
De : "Jim Robinson" <notifications@github.com>
Envoyé : ‎25/‎07/‎2017 06:19
À : "igvteam/igv" <igv@noreply.github.com>
Cc : "valamates" <valerie.amarger@univ-nantes.fr>; "Author" <author@noreply.github.com>
Objet : Re: [igvteam/igv] IGV Java Webstart not working after Java update(#442)

I think I have found and fixed the problem, please try again. There was a change in Java 8 1.4.1 wrt the Manifest.
