### ISSUE TITLE
Sashimi plot not showing (IGV 2.4 Beta)

### ISSUE THREAD

**Issue by Kazyra** [igvteam/igv#452]
On step 8 of the "Viewing RNA-Seq Data" Exercise in "IGV Exercises.pdf" [here](http://www.igv.org/workshops/BroadApril2017/) , the pop-up window which should contain the Sashimi plot is empty.

**Comment by helgathorv** [comment]
Nothing shows up in the igv.log, but the following shows up in the Java console when I loaded the tutorial Body Map data from server (ref genome hg19), jumped to slc25a3, and clicked on "Sashimi Plot" in the menu:

INFO [2017-08-22 17:17:49,884]  [FeatureTrack.java:736] [AWT-EventQueue-2]  Loaded chr12 98979214-99003966
ERROR [2017-08-22 17:17:49,942]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-2]  Unhandled exception
java.lang.NullPointerException
	at org.broad.igv.sam.CoverageTrack$IntervalRenderer.paint(CoverageTrack.java:476)
	at org.broad.igv.sam.CoverageTrack$IntervalRenderer.access$000(CoverageTrack.java:457)
	at org.broad.igv.sam.CoverageTrack.drawData(CoverageTrack.java:264)
	at org.broad.igv.sam.CoverageTrack.render(CoverageTrack.java:236)
	at org.broad.igv.renderer.SashimiJunctionRenderer.render(SashimiJunctionRenderer.java:194)
	at org.broad.igv.track.FeatureTrack.renderFeatureImpl(FeatureTrack.java:913)
	at org.broad.igv.track.FeatureTrack.renderFeatures(FeatureTrack.java:858)
	at org.broad.igv.sam.SpliceJunctionTrack.renderFeatures(SpliceJunctionTrack.java:262)
	at org.broad.igv.track.FeatureTrack.render(FeatureTrack.java:763)
	at org.broad.igv.ui.SashimiPlot$TrackComponent.paintComponent(SashimiPlot.java:275)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jrobinso** [comment]
This is fixed i v2.4-rc6
