### ISSUE TITLE
Details popup broken in 2.4  (Cannot format given object as a Number)

### ISSUE THREAD

**Issue by pmarks** [igvteam/igv#463]
Trying to bring up a details pop-up gives the following exception in igv.log, and fails to load the pop-up:

ERROR [2017-09-21 13:52:37,276] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.IllegalArgumentException: Cannot format given Object as a Number
        at java.text.DecimalFormat.format(DecimalFormat.java:507)
        at java.text.Format.format(Format.java:157)
        at org.broad.igv.sam.SAMAlignment.getValueStringImpl(SAMAlignment.java:636)
        at org.broad.igv.sam.SAMAlignment.getValueString(SAMAlignment.java:465)
        at org.broad.igv.sam.AlignmentTrack.getValueStringAt(AlignmentTrack.java:999)
        at org.broad.igv.ui.panel.DataPanel.updateTooltipText(DataPanel.java:512)
        at org.broad.igv.ui.panel.DataPanel$DataPanelMouseAdapter.mouseMoved(DataPanel.java:635)
        at java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:329)
        at java.awt.Component.processMouseMotionEvent(Component.java:6578)
        at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)

Looks like the offending commit is here:
https://github.com/igvteam/igv/commit/e6b30d03c8fdcd458cd12b6669f7c9449d7a4118

This change causes a string to be passed to:
`Globals.DECIMAL_FORMAT.format(quality)`

here:
https://github.com/igvteam/igv/blob/0882b4d280efc7bccc13e78660f0b385041a3ef7/src/org/broad/igv/sam/SAMAlignment.java#L636

**Comment by slw287r** [comment]
Exactly the same here.
btw: for the previous 2.4 beta version, an empty square will pop up when I hover mouse out of reads in the alignment panel.

**Comment by jrobinso** [comment]
Thanks for the report and analysis.   This should be fixed (2.4.1)
