### ISSUE TITLE
build failure igvtools 2.4.1

### ISSUE THREAD

**Issue by ilovezfs** [igvteam/igv#464]
```
BUILD FAILED
/private/tmp/igvtools-20170926-25059-15zblfx/igv-2.4.1/scripts/build-tools.xml:73: java.lang.NoClassDefFoundError: org/apache/bcel/classfile/Visitor
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.tools.ant.types.optional.depend.DependScanner.scan(DependScanner.java:111)
	at org.apache.tools.ant.types.optional.depend.ClassfileSet.getDirectoryScanner(ClassfileSet.java:145)
	at org.apache.tools.ant.taskdefs.Zip.grabResources(Zip.java:1591)
	at org.apache.tools.ant.taskdefs.Zip.getResourcesToAdd(Zip.java:1328)
	at org.apache.tools.ant.taskdefs.Zip.getResourcesToAdd(Zip.java:1261)
	at org.apache.tools.ant.taskdefs.Jar.getResourcesToAdd(Jar.java:868)
	at org.apache.tools.ant.taskdefs.Zip.executeMain(Zip.java:648)
	at org.apache.tools.ant.taskdefs.Zip.execute(Zip.java:600)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: java.lang.ClassNotFoundException: org.apache.bcel.classfile.Visitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

Total time: 18 seconds
```
https://jenkins.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1574/version=sierra/testReport/junit/brew-test-bot/sierra/install_homebrew_science_igvtools/

```
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
```

**Comment by jrobinso** [comment]
The bcel jar is required in ant's classpath for building igvtools.  This is not a new requirement, but apologies that it is not documented.   See instructions here (search for bcel.jar)  http://ant.apache.org/manual/install.html.

**Comment by ilovezfs** [comment]
OK.
