### ISSUE TITLE
error with DISPLAY variable

### ISSUE THREAD

**Issue by amir-ariff** [igvteam/igv#471]
Hello,

I've had no troubles running IGV in the past, but for some reason I could not invoke it today. Here's the error I've encountered:

amir@MDHS-NIX-030[IGV_2.3.86] java -jar igv.jar                                                                                                                                                                                      [ 2:10PM]
INFO [2017-10-11 14:11:36,292]  [DirectoryManager.java:169] [main]  IGV Directory: /home/amir/igv
INFO [2017-10-11 14:11:36,292] [DirectoryManager.java:169]  IGV Directory: /home/amir/igv
INFO [2017-10-11 14:11:36,302]  [Main.java:134] [main]  Startup  IGV Version 2.3.86 (137)11/01/2016 05:27 PM
INFO [2017-10-11 14:11:36,302]  [Main.java:135] [main]  Java 1.7.0_131
INFO [2017-10-11 14:11:36,303]  [DirectoryManager.java:72] [main]  Fetching user directory... 
No protocol specified
ERROR [2017-10-11 14:11:36,335]  [DefaultExceptionHandler.java:49] [main]  Unhandled exception
java.lang.InternalError: Can't connect to X11 window server using ':52.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at java.awt.Toolkit$2.run(Toolkit.java:869)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
	at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:1928)
	at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:752)
	at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:433)
	at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
	at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1588)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:536)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:576)
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1345)
	at javax.swing.UIManager.initialize(UIManager.java:1455)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1422)
	at javax.swing.UIManager.getDefaults(UIManager.java:656)
	at javax.swing.UIManager.getString(UIManager.java:785)
	at javax.swing.filechooser.UnixFileSystemView.<clinit>(FileSystemView.java:609)
	at javax.swing.filechooser.FileSystemView.getFileSystemView(FileSystemView.java:86)
	at org.broad.igv.DirectoryManager.getUserDirectory(DirectoryManager.java:73)
	at org.broad.igv.ui.Main.initApplication(Main.java:136)
	at org.broad.igv.ui.Main.main(Main.java:88)

I've tried deleting the prefs.properties file to no avail.
I've also tried setting export  DISPLAY=:0 , which returns a similar error:
amir@MDHS-NIX-030[IGV_2.3.86] java -jar igv.jar                                                                                                                                                                                      [ 2:18PM]
INFO [2017-10-11 14:20:01,875]  [DirectoryManager.java:169] [main]  IGV Directory: /home/amir/igv
INFO [2017-10-11 14:20:01,875] [DirectoryManager.java:169]  IGV Directory: /home/amir/igv
INFO [2017-10-11 14:20:01,880]  [Main.java:134] [main]  Startup  IGV Version 2.3.86 (137)11/01/2016 05:27 PM
INFO [2017-10-11 14:20:01,881]  [Main.java:135] [main]  Java 1.7.0_131
INFO [2017-10-11 14:20:01,881]  [DirectoryManager.java:72] [main]  Fetching user directory... 
No protocol specified
ERROR [2017-10-11 14:20:01,908]  [DefaultExceptionHandler.java:49] [main]  Unhandled exception
java.lang.InternalError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)

I realise this is an older version of IGV, but I cannot run the latest version of IGV on our server due to an outdated java version:
amir@MDHS-NIX-030[IGV_2.4.2] java -jar igv.jar                                                                                                                                                                                       [ 2:21PM]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broad/igv/ui/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by jrobinso** [comment]
Hi, the route of your problem is your X11 configuration, specifically this error

Can't connect to X11 window server using ':52.0' as the value of the DISPLAY variable.

Are you able to run XClock?

**Comment by amir-ariff** [comment]
No, I'm not able to run it:

amir@MDHS-NIX-030[amir] /usr/bin/xclock                                                                                                                                                                                              [ 8:46AM]
connect /tmp/.X11-unix/X51: No such file or directory
Error: Can't open display: localhost:15.0


If it helps elucidate anything, this is run on biolinux via x2go terminal, and other users are able to invoke igv via the same command line, just not myself.

**Comment by amir-ariff** [comment]
It seems that I'm able to run igv when I'm directly logged into the server where the directory is, but not when I ssh into the directory to invoke it. Perhaps this is a limitation of the ssh that I'm not familiar with. If there's a way to allow the invocation via ssh, that might work?

**Comment by jrobinso** [comment]
You need to setup an X-Windows server on your machine, google for instructions I don't recall the details.   This is not an IGV issue.
