### ISSUE TITLE
IGV runs with IGV 9 but with errors & warnings

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#474]
Running the Snapshot version of the binary distribution that was built Oct 12 01:27pm works with Java 9. But it spits out the following errors & warnings:

WARN [2017-10-12 14:22:19,307]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
INFO [2017-10-12 14:22:19,337]  [DirectoryManager.java:171] [AWT-EventQueue-0]  IGV Directory: /Users/helga/igv
INFO [2017-10-12 14:22:19,337] [DirectoryManager.java:171]  IGV Directory: /Users/helga/igv
INFO [2017-10-12 14:22:19,339]  [Main.java:154] [AWT-EventQueue-0]  Startup  IGV Version snapshot 10/12/2017 01:27 PM
INFO [2017-10-12 14:22:19,340]  [Main.java:155] [AWT-EventQueue-0]  Java 9
INFO [2017-10-12 14:22:19,340]  [DirectoryManager.java:76] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2017-10-12 14:22:19,512]  [Main.java:156] [AWT-EventQueue-0]  Default User Directory: /Users/helga
INFO [2017-10-12 14:22:19,512]  [Main.java:157] [AWT-EventQueue-0]  OS: Mac OS X

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by apple.dts.samplecode.osxadapter.OSXAdapter (file:/Users/helga/Downloads/IGV_snapshot-4/igv.jar) to constructor com.apple.eawt.Application()
WARNING: Please consider reporting this to the maintainers of apple.dts.samplecode.osxadapter.OSXAdapter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mac OS X Adapter could not talk to EAWT:
java.lang.NoSuchMethodException: com.apple.eawt.Application.addApplicationListener(com.apple.eawt.ApplicationListener)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
	at apple.dts.samplecode.osxadapter.OSXAdapter.setHandler(OSXAdapter.java:146)
	at apple.dts.samplecode.osxadapter.OSXAdapter.setAboutHandler(OSXAdapter.java:88)
	at org.broad.igv.ui.IGVMenuBar.<init>(IGVMenuBar.java:166)
	at org.broad.igv.ui.IGVMenuBar.lambda$createInstance$1(IGVMenuBar.java:142)
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166)
	at org.broad.igv.ui.IGVMenuBar.createInstance(IGVMenuBar.java:142)
	at org.broad.igv.ui.IGV.<init>(IGV.java:263)
	at org.broad.igv.ui.IGV.createInstance(IGV.java:164)
	at org.broad.igv.ui.Main.open(Main.java:284)
	at org.broad.igv.ui.Main$1.run(Main.java:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
OSXAdapter could not access the About Menu
java.lang.NoSuchMethodException: com.apple.eawt.Application.setEnabledAboutMenu(boolean)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
	at apple.dts.samplecode.osxadapter.OSXAdapter.setAboutHandler(OSXAdapter.java:93)
	at org.broad.igv.ui.IGVMenuBar.<init>(IGVMenuBar.java:166)
	at org.broad.igv.ui.IGVMenuBar.lambda$createInstance$1(IGVMenuBar.java:142)
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166)
	at org.broad.igv.ui.IGVMenuBar.createInstance(IGVMenuBar.java:142)
	at org.broad.igv.ui.IGV.<init>(IGV.java:263)
	at org.broad.igv.ui.IGV.createInstance(IGV.java:164)
	at org.broad.igv.ui.Main.open(Main.java:284)
	at org.broad.igv.ui.Main$1.run(Main.java:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Mac OS X Adapter could not talk to EAWT:
java.lang.NoSuchMethodException: com.apple.eawt.Application.addApplicationListener(com.apple.eawt.ApplicationListener)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
	at apple.dts.samplecode.osxadapter.OSXAdapter.setHandler(OSXAdapter.java:146)
	at apple.dts.samplecode.osxadapter.OSXAdapter.setQuitHandler(OSXAdapter.java:80)
	at org.broad.igv.ui.IGVMenuBar.<init>(IGVMenuBar.java:167)
	at org.broad.igv.ui.IGVMenuBar.lambda$createInstance$1(IGVMenuBar.java:142)
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166)
	at org.broad.igv.ui.IGVMenuBar.createInstance(IGVMenuBar.java:142)
	at org.broad.igv.ui.IGV.<init>(IGV.java:263)
	at org.broad.igv.ui.IGV.createInstance(IGV.java:164)
	at org.broad.igv.ui.Main.open(Main.java:284)
	at org.broad.igv.ui.Main$1.run(Main.java:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO [2017-10-12 14:22:30,175]  [GenomeManager.java:190] [pool-2-thread-1]  Loading genome: /Users/helga/igv/genomes/hg19.genome
INFO [2017-10-12 14:22:36,817]  [GenomeComboBox.java:79] [AWT-EventQueue-0]  Enter genome combo box
INFO [2017-10-12 14:22:36,825]  [GenomeManager.java:270] [pool-2-thread-1]  Genome loaded.  id= hg19
ERROR [2017-10-12 14:22:36,968]  [CommandListener.java:141] [Thread-4]  java.net.BindException: Address already in use (Bind failed)
INFO [2017-10-12 14:26:14,197]  [ShutdownThread.java:47] [Thread-1]  Shutting down

**Comment by davideby** [comment]
The issue is with reflective access to internal Apple APIs through the OSX Adapter, which is flagged as illegal and blocked in Java 9.

Java 9 has added new public cross-platform APIs to handle these same calls so in the longer term we'll be able to switch to those in the future (see this [migration guide](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7744EF96-5899-4FB2-B34E-86D49B2E89B6)).  The major downside is that doing this would tie IGV to requiring Java 9 and we're nowhere near ready for that.

In the shorter term, we might be able to add an exception at the command line to allow these.

**Comment by davideby** [comment]
On a separate note, related to this log message:
ERROR [2017-10-12 14:22:36,968] [CommandListener.java:141] [Thread-4] java.net.BindException: Address already in use (Bind failed)

I'm highly suspicious of whatever's behind this as the cause of the issues running under JNLP .

**Comment by jrobinso** [comment]
That just means you are already running IGV and its taking the 60151 port.
  You can have only 1 IGV instance listening on that port at a time.
 That's perfectly normal.
