### ISSUE TITLE
Unhandled exception when running IGV from JavaWebStart with Java 9 

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#475]
INFO [2017-10-12 16:06:08,599] [Main.java:154]  Startup  **IGV Version 2.4.2 10/05/2017 02:06 PM**
INFO [2017-10-12 16:06:08,600] [Main.java:155]  Java 9
INFO [2017-10-12 16:06:08,600] [DirectoryManager.java:76]  Fetching user directory... 
INFO [2017-10-12 16:06:08,604] [Main.java:156]  Default User Directory: /Users/helga
INFO [2017-10-12 16:06:08,605] [Main.java:157]  OS: Mac OS X
ERROR [2017-10-12 16:06:12,879] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.IllegalAccessError: class com.jidesoft.plaf.LookAndFeelFactory (in unnamed module @0x6336103) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x6336103
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
        at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
        at org.broad.igv.ui.Main.initializeLookAndFeel(Main.java:324)
        at org.broad.igv.ui.Main.open(Main.java:265)
        at org.broad.igv.ui.Main$1.run(Main.java:108)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by davideby** [comment]
There are some severe issues when launching IGV with Java 9 under WebStart (through the JNLPs).  We should note this as unsupported for now and steer users to the workaround of running from the command line or modified scripts.

**Comment by jrobinso** [comment]
Looks like this could be fixed with a Jide update.  
https://github.com/jidesoft/jide-oss/issues/25

**Comment by jrobinso** [comment]
Webstart is not and will not be supported for Java versions > 8.

**Comment by slw287r** [comment]
FYI

>[Workaround Java 10 Issue /w missing Windows LnF](https://github.com/jidesoft/jide-oss/commit/bce89cec677169503b820cb67ca5709f7c72e6ec)
>as of Java 10, com.sun.java.swing.plaf.windows.WindowsLookAndFeel is no longer available on macOS thus "instanceof indowsLookAndFeel" directives will result in a NoClassDefFoundError during runtime and the code will break. The proposed fix works around this problem.

**Comment by jrobinso** [comment]
Thanks @slw287r

**Comment by bourgesl** [comment]
I fixed jide-oss 3.7.4 build:
https://github.com/jidesoft/jide-oss/pull/32
It works with javaws 10...
