### ISSUE TITLE
Unable to open IGV successful, and the log says :"Error checking version", how to fix this problem?

### ISSUE THREAD

**Issue by LeanGreen** [igvteam/igv#502]
# My java version is below:
```
java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
# and when I open IGV, it can't load genome hg19 well. I checked the log, it says: 
```
INFO [2018-01-03 21:28:39,913] [Main.java:154]  Startup  IGV Version 2.4.5 12/14/2017 01:18 AM
INFO [2018-01-03 21:28:39,914] [Main.java:155]  Java 1.8.0_151
INFO [2018-01-03 21:28:39,914] [DirectoryManager.java:76]  Fetching user directory...
INFO [2018-01-03 21:28:39,954] [Main.java:156]  Default User Directory: /home/zcz
INFO [2018-01-03 21:28:39,955] [Main.java:157]  OS: Linux
ERROR [2018-01-03 21:31:20,364] [Main.java:211]  Error checking version
java.net.SocketTimeoutException
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:734)
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
        at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:148)
        at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:141)
        at org.broad.igv.ui.Main.lambda$checkVersion$0(Main.java:189)
        at java.lang.Thread.run(Thread.java:748)
ERROR [2018-01-03 21:31:40,382] [GenomeListManager.java:407]  Error fetching genome list:
java.net.SocketTimeoutException
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:734)
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
        at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:231)
        at org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:225)
        at org.broad.igv.ui.commandbar.GenomeListManager.getServerGenomeMap(GenomeListManager.java:369)
        at org.broad.igv.ui.commandbar.GenomeListManager.getGenomeListItem(GenomeListManager.java:183)
        at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:167)
        at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2129)
        at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jrobinso** [comment]
The root problem seems to be making an internet connection.  Does this
machine have access to the internet?  Do you have any firewalls that could
be blocking the connection?

**Comment by LeanGreen** [comment]
## Sure, I can use Firefox Browser, and open "http://igv.broadinstitute.org/genomes/genomes.txt", "http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome".
This is the log: 
[igv.log](https://github.com/igvteam/igv/files/1602248/igv.log)

```
INFO [2018-01-04 10:04:04,834] [Main.java:154]  Startup  IGV Version 2.4.5 12/14/2017 01:18 AM
INFO [2018-01-04 10:04:04,834] [Main.java:155]  Java 1.8.0_151
INFO [2018-01-04 10:04:04,835] [DirectoryManager.java:76]  Fetching user directory... 
INFO [2018-01-04 10:04:04,875] [Main.java:156]  Default User Directory: /home/zcz
INFO [2018-01-04 10:04:04,876] [Main.java:157]  OS: Linux
INFO [2018-01-04 10:05:05,684] [GenomeManager.java:182]  Loading genome: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
ERROR [2018-01-04 10:06:45,359] [Main.java:211]  Error checking version
java.net.SocketTimeoutException
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:734)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:148)
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:141)
	at org.broad.igv.ui.Main.lambda$checkVersion$0(Main.java:189)
	at java.lang.Thread.run(Thread.java:748)
INFO [2018-01-04 10:07:05,377] [HttpUtils.java:294]  HEAD request failed for url: http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome.  Trying GET
ERROR [2018-01-04 10:08:05,445] [HttpUtils.java:323]  Error fetching content length
java.net.SocketTimeoutException
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:734)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
	at org.broad.igv.util.HttpUtils.openConnectionHeadOrGet(HttpUtils.java:298)
	at org.broad.igv.util.HttpUtils.getHeaderField(HttpUtils.java:302)
	at org.broad.igv.util.HttpUtils.getContentLength(HttpUtils.java:316)
	at org.broad.igv.ui.util.download.Downloader.run(Downloader.java:54)
	at org.broad.igv.ui.util.download.Downloader.download(Downloader.java:196)
	at org.broad.igv.feature.genome.GenomeManager.refreshCache(GenomeManager.java:706)
	at org.broad.igv.feature.genome.GenomeManager.getArchiveFile(GenomeManager.java:590)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:195)
	at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:168)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2129)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [2018-01-04 10:09:05,523] [Downloader.java:131]  Error downloading http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg19.genome
java.net.SocketTimeoutException
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:734)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
	at org.broad.igv.ui.util.download.Downloader.run(Downloader.java:66)
	at org.broad.igv.ui.util.download.Downloader.download(Downloader.java:196)
	at org.broad.igv.feature.genome.GenomeManager.refreshCache(GenomeManager.java:706)
	at org.broad.igv.feature.genome.GenomeManager.getArchiveFile(GenomeManager.java:590)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:195)
	at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:168)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2129)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [2018-01-04 10:09:05,527] [Downloader.java:164]  Error renaming download file /home/zcz/igv/genomes/hg19.genome.download
java.nio.file.NoSuchFileException: /home/zcz/igv/genomes/hg19.genome.download
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.broad.igv.ui.util.download.Downloader.run(Downloader.java:162)
	at org.broad.igv.ui.util.download.Downloader.download(Downloader.java:196)
	at org.broad.igv.feature.genome.GenomeManager.refreshCache(GenomeManager.java:706)
	at org.broad.igv.feature.genome.GenomeManager.getArchiveFile(GenomeManager.java:590)
	at org.broad.igv.feature.genome.GenomeManager.loadGenome(GenomeManager.java:195)
	at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:168)
	at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2129)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO [2018-01-04 10:09:05,753] [CommandListener.java:120]  Listening on port 60151

```

**Comment by LeanGreen** [comment]
## After these logs, the IGV is opened. But hg19 genome doesn't work, no matter if I use Genome>Load Genome from File>hg19.genome(Download myself). And when I tried to open sorted.bam file, noted "Error loading XXX.bam: null".

**Comment by LeanGreen** [comment]
## After I close the firewall, "service iptables stop". The problem is the same.

**Comment by LeanGreen** [comment]
## It seems to be all kinds of genomes problem.
[igv.log](https://github.com/igvteam/igv/files/1602341/igv.log)

**Comment by jrobinso** [comment]
Yes, something is blocking IGV (a Java program) from making internet
connections.   Its local to you,  I can't really debug the problem from the
log.     Has IGV worked in the past on this machine in this environment?

Sometimes Java does not properly detect Proxy settings from the browser.
 You can set them manually in the IGV "Preferences" window,  select "View >
Preferences"  then the proxy tab.   If you are using a proxy setting this
manually might help.

If nothing else works you can download a local version of the hg19
fasta file and load the genome from your local disk using  "Genomes > Load
Genome from File".  The fasta file and its index (keep these in the same
directory)  can be downloaded from

http://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta
http://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai


Annotations can be downloaded from
http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/refGene.txt.gz

**Comment by LeanGreen** [comment]
## IGV worked well about one month ago. But since last week, it show this problem. And my own laptop(win10) use IGV well.

**Comment by jrobinso** [comment]
Something has changed in your local network,  obviously, IGV has not
changed and the servers you are accessing have not changed.

**Comment by jrobinso** [comment]
Closing this issue as it is a user network problem,  nothing we can do on our side.
