### ISSUE TITLE
Google login not working  

### ISSUE THREAD

**Issue by lmtani** [igvteam/igv#526]
Today I started my IGV and notice that the login with google is not working. Until last week it was working fine.

The log suggest that a json was removed from cloud:

```
abr 02, 2018 9:19:35 AM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/taniguti/.java/.userPrefs/prefs.xml
java.io.FileNotFoundException: File not found: https://dn7ywbm9isq8j.cloudfront.net/app/oauth_native.json
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:775)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:148)
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:141)
	at org.broad.igv.ga4gh.OAuthUtils.fetchOauthProperties(OAuthUtils.java:135)
	at org.broad.igv.ga4gh.OAuthUtils.<init>(OAuthUtils.java:123)
	at org.broad.igv.ga4gh.OAuthUtils.<clinit>(OAuthUtils.java:104)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:628)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:611)
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:607)
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:148)
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:141)
	at org.broad.igv.ui.Main.lambda$checkVersion$0(Main.java:189)
	at java.lang.Thread.run(Thread.java:748)
```
Does anyone know how to get this feature working again? I'm having this problem in different machines (linux and macOs)

**Comment by jrobinso** [comment]
Hi, apologies,  mistake on our end.   Working on a solution.

**Comment by jrobinso** [comment]
This should be fixed now.

**Comment by lmtani** [comment]
@jrobinso Thank you again !
