### ISSUE TITLE
IGV app fails to start on macOS

### ISSUE THREAD

**Issue by tomas-pluskal** [igvteam/igv#527]
Hi,
The IGV_2.4.10.app downloaded from the IGV website fails to start on my system (macOS 10.12.6). It doesn't produce any error message, just dies without showing any window.

By running /Applications/IGV_2.4.10.app/Contents/MacOS/JavaAppLauncher manually from the command line, I got the following exception:

````
$ /Applications/IGV_2.4.10.app/Contents/MacOS/JavaAppLauncher
WARN [2018-04-02 16:36:08,017]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
INFO [2018-04-02 16:36:08,046]  [DirectoryManager.java:171] [AWT-EventQueue-0]  IGV Directory: /Users/plusik/igv
INFO [2018-04-02 16:36:08,046] [DirectoryManager.java:171]  IGV Directory: /Users/plusik/igv
INFO [2018-04-02 16:36:08,050]  [Main.java:154] [AWT-EventQueue-0]  Startup  IGV Version 2.4.10 03/20/2018 10:50 PM
INFO [2018-04-02 16:36:08,051]  [Main.java:155] [AWT-EventQueue-0]  Java 10
INFO [2018-04-02 16:36:08,051]  [DirectoryManager.java:76] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2018-04-02 16:36:09,185]  [Main.java:156] [AWT-EventQueue-0]  Default User Directory: /Users/plusik
INFO [2018-04-02 16:36:09,185]  [Main.java:157] [AWT-EventQueue-0]  OS: Mac OS X


ERROR [2018-04-02 16:36:09,361]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
	at org.broad.igv.ui.Main.initializeLookAndFeel(Main.java:324)
	at org.broad.igv.ui.Main.open(Main.java:265)
	at org.broad.igv.ui.Main$1.run(Main.java:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
INFO [2018-04-02 16:36:11,158]  [ShutdownThread.java:47] [Thread-1]  Shutting down
````

**Comment by helgathorv** [comment]
Looks like you are using Java 10. IGV is still on Java 8. Unfortunately there are significant differences between Java 8 and the next versions. We're working on an update, but no definite release date yet.

**Comment by tomas-pluskal** [comment]
I have Java 8 on my computer, too, and it is configured as default: 
````
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
````
So I'd say the problem is in how IGV detects java during startup? It seems to ignore $JAVA_HOME.

**Comment by jrobinso** [comment]
We use JavaAppLauncher  (JavaAppLauncher is the executable).   I don't see
any settings to specify a JVM,  I would have assumed it would use
$JAVA_HOME but maybe it doesn't.   There isn't a lot of support for
bundling Mac app at the Oracle website,  if you know of anything helpful
please point us to it.

As a workaround you could download the binary distribution and edit the
shell script, if necessary, to point to a specific Java.

Java 9 and greater is a disaster for legacy applications,  do you know of
any that actually support it?

**Comment by tomas-pluskal** [comment]
As far as I know, many of the modules that are disabled in Java 9+ can be enabled again by using the --add-module parameter to the java command.  

Is JavaAppLauncher part of the JDK or is it a third party packager?

**Comment by jrobinso** [comment]
JavaAppLauncher is part of the JDK but doesn't seem to be maintained by Oracle.     I think your best best is to use the "binary distribution",  and modify igv.sh or igv.command if needed to point to the right Java.   

Its not as simple as enabling modules, some libraries we use just won't work at all.  Trust me we have tried.   I don't know of any genomics libraries or apps that work with Java 9 but I might be mistaken.   

We will post an interim solution when we have one,  but it will likely be based on the "binary" distribution and not a bundled, signed mac "app".

**Comment by tomas-pluskal** [comment]
Thanks, the binary distribution works for me. I would suggest to add some warning about this to the download page, and perhaps deprecate the mac app based on the JavaAppLauncher.

**Comment by charlottenguyen** [comment]
How did you get the binary distribution to work? Did you have to modify it?

**Comment by tomas-pluskal** [comment]
No modification necessary, as long as your default java is Java 8 (try running java -version in the command line).

**Comment by charlottenguyen** [comment]
Thank you, it worked out!
