### ISSUE TITLE
Problems loading alignment from GCS

### ISSUE THREAD

**Issue by lmtani** [igvteam/igv#567]
Hi!

IGV is having trouble to load bam files from Google Cloud Storage. It was ok earlier this week.

Here is the IGV version:

```
INFO [2018-07-19T13:52:09,454]  [Main.java:155] [AWT-EventQueue-0]  Startup  IGV Version 2.4.13 07/11/2018 02:16 PM
INFO [2018-07-19T13:52:09,455]  [Main.java:156] [AWT-EventQueue-0]  Java 1.8.0_181
```

And here is the error log

```
INFO [2018-07-19T13:53:43,514]  [IGV.java:1386] [pool-3-thread-4]  Loading 1 resources.
INFO [2018-07-19T13:53:43,515]  [TrackLoader.java:132] [pool-3-thread-4]  Loading resource, path gs://my-bams/XXXXXX-001/results/XXXXXX-001.bam
INFO [2018-07-19T13:53:44,578]  [HttpUtils.java:930] [pool-3-thread-4]  Range-byte request succeeded
ERROR [2018-07-19T13:54:00,291]  [AlignmentTileLoader.java:299] [pool-2-thread-2]  Error loading alignment data
htsjdk.samtools.util.RuntimeIOException: Invalid file header in BAM index https://www.googleapis.com/storage/v1/b/my-bams/o/XXXXXX-001%2Fresults%2FXXXXXX.bam?alt=media: 
	at htsjdk.samtools.AbstractBAMFileIndex.verifyBAMMagicNumber(AbstractBAMFileIndex.java:406) ~[igv.jar:?]
	at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:68) ~[igv.jar:?]
	at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:42) ~[igv.jar:?]
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:406) ~[igv.jar:?]
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:915) ~[igv.jar:?]
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575) ~[igv.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528) ~[igv.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533) ~[igv.jar:?]
	at org.broad.igv.sam.reader.BAMReader.query(BAMReader.java:187) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:161) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:390) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.load(AlignmentDataManager.java:335) ~[igv.jar:?]
	at org.broad.igv.sam.CoverageTrack.load(CoverageTrack.java:184) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanel.lambda$load$3(DataPanel.java:225) ~[igv.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
INFO [2018-07-19T13:54:00,292]  [MessageUtils.java:74] [pool-2-thread-2]  <html>Error encountered querying alignments: htsjdk.samtools.util.RuntimeIOException: Invalid file header in BAM index https://www.googleapis.com/storage/v1/b/my-bams/o/XXXXXX-001%2Fresults%2FXXXXXX-001.bam?alt=media: 
```

We also use IGV.js and no problems there. Could anyone help?

**Comment by jrobinso** [comment]
Just to confirm,   you use igv.js with the same bam file that is giving an
error in IGV?

Do you have a bam file I can access to reproduce the problem?

**Comment by lmtani** [comment]
Hi @jrobinso,

Today I tried again specifying the uri for the bai file and it worked. Has the pattern to find the index changed? Here are a bam/bai file (publicly available):

gs://my-production/270654-008/results/270654-008.bam
gs://my-production/270654-008/results/270654-008.bam.bai

**Comment by lmtani** [comment]
@jrobinso , the problem is on the `getIndexPath` method of `BAMReader` class. It is returning the bam uri instead of the bai

For example, adding `indexPath = indexPath + ".bai";` into line 108 of the file https://github.com/igvteam/igv/blob/master/src/main/java/org/broad/igv/sam/reader/BAMReader.java#L108 solves the loading problem.

**Comment by jrobinso** [comment]
That's strange because that hasn't changed in a while as far as I know.
 Thanks for the pointer,  I'll fix it.   The complication is both
".bam.bai" and ".bai" conventions are used, the first is the samtools
convention, the second Picard.    That the people involved couldn't agree
on something so inane has vexed us all for many years  (I've been in this
for a long time).
