### ISSUE TITLE
Expand insertions

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#591]
Expand insertions in alignment tracks by making a gap in the reference sequence.   Align insertions sequencing using cigar padding operators when present.

This has actually been implemented for over a year, but needs a little more work before releasing.

**Comment by amwenger** [comment]
Two suggestions:
* Since the insertion markers are drawn globally on all BAM tracks when at least one BAM has an insertion, I think the "Show insertion markers" preference should exist only in the "Alignments" tab and not in the "Third Gen" tab.
* I have a hard time closing the expanded insertion.  Consider making the target zone for the "close" click bigger.  Perhaps allow clicking anywhere in the red bar that shows the range of the insertion rather than just in the purple triangle.

**Comment by jrobinso** [comment]
OK, noted.  Its been a year since I worked on that,  but I do want to release it.   Please continue noting problems and suggestions.

**Comment by kpalin** [comment]
This is a great feature (thanks) but there is a bug in situation where there are several alignment tracks (at least Third Gen tracks)  The insertions are extracted from all alignments but drawn only on one (I think the latest one added but not sure). Trying to expand such insertion throws nullPointerException. This with IGV 2.5.0 binary download.

```java.lang.NullPointerException: null                                                                                                                                                                                                                                                                                                 at org.broad.igv.sam.AlignmentTrack.renderExpandedInsertion(AlignmentTrack.java:663) ~[igv.jar:?]                                                                                                                                                                                                                            at org.broad.igv.ui.panel.DataPanelPainter.paintExpandedInsertion(DataPanelPainter.java:214) ~[igv.jar:?]                                                                                                                                                                                                                    at org.broad.igv.ui.panel.DataPanelPainter.paint(DataPanelPainter.java:89) ~[igv.jar:?]                                                                                                                                                                                                                                      at org.broad.igv.ui.panel.DataPanel.paintComponent(DataPanel.java:174) ~[igv.jar:?]                        ```

**Comment by jrobinso** [comment]
Thanks for the report.   Does the error happen if you just load 1 track (the one the insertion is drawn for)?

**Comment by kpalin** [comment]
Works. I now I can't even reproduce the exception. I'm of not much help now. I'll try to get a more reproducible bug report next time.
