### ISSUE TITLE
Missing org.apache.commons.io.output.StringBuilderWriter on Ubuntu 18.04

### ISSUE THREAD

**Issue by sgrzemski** [igvteam/igv#607]
Hello IGV developers,

I'm facing a problem installing and running IGV on Ubuntu 18.04. I've tried running it both with Java 8 and Java 10, but unfortunately I am missing org.apache.commons.io.output.StringBuilderWriter. IGV installed with dependencies like a charm, no errors found, exit code 0. Maybe https://mvnrepository.com/artifact/commons-io/commons-io/2.6 is missing during the installation phase for IGV?

```
sgrzemski@ThinkPad-T470s:~/MBI3$ igv
INFO [2018-11-25 12:51:32,764]  [DirectoryManager.java:171] [AWT-EventQueue-0]  IGV Directory: /home/sgrzemski/igv
INFO [2018-11-25 12:51:32,764] [DirectoryManager.java:171]  IGV Directory: /home/sgrzemski/igv
INFO [2018-11-25 12:51:32,777]  [Main.java:154] [AWT-EventQueue-0]  Startup  IGV Version user 01/22/2018 08:52 AM
INFO [2018-11-25 12:51:32,778]  [Main.java:155] [AWT-EventQueue-0]  Java 1.8.0_191
INFO [2018-11-25 12:51:32,778]  [DirectoryManager.java:76] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2018-11-25 12:51:32,801]  [Main.java:156] [AWT-EventQueue-0]  Default User Directory: /home/sgrzemski
INFO [2018-11-25 12:51:32,801]  [Main.java:157] [AWT-EventQueue-0]  OS: Linux


ERROR [2018-11-25 12:51:32,819]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NoClassDefFoundError: org/apache/commons/io/output/StringBuilderWriter
	at org.broad.igv.util.HttpUtils.isRemoteURL(HttpUtils.java:120)
	at org.broad.igv.util.ParsingUtils.openInputStreamGZ(ParsingUtils.java:109)
	at org.broad.igv.util.ParsingUtils.openInputStream(ParsingUtils.java:96)
	at org.broad.igv.util.ParsingUtils.openBufferedReader(ParsingUtils.java:78)
	at org.broad.igv.prefs.PreferencesManager.load(PreferencesManager.java:168)
	at org.broad.igv.prefs.PreferencesManager.loadUserPreferences(PreferencesManager.java:126)
	at org.broad.igv.prefs.PreferencesManager.init(PreferencesManager.java:92)
	at org.broad.igv.prefs.PreferencesManager.getPreferences(PreferencesManager.java:53)
	at org.broad.igv.prefs.PreferencesManager.getPreferences(PreferencesManager.java:109)
	at org.broad.igv.ui.Main.updateTooltipSettings(Main.java:175)
	at org.broad.igv.ui.Main.initApplication(Main.java:162)
	at org.broad.igv.ui.Main.access$000(Main.java:72)
	at org.broad.igv.ui.Main$1.run(Main.java:102)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.StringBuilderWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
INFO [2018-11-25 12:51:33,829]  [ShutdownThread.java:47] [Thread-2]  Shutting down
sgrzemski@ThinkPad-T470s:~/MBI3$ sudo update-alternatives --config java
Są 2 dostępne alternatywy dla java (dostarczające /usr/bin/java).

  Wybór       Ścieżka                                    Priorytet  Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1101      tryb auto
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1101      tryb ręczny
* 2            /usr/lib/jvm/java-8-oracle/jre/bin/java       1081      tryb ręczny

Wciśnij <enter>, aby zachować bieżący wybór[*], lub wpisz numer wyboru: 1
update-alternatives: użycie /usr/lib/jvm/java-11-openjdk-amd64/bin/java jako dostarczającego /usr/bin/java (java) w trybie ręcznym
sgrzemski@ThinkPad-T470s:~/MBI3$ igv
INFO [2018-11-25 12:51:54,868]  [DirectoryManager.java:171] [AWT-EventQueue-0]  IGV Directory: /home/sgrzemski/igv
INFO [2018-11-25 12:51:54,868] [DirectoryManager.java:171]  IGV Directory: /home/sgrzemski/igv
INFO [2018-11-25 12:51:54,873]  [Main.java:154] [AWT-EventQueue-0]  Startup  IGV Version user 01/22/2018 08:52 AM
INFO [2018-11-25 12:51:54,874]  [Main.java:155] [AWT-EventQueue-0]  Java 10.0.2
INFO [2018-11-25 12:51:54,874]  [DirectoryManager.java:76] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2018-11-25 12:51:54,934]  [Main.java:156] [AWT-EventQueue-0]  Default User Directory: /home/sgrzemski
INFO [2018-11-25 12:51:54,935]  [Main.java:157] [AWT-EventQueue-0]  OS: Linux


ERROR [2018-11-25 12:51:54,957]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NoClassDefFoundError: org/apache/commons/io/output/StringBuilderWriter
	at org.broad.igv.util.HttpUtils.isRemoteURL(HttpUtils.java:120)
	at org.broad.igv.util.ParsingUtils.openInputStreamGZ(ParsingUtils.java:109)
	at org.broad.igv.util.ParsingUtils.openInputStream(ParsingUtils.java:96)
	at org.broad.igv.util.ParsingUtils.openBufferedReader(ParsingUtils.java:78)
	at org.broad.igv.prefs.PreferencesManager.load(PreferencesManager.java:168)
	at org.broad.igv.prefs.PreferencesManager.loadUserPreferences(PreferencesManager.java:126)
	at org.broad.igv.prefs.PreferencesManager.init(PreferencesManager.java:92)
	at org.broad.igv.prefs.PreferencesManager.getPreferences(PreferencesManager.java:53)
	at org.broad.igv.prefs.PreferencesManager.getPreferences(PreferencesManager.java:109)
	at org.broad.igv.ui.Main.updateTooltipSettings(Main.java:175)
	at org.broad.igv.ui.Main.initApplication(Main.java:162)
	at org.broad.igv.ui.Main.access$000(Main.java:72)
	at org.broad.igv.ui.Main$1.run(Main.java:102)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.StringBuilderWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 27 more
INFO [2018-11-25 12:51:55,965]  [ShutdownThread.java:47] [Thread-1]  Shutting down
sgrzemski@ThinkPad-T470s:~/MBI3$ 
```

Many thanks in advance, BR,
Szymon

**Comment by sgrzemski** [comment]
IGV installed from Ubuntu 18.04 repository. Downloaded from http://data.broadinstitute.org/igv/projects/downloads/2.4/IGV_2.4.16.zip works like a charm. The repo version is 2.4.6, so I believe more recent version has it fixed.

**Comment by jrobinso** [comment]
Hi, we have no control over the Ubuntu installs.
