### ISSUE TITLE
IGV 2.5.2 windows version and proxy password storage

### ISSUE THREAD

**Issue by littlebzh** [igvteam/igv#653]
Hello

After a recent upgrade to igv 2.5.2 windows version and a change of proxy's password in the dedicated tab in Preferences , IGV crashed during start-up.

It seems to be related to the proxy's stored password in prefs.properties.

In 2.5.2 version : it is written in clear text

`PROXY.PW=test_password`

In this case, after cash, igv.log shows :

`ERROR [2019-05-28T12:51:55,005] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.IllegalArgumentException: Illegal character in Base64 encoded data.
	at biz.source_code.base64Coder.Base64Coder.decode(Base64Coder.java:248) ~[igv.jar:?]
	at biz.source_code.base64Coder.Base64Coder.decode(Base64Coder.java:214) ~[igv.jar:?]
	at biz.source_code.base64Coder.Base64Coder.decode(Base64Coder.java:202) ~[igv.jar:?]
	at biz.source_code.base64Coder.Base64Coder.decodeString(Base64Coder.java:170) ~[igv.jar:?]
	at org.broad.igv.util.Utilities.base64Decode(Utilities.java:69) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.updateProxySettings(HttpUtils.java:458) ~[igv.jar:?]
	at org.broad.igv.ui.Main.open(Main.java:279) ~[igv.jar:?]
	at org.broad.igv.ui.Main$1.run(Main.java:110) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
INFO [2019-05-28T12:51:56,019] [ShutdownThread.java:46]  Shutting down`

After tests, in previous version (an old 2.3.x) and in the snapshot version : the password is base64 encoded in igv.prefs file.
`PROXY.PW=ZmRjaHUuMzZ=`

If I edit prefs.properties file and  I put the encoded string in PROXY.PW and I try to launch IGV 2.5.2, it works (no crash and proxy is correctly set).

Is there a problem with password configuration in 2.5.2 or I need to check something on my side ?

Regards

**Comment by jrobinso** [comment]
Thanks, by coincidence I just discovered this myself.   I pushed a fix and
will release it soon.  The error occurs when writing the password from the
preferences UI.   A workaround until the fix is released is to base64 the
password and manually edit the prefs.properties file.

This will be released soon as 2.5.3

**Comment by jrobinso** [comment]
Fixed in 2.5.3
