### ISSUE TITLE
IGV 2.6.3 java.lang.NullPointerException: null on Mac

### ISSUE THREAD

**Issue by MeHelmy** [igvteam/igv#701]
I got `java.lang.NullPointerException: null` when I try to run IGV 2.6.3 

*I tried both*

- IGV Mac App
-  IGV and igvtools to run on the command line (all platforms)

Based on issue #651 I also installed  OpenJDK 11, but nothing changed.

```
Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
WARN [2019-09-27T10:50:23,596]  [Globals.java:138] [AWT-EventQueue-0]  Development mode is enabled
INFO [2019-09-27T10:50:23,619]  [DirectoryManager.java:179] [AWT-EventQueue-0]  IGV Directory: /Users/mmahmoud/igv
INFO [2019-09-27T10:50:23,635]  [Main.java:156] [AWT-EventQueue-0]  Startup  IGV Version 2.6.3 08/27/2019 12:03 AM
INFO [2019-09-27T10:50:23,645]  [Main.java:157] [AWT-EventQueue-0]  Java 11.0.4 (build 11.0.4+11) 2019-07-16
INFO [2019-09-27T10:50:23,646]  [Main.java:160] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2019-09-27T10:50:23,647]  [Main.java:162] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK
INFO [2019-09-27T10:50:23,647]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory...
INFO [2019-09-27T10:50:23,712]  [Main.java:165] [AWT-EventQueue-0]  Default User Directory: /Users/mmahmoud
INFO [2019-09-27T10:50:23,713]  [Main.java:166] [AWT-EventQueue-0]  OS: Mac OS X 10.14.5 x86_64
ERROR [2019-09-27T10:50:23,743]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at java.awt.Window.init(Window.java:509) ~[?:?]
	at java.awt.Window.<init>(Window.java:549) ~[?:?]
	at java.awt.Frame.<init>(Frame.java:423) ~[?:?]
	at java.awt.Frame.<init>(Frame.java:388) ~[?:?]
	at javax.swing.JFrame.<init>(JFrame.java:180) ~[?:?]
	at org.broad.igv.ui.Main$1.run(Main.java:107) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
INFO [2019-09-27T10:50:24,855]  [ShutdownThread.java:46] [Thread-1]  Shutting down
```

**Comment by jrobinso** [comment]
This is the first report of this we have received, and I can't reproduce it.  We all use Macs.  

Could you try the snapshot version and see if the problem persists?  We don't provide a signed mac app for the snapshot, you'll need to unzip and run from the command line.  Thanks.

**Comment by jrobinso** [comment]
Sorry forgot the link  https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by MeHelmy** [comment]
Sorry for the late answer,
I downloaded it .

to start `./igv.sh`


**Error**

```
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)
WARN [2019-10-01T17:33:39,427]  [Globals.java:139] [AWT-EventQueue-0]  Development mode is enabled
INFO [2019-10-01T17:33:39,443]  [DirectoryManager.java:179] [AWT-EventQueue-0]  IGV Directory: /Users/mmahmoud/igv
INFO [2019-10-01T17:33:39,457]  [Main.java:150] [AWT-EventQueue-0]  Startup  IGV Version snapshot 09/26/2019 08:12 PM
INFO [2019-10-01T17:33:39,466]  [Main.java:151] [AWT-EventQueue-0]  Java 11.0.2 (build 11.0.2+9) 2019-01-15
INFO [2019-10-01T17:33:39,467]  [Main.java:154] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2019-10-01T17:33:39,467]  [Main.java:156] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK
INFO [2019-10-01T17:33:39,468]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory...
INFO [2019-10-01T17:33:39,532]  [Main.java:159] [AWT-EventQueue-0]  Default User Directory: /Users/mmahmoud
INFO [2019-10-01T17:33:39,532]  [Main.java:160] [AWT-EventQueue-0]  OS: Mac OS X 10.14.5 x86_64
ERROR [2019-10-01T17:33:39,552]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at java.awt.Window.init(Unknown Source) ~[?:?]
	at java.awt.Window.<init>(Unknown Source) ~[?:?]
	at java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at javax.swing.JFrame.<init>(Unknown Source) ~[?:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:102) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
INFO [2019-10-01T17:33:40,687]  [ShutdownThread.java:46] [Thread-1]  Shutting down
```

**Comment by jrobinso** [comment]
I'm not really sure, note the error is in the java awt, not our application
code.   I haven't seen this before.  Could you try the mac bundle (the
app).

**Comment by MeHelmy** [comment]
Thanks for your continuous help. 

I identified the issue. it has no relation to the code at all, and the error is not informative.

The Issue is when you connect mac to an external screen and close the led IGV will not work (I see how it is sound). so the **solution is to open mac led**, only then the IGV will work.

More could be found here: 
https://github.com/oracle/visualvm/issues/84#issuecomment-474830113

Thanks,
Medhat

**Comment by jrobinso** [comment]
OK, thanks for the link.  There's nothing we can do about that obviously,
hopefully they fix it soon.
