### ISSUE TITLE
IGV 2.7.2 does not start  - can someone give me hint?

### ISSUE THREAD

**Issue by AKWB** [igvteam/igv#718]
Hi,

I searched the repository, but I did not really find a solution for my issue.

I start IGV 2.7.2 with the following command:
java --module-path=lib -Xmx4g @igv.args --module=org.igv/org.broad.igv.ui.Main

I am not a java-person...I tried to set the proxy in /etc/java-11-openjdk/net.properties, but this did not change.  Maybe someone can help? Or give me a hint?

I get this error message:
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
WARN [2019-10-24T12:51:54,108]  [Globals.java:139] [main]  Development mode is enabled
INFO [2019-10-24T12:51:54,124]  [DirectoryManager.java:179] [main]  IGV Directory: /home/sem_awie/igv
ERROR [2019-10-24T12:52:14,240]  [OAuthUtils.java:95] [main]  java.net.SocketTimeoutException: connect timed out
INFO [2019-10-24T12:52:14,568]  [Main.java:156] [AWT-EventQueue-0]  Startup  IGV Version 2.7.2 10/21/2019 11:01 PM
INFO [2019-10-24T12:52:14,578]  [Main.java:157] [AWT-EventQueue-0]  Java 11.0.4 (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3) 2019-07-16
INFO [2019-10-24T12:52:14,578]  [Main.java:160] [AWT-EventQueue-0]  Java Vendor: Ubuntu https://ubuntu.com/
INFO [2019-10-24T12:52:14,579]  [Main.java:162] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM    
INFO [2019-10-24T12:52:14,579]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2019-10-24T12:52:14,621]  [Main.java:165] [AWT-EventQueue-0]  Default User Directory: /home/sem_awie
INFO [2019-10-24T12:52:14,622]  [Main.java:166] [AWT-EventQueue-0]  OS: Linux 4.15.0-65-generic amd64
ERROR [2019-10-24T12:52:15,122]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.ui.IGVMenuBar.createGoogleMenu(IGVMenuBar.java:1050) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.createMenus(IGVMenuBar.java:186) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.<init>(IGVMenuBar.java:152) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.lambda$createInstance$1(IGVMenuBar.java:139) ~[igv.jar:?]
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.createInstance(IGVMenuBar.java:139) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.<init>(IGV.java:243) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.createInstance(IGV.java:144) ~[igv.jar:?]
	at org.broad.igv.ui.Main.open(Main.java:294) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:112) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
ERROR [2019-10-24T12:52:34,666]  [Main.java:221] [Thread-2]  Error checking version
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:816) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:698) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:694) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:202) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:194) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$checkVersion$1(Main.java:199) [igv.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by jrobinso** [comment]
Apologies for this, it looks like a proxy issue as you suggest.  We occasionally see this on Linux systems but haven't been able to reproduce it locally.  It appears that java is not picking up the proxy information.  IGV has a UI for setting proxy but of course if you can't start it you can't use it.

Try this as a workaround.   Look in the directory "igv" in you home directory, if it doesn't exist create it.   In that directory look for a file called "prefs.properties",  again if it doesn't exist create it.   Add the following lines to the file, substituting your proxy and port, save and restart IGV.

PROXY.USE=true
PROXY.HOST={your host}
PROXY.PORT={port number}

**Comment by AKWB** [comment]
thanks for your suggestion!! I have this pref.properties file and as I used an old version of IGV (2.4.14). The proxy information is already in there. If I start the old IGV (of course with Java 8) I also get the second part of the error message (Error checking version), but IGC starts anyway and I can work with it. 

What about the first part of the error message? 
--> ERROR [2019-10-24T12:52:15,122] [DefaultExceptionHandler.java:49] [AWT-EventQueue-0] Unhandled exception
java.lang.NullPointerException: null
at org.broad.igv.ui.IGVMenuBar.createGoogleMenu(IGVMenuBar.java:1050) ~[igv.jar:?]

or do I need to delete the igv-folder from my "old" IGV-version?

**Comment by jrobinso** [comment]
Are you trying to use IGV offline?

**Comment by jrobinso** [comment]
If you are getting those errors with the proxy information set, perhaps that proxy information is not correct.  You could try removing it.

Also, could you try the "snapshot" build?  I just pushed a change to protect against the specific error that stopping the startup, but you might encounter another one downstream if there is no network connection.   You can download the snapshot from  https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by AKWB** [comment]
No, my PC is online...
But, if the old IGV-version can use the proxy info, it should be correct, or?
ok, so I will the snapshot version ;-). And come back to you. Thanks!!

**Comment by AKWB** [comment]
the snapshot works...I get this (Error checking version), but it does not harm IGV from working...
I can also download genomes from a server. Thus, I guess everything should work?

Thanks a lot!!

**Comment by jrobinso** [comment]
OK, that's for confirming it.  If you're able to download genomes your proxy is working.   The version check is not used anymore,  I will just remove that.
