### ISSUE TITLE
Error parsing line at byte position when uploading bed file

### ISSUE THREAD

**Issue by olechnwin** [igvteam/igv#719]
Hi,
I tried to open a bed file and it's giving me this error:

`Error loading D:\macs2_rslt.bed: Error parsing line at byte position: LineIteratorImpl(SynchronousLineReader), for input source: D:\macs2_rslt.bed
`

This is the error in igv.log:
```
ERROR [2019-08-06T12:36:14,155] [DataPanel.java:253]  Error: 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException
	at org.broad.igv.track.DataSourceTrack.getSummaryScores(DataSourceTrack.java:106) ~[igv.jar:?]
	at org.broad.igv.track.DataTrack.load(DataTrack.java:144) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanel.lambda$load$3(DataPanel.java:225) ~[igv.jar:?]
	... 4 more
```

I'm attaching the bed.file that's giving me this error. 
Can you please help me figure out what was wrong? Thank you in advance.
[macs2_rslt.zip](https://github.com/igvteam/igv/files/3773120/macs2_rslt.zip)

**Comment by olechnwin** [comment]
Never mind. I figured out what was wrong. In one of the bed line, the address was written in scientific form. That's why IGV is throwing out an error.
