### ISSUE TITLE
Don't require connection to AWS when starting IGV 2.7.2

### ISSUE THREAD

**Issue by conchoecia** [igvteam/igv#721]
I did a few tests on IGV 2.7.2  ( on OS X) using Little Snitch, and found that when starting up IGV pings both AWS (s3-1.amazonaws.com) and the Broad institute (data.broadinstitute.org). I am only visualizing local assemblies and bams.

When I deny the broad institute connection the application loads fine. When I deny the AWS connection the application fails to continue loading and I cannot use it. I also tried loading IGV 2.7.2 without an internet connection and it did finish loading.

Can you make it such that IGV can continue loading even if there is no network connection or the AWS connection is denied?

**Comment by jrobinso** [comment]
Hi,
IGV does load with no internet connection,  I think you confirmed that but am unsure based on your last statement.  RE if the connection is denied,  if it fails IGV should continue to load, if it hangs forever IGV might hang as well.  Could you give me more details on what is happening?  Anything in the log?

I am not familiar with "Little Snitch".

**Comment by conchoecia** [comment]
Hi, Thanks for your quick response. [Little Snitch is an app for OS X that allows you to monitor network traffic on a per-application basis](https://www.obdev.at/products/littlesnitch/index.html). When a program tries to connect to something over the network, the program asks the user for permission, then allows the connection or blocks it based on the user's response. 

I think what is going on is that the program is "hanging" and waiting for the AWS connection, and never loads if it doesn't connect to AWS.

To make it a little more clear, I did another experiment:
1. Turned off internet
2. Opened IGV 2.7.2 on my mac
  - The IGV process was running, but the main window never appeared.
3. Turned on the internet
  - Little Snitch immediately reported that IGV wanted to connect to AWS and prompted me to allow or deny the connection. I waited for about a minute, and the main IGV window never appeared.
4. I clicked "allow" on the Little Snitch prompt to allow IGV to make a connection to the AWS server.
  - The main IGV window immediately appeared.
5. A Little Snitch prompt appeared showing that IGV was attempting to connect to the Broad Institute server.
6. I denied the prompt to connect to the Broad Institute server.
  - Nothing happened.
7. I tried to use IGV with local files. It was fine.

Little Snitch reports the following relevant info:

```
IGV_2.7.2
wants to connect to s3.amazonaws.com on TCP port 443 (https)

	IP Address	52.216.138.77
	Reverse DNS Name	s3-1.amazonaws.com
	Established by	Java Class: @/private/var/folders/mq/l2lx8t993_3fgq4f8v528gq40000gn/T/AppTranslocation/B6C01B78-39C4-4DBC-BE5A-7512F7ABD1AE/d/IGV_2.7.2.app/Contents/MacOS/../Java/igv.arg
```

I'd be happy to take a look at some IGV-specific logs if it generates them while loading the app. I'm just not sure where they are located on the disk.

**Comment by jrobinso** [comment]
The igv log is in an "igv" folder in your home directory.  Its called igv.log.   

I can't reproduce your problem, if I startup with no internet it gives me the warning below, as it should.    You can avoid the call to amazon by editing the genome server URL in the advanced preferences (View > Preferences > Advanced).  You can set it to a local file using the full file path, an empty file should work.  

<img width="606" alt="Screen Shot 2019-10-29 at 7 35 23 PM" src="https://user-images.githubusercontent.com/933148/67824513-c5573f80-fa83-11e9-9fea-0c25c21e2dd7.png">

**Comment by conchoecia** [comment]
I'm still having this problem - where IGV just keeps trying to connect to the internet no matter how I change the preferences. Here is my error log before changing the advanced preferences:

```
INFO [2019-10-29T12:59:09,132] [Main.java:156]  Startup  IGV Version 2.7.2 10/21/2019 11:01 PM
INFO [2019-10-29T12:59:09,141] [Main.java:157]  Java 11.0.5 (build 11.0.5+10) 2019-10-15
INFO [2019-10-29T12:59:09,142] [Main.java:160]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2019-10-29T12:59:09,142] [Main.java:162]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK
INFO [2019-10-29T12:59:09,143] [DirectoryManager.java:84]  Fetching user directory...
INFO [2019-10-29T12:59:09,258] [Main.java:165]  Default User Directory: /Users/darrin
INFO [2019-10-29T12:59:09,258] [Main.java:166]  OS: Mac OS X 10.14.1 x86_64
ERROR [2019-10-29T12:59:11,338] [Main.java:221]  Error checking version
java.net.ConnectException: Host is down (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:816) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:698) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:694) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:202) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:194) ~[igv.jar:?]
        at org.broad.igv.ui.Main.lambda$checkVersion$1(Main.java:199) [igv.jar:?]
```

Now I made an empty file in my home directory and pointed IGV to that file, but IGV still is trying to connect to the internet every time that I start it up, and will not load unless it can ping the mothership (AWS and the broad institute).

<img width="898" alt="Screen Shot 2020-01-22 at 9 49 00 PM" src="https://user-images.githubusercontent.com/3123273/72924031-38114780-3d61-11ea-9e09-b764240d5490.png">

```
INFO [2020-01-22T21:52:24,321] [Main.java:156]  Startup  IGV Version 2.7.2 10/21/2019 11:01 PM
INFO [2020-01-22T21:52:24,335] [Main.java:157]  Java 11.0.5 (build 11.0.5+10) 2019-10-15
INFO [2020-01-22T21:52:24,336] [Main.java:160]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2020-01-22T21:52:24,336] [Main.java:162]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK
INFO [2020-01-22T21:52:24,337] [DirectoryManager.java:84]  Fetching user directory...
INFO [2020-01-22T21:52:24,482] [Main.java:165]  Default User Directory: /Users/darrin
INFO [2020-01-22T21:52:24,483] [Main.java:166]  OS: Mac OS X 10.14.1 x86_64
ERROR [2020-01-22T21:52:24,817] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.ui.IGVMenuBar.createGoogleMenu(IGVMenuBar.java:1050) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.createMenus(IGVMenuBar.java:186) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.<init>(IGVMenuBar.java:152) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.lambda$createInstance$1(IGVMenuBar.java:139) ~[igv.jar:?]
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166) ~[igv.jar:?]
	at org.broad.igv.ui.IGVMenuBar.createInstance(IGVMenuBar.java:139) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.<init>(IGV.java:243) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.createInstance(IGV.java:144) ~[igv.jar:?]
	at org.broad.igv.ui.Main.open(Main.java:294) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:112) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
ERROR [2020-01-22T21:52:32,024] [Main.java:221]  Error checking version
java.net.ConnectException: Host is down (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:816) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:698) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:694) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:202) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.getContentsAsString(HttpUtils.java:194) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$checkVersion$1(Main.java:199) [igv.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by jrobinso** [comment]
You are still testing 2.7.2,  so its not surprising the result is the same.  I could not reproduce this but added some checks in 2.8.0 that might resolve it.  Can't say for sure since I can't produce it here.

**Comment by conchoecia** [comment]
The new version works great, even when IGV can't connect to the internet. Thank you for the fix! 

<img width="601" alt="Screen Shot 2020-01-22 at 11 22 24 PM" src="https://user-images.githubusercontent.com/3123273/72931000-297d5d00-3d6e-11ea-8be0-9a168c50177d.png">
