### ISSUE TITLE
IGV Mac app crashing on load

### ISSUE THREAD

**Issue by IsmailM** [igvteam/igv#752]
The IGV app crashes as soon as it is launched. I am on Mac Os Catalina

I see the following error when starting the app from the command line 

```bash
$ /Applications/IGV_2.8.0.app/Contents/MacOS/IGV

echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
WARN [2020-01-27T15:34:19,090]  [Globals.java:139] [main]  Development mode is enabled
INFO [2020-01-27T15:34:19,115]  [DirectoryManager.java:179] [main]  IGV Directory: /Users/ismailm/igv
INFO [2020-01-27T15:34:20,182]  [Main.java:159] [AWT-EventQueue-0]  Startup  IGV Version 2.8.0 01/06/2020 08:43 PM
INFO [2020-01-27T15:34:20,200]  [Main.java:160] [AWT-EventQueue-0]  Java 11.0.5 (build 11.0.5+10) 2019-10-15
INFO [2020-01-27T15:34:20,202]  [Main.java:163] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2020-01-27T15:34:20,203]  [Main.java:165] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK
INFO [2020-01-27T15:34:20,203]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory...
INFO [2020-01-27T15:34:21,430]  [Main.java:168] [AWT-EventQueue-0]  Default User Directory: /Users/ismailm
INFO [2020-01-27T15:34:21,430]  [Main.java:169] [AWT-EventQueue-0]  OS: Mac OS X 10.15.1 x86_64
ERROR [2020-01-27T15:34:21,436]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at java.awt.Window.init(Unknown Source) ~[?:?]
	at java.awt.Window.<init>(Unknown Source) ~[?:?]
	at java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at java.awt.Frame.<init>(Unknown Source) ~[?:?]
	at javax.swing.JFrame.<init>(Unknown Source) ~[?:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:111) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
INFO [2020-01-27T15:34:22,458]  [ShutdownThread.java:46] [Thread-1]  Shutting down
```

Would appreciate any help on this. 

Many thanks, 
Ismail Moghul

**Comment by IsmailM** [comment]
Seems like this is related to https://stackoverflow.com/questions/53216725/mac-os-and-java-lang-nullpointerexception-at-java-awt-window-initwindow-java49

I simply had to disconnect my laptop from its docking station and then launch IGV...

**Comment by helgathorv** [comment]
Thanks for letting us know.

**Comment by jrobinso** [comment]
Sorry about that, this seems to be a common problem with docking stations,
"display link",  and Java.   See this open issue:
https://github.com/oracle/visualvm/issues/84.
