### ISSUE TITLE
Error from IGV calling: Unhandled exception java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by Roksaneh** [igvteam/igv#824]
Hello,

I am trying to execute IGV on Linux Ubuntu 18.04 through Winscp from windows.
First I downloaded the IGV for Linux from https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_Linux_2.8.6.zip.
Then I installed Java from the command below:
$ sudo apt install default-jdk
Thereafter I tried to unzip IGV_Linux_2.8.6.zip using unzip command.
According to readme.txt I tried to make igv.sh executable via chmod a+x igv.sh command.
Then I tried to run the IGV via this command from terminal through Winscp:
$ java --module-path=lib -Xmx4g @igv.args --module=org.igv/org.broad.igv.ui.Main
There I got an error below:
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
WARN [2020-07-04T12:23:23,218]  [Globals.java:139] [main]  Development mode is enabled
INFO [2020-07-04T12:23:23,229]  [DirectoryManager.java:179] [main]  IGV Directory: /home/bluser/igv
ERROR [2020-07-04T12:23:26,035]  [DefaultExceptionHandler.java:49] [main]  Unhandled exception
java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:?]
        at sun.awt.X11GraphicsEnvironment$1.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.awt.X11GraphicsEnvironment.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at java.awt.GraphicsEnvironment$LocalGE.createGE(Unknown Source) ~[?:?]
        at java.awt.GraphicsEnvironment$LocalGE.<clinit>(Unknown Source) ~[?:?]
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(Unknown Source) ~[?:?]
        at sun.awt.X11.XToolkit.<clinit>(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at java.awt.Toolkit$2.run(Unknown Source) ~[?:?]
        at java.awt.Toolkit$2.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.awt.Toolkit.getDefaultToolkit(Unknown Source) ~[?:?]
        at java.awt.Toolkit.getEventQueue(Unknown Source) ~[?:?]
        at java.awt.EventQueue.invokeLater(Unknown Source) ~[?:?]
        at javax.swing.SwingUtilities.invokeLater(Unknown Source) ~[?:?]
        at org.broad.igv.ui.Main.main(Main.java:119) ~[igv.jar:?]

Anybody can help me with this?
$ Java -version
Output:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

**Comment by jrobinso** [comment]
You don't need to install Java for that bundle, its included and won't use the Java you installed in any event.

However the problem is not with Java but with X11.    Try a websearch on this error message, it should give you suggestions to try
```
java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
```

**Comment by Roksaneh** [comment]
> You don't need to install Java for that bundle, its included and won't use the Java you installed in any event.
> 
> However the problem is not with Java but with X11. Try a websearch on this error message, it should give you suggestions to try
> 
> ```
> java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
> ```

Thank you dear Jim, for our reply. I tried almost solution but could not solve the problem so far.
I was wondering maybe you can guide me for my other issue with IGV web application.
I also tried to work with IGV online web-based application, there I could not load my desired reference genome! (mm9)
Please guide me on how to load the mm9 genome on the IGV web application?
I read the help page on the IGV website but did not help.
Thank you.

**Comment by jrobinso** [comment]
@Roksaneh what exactly about the instructions for the website do you not understand?
