### ISSUE TITLE
Multiple IGVs accessing same log file pops up continuous errors. Can a log file be specific in batch scripts?

### ISSUE THREAD

**Issue by ranasats** [igvteam/igv#831]
Hi,

I'm trying to batch process bams a handful of paired bams. I have IGV scripted to launch for each pair and go through a list of pos and take a screenshot. However, I'm getting this error due to from what I guess is the multiple IGV processes writing to the same log file. Is there a way to specify a log file in the batch script? It doesn't seem to cause any issues for the end product. All my images are there and look good. 

I'm now using IGV 2.8.0 I tried 2.8.7 but there were issues with the batch script freezing at random points in the process. So far 2.8.0 has been going strong.

```
INFO [2020-07-28T14:44:29,986]  [BatchRunner.java:72] [pool-3-thread-2]  Executing Command: exit
2020-07-28 14:44:29,987 pool-3-thread-2 ERROR Recovering from StringBuilderEncoder.encode('INFO [2020-07-28T14:44:29,986] [BatchRunner.java:72]  Executing Command: exit
') error: org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream /home/ranas/igv/igv.log org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream /home/ranas/igv/igv.log
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:265)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.FileManager.writeToDestination(FileManager.java:261)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.rolling.RollingFileManager.writeToDestination(RollingFileManager.java:219)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:295)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.OutputStreamManager.drain(OutputStreamManager.java:352)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.ByteBufferDestinationHelper.writeToUnsynchronized(ByteBufferDestinationHelper.java:45)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.OutputStreamManager.writeBytes(OutputStreamManager.java:362)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.TextEncoderHelper.writeEncodedText(TextEncoderHelper.java:96)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.TextEncoderHelper.encodeText(TextEncoderHelper.java:65)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:68)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:32)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:220)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:58)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:309)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:439)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:434)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at log4j@1.2-api-2.11.0/org.apache.log4j.Category.maybeLog(Category.java:452)
        at log4j@1.2-api-2.11.0/org.apache.log4j.Category.info(Category.java:262)
        at org.igv/org.broad.igv.batch.BatchRunner.run(BatchRunner.java:72)
        at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Stale file handle
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at org.apache.logging.log4j.core@2.11.0/org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:263)
        ... 37 more
```

The above error happens at every command (sort, go to, screenshot, etc)

**Comment by jrobinso** [comment]
IGV isn't designed for this, multiple instances on the same machine won't work for sure with oAuth and there could be other issues.     However there is a command line switch to specify an "igv" directory, which by default is <user home>/igv.  As the log is in the igv directory this might work.   The switch is
```
--igvDirectory  <full path to a writable directory>
```
