### ISSUE TITLE
user-defined-genomes file is being overwritten

### ISSUE THREAD

**Issue by ranasats** [igvteam/igv#841]
Hey,

I have a user-defined-genomes file in my user directory` /home/<user>/igv/genomes/user-defined-genomes.txt`

It has two lines in it, but randomly the second line keeps getting deleted from the file, causing IGV to fail to launch when looking for the custom genome referenced in this line.

I'm not sure why this is happening, logs show nothing other than 

`INFO [2020-08-26T20:03:09,312] [MessageUtils.java:76]  Could not locate genome with ID: ASM985889v3_offline`

Because the server I'm running this on not connected to the internet it can't continue loading the default genome/list.

I'm using IGV 2.8.0 on CentOS 6.10

**Comment by jrobinso** [comment]
What is the second line, could you paste it here?   Regardless I suggest you store a genomes list file somewhere else and then change the location for the default list in the preferences  (View > Preferences > Advanced > Genome Server URL).    Enter the absolute file path to the genome list file.

The genome list file format is 3 columns, tab delimited,  with a header line (first line) that is ignored.     The columns are name (for the menu),  url  or file path to the .genome, .gbk, or fasta file,  and the unique ID for the genome.  Here are the first few lines of the default file


```
<Server-Side Genome List>
A. gambia (Pest AgamP3)	https://s3.amazonaws.com/igv.broadinstitute.org/genomes/AgamP3.genome	AgamP3
A. nidulans (4.1)	https://s3.amazonaws.com/igv.broadinstitute.org/genomes/anidulans_4.1.genome	anidulans_4.1
Autographa californica MNPV	https://s3.amazonaws.com/igv.broadinstitute.org/genomes/NC_001623.genome	NC_001623
Bacillus Subtilis str. 168	https://s3.amazonaws.com/igv.broadinstitute.org/genomes/NC_000964.genome	NC_000964
```

**Comment by ranasats** [comment]
Hi Jim,

Here is the whole file:

`(base) [ranas@server ranas]$ cat /home/ranas/igv/genomes/user-defined-genomes.txt
Local Genome for IGV /home/ranas/igv/custom_genomes/IGVSS.genome       IGVSS_Genome
SARS-CoV-2_offline      /home/ranas/igv/custom_genomes/SARS_COVID19.genome   ASM985889v3_offline
`

That file works normally. I can load a script that has either "IGV_hg19_offline" or "ASM985889v3_offline" when that file is fully populated. Both genomes work great and load. However like I said before this file sometimes gets overwritten to only contain the first line, not the second.

**Comment by jrobinso** [comment]
Thanks.   Have you tried the solution I suggested?

**Comment by ranasats** [comment]
I'm running this as a batch script, is there a setting I can change in the preferences file, or add something to the arguments while launching before running the batch?

**Comment by jrobinso** [comment]
Yes, it is a user preference.  Just set it through the UI and it will be in the preferences file.

**Comment by ranasats** [comment]
Hey Jim, Thanks for the help so far. Please bare with me, I updated as you suggested. Prefs file contains:
```
IGV.genome.sequence.dir=/home/ranas/igv/genomes/user-defined-genomes.txt
```

But a new error shows up:


```
ERROR [2020-09-01T11:16:48,362]  [GenomeListManager.java:411] [pool-3-thread-1]  Error fetching genome list:
java.net.MalformedURLException: no protocol: /home/ranas/igv/genomes/user-defined-genomes.txt
        at java.net.URL.<init>(URL.java:627) ~[?:?]
        at java.net.URL.<init>(URL.java:523) ~[?:?]
        at java.net.URL.<init>(URL.java:470) ~[?:?]
        at org.broad.igv.util.URLUtils.getFauxUrl(URLUtils.java:100) ~[igv.jar:?]
        at org.broad.igv.util.URLUtils.getHost(URLUtils.java:29) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.mapURL(HttpUtils.java:145) ~[igv.jar:?]
        at org.broad.igv.util.HttpUtils.createURL(HttpUtils.java:122) ~[igv.jar:?]
        at org.broad.igv.ui.commandbar.GenomeListManager.getServerGenomeMap(GenomeListManager.java:370) [igv.jar:?]
        at org.broad.igv.ui.commandbar.GenomeListManager.getGenomeListItem(GenomeListManager.java:183) [igv.jar:?]
        at org.broad.igv.feature.genome.GenomeManager.loadGenomeById(GenomeManager.java:175) [igv.jar:?]
        at org.broad.igv.ui.IGV$StartupRunnable.run(IGV.java:2084) [igv.jar:?]
        at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jrobinso** [comment]
Please do not use user-defined-genomes.txt and do not store the file in the igv/genomes directory.   You are now mixing two independent things.    Re-read the instructions above.
