### ISSUE TITLE
IGV error on ubuntu

### ISSUE THREAD

**Issue by shayanns** [igvteam/igv#845]
im trying to install igv in ubuntu. when i execute "java --module-path=lib -Xmx4g @igv.args --module=org.igv/org.broad.igv.ui.Main" i get the following error:

WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
WARN [2020-09-06T17:03:51,799]  [Globals.java:139] [main]  Development mode is enabled
INFO [2020-09-06T17:03:51,837]  [DirectoryManager.java:179] [main]  IGV Directory: /home/s/igv
INFO [2020-09-06T17:03:52,841]  [Main.java:160] [AWT-EventQueue-0]  Startup  IGV Version 2.8.9 08/03/2020 06:24 PM
INFO [2020-09-06T17:03:52,865]  [Main.java:161] [AWT-EventQueue-0]  Java 11.0.8 (build 11.0.8+10-post-Ubuntu-0ubuntu120.04) 2020-07-14
INFO [2020-09-06T17:03:52,866]  [Main.java:164] [AWT-EventQueue-0]  Java Vendor: Ubuntu https://ubuntu.com/
INFO [2020-09-06T17:03:52,868]  [Main.java:166] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM
INFO [2020-09-06T17:03:52,875]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory...
INFO [2020-09-06T17:03:52,963]  [Main.java:169] [AWT-EventQueue-0]  Default User Directory: /home/s
INFO [2020-09-06T17:03:52,965]  [Main.java:170] [AWT-EventQueue-0]  OS: Linux 4.4.0-19041-Microsoft amd64
ERROR [2020-09-06T17:03:52,974]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208) ~[?:?]
        at java.awt.Window.<init>(Window.java:548) ~[?:?]
        at java.awt.Frame.<init>(Frame.java:423) ~[?:?]
        at java.awt.Frame.<init>(Frame.java:388) ~[?:?]
        at javax.swing.JFrame.<init>(JFrame.java:180) ~[?:?]
        at org.broad.igv.ui.Main.lambda$main$0(Main.java:112) ~[igv.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
INFO [2020-09-06T17:03:54,031]  [ShutdownThread.java:46] [Thread-1]  Shutting down

i have installed java 11.0.8

thank you in advance

**Comment by jrobinso** [comment]
You need to set your X11 display

**Comment by sudoJpablo** [comment]
como hago eso?
