### ISSUE TITLE
Bug: Could not find BlockCompressionMethod

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#884]
Hi,
I'm encountering a bug that is new from the past few IGV versions. This is occurring when using CRAM files from gcloud. Not sure if it occurs from local CRAMs. The CRAM files are definitely correctly aligned to the reference genome being used.

When this error occurs, reads stop to load. This error resolves when zooming out 3-4 levels and then zooming back in-- the reads reappear and start reloading.

The error is triggered when scrolling side to side far enough to trigger loading of additional reads. It does not occur when inputting a specific location in the genome.

<img width="1030" alt="Screen Shot 2021-01-04 at 1 19 01 PM" src="https://user-images.githubusercontent.com/47928628/103566212-9ad6f280-4e8f-11eb-95b0-b40e712d54f9.png">
<img width="780" alt="Screen Shot 2021-01-04 at 1 19 05 PM" src="https://user-images.githubusercontent.com/47928628/103566217-9ca0b600-4e8f-11eb-8220-172b758cc65e.png">

**Comment by jrobinso** [comment]
There's not enough to go on there to guess the problem.     Can you reproduce this with a CRAM I can load?  Attaching the log output with the stack trace might help.

**Comment by gevro** [comment]
Simple to replicate the bug. Just open this file: gs://fc-96159657-d5ae-4dda-90fd-00769e94dd22/84f7081e-fff3-4615-8a5c-76967ea0900a/WholeGenomeGermlineSingleSample/23201801-45b7-4f5c-9628-b9ba8541eb0c/call-BamToCram/BamToCram/cb9a1cbe-d3ef-4cd7-8fa4-32581ec485dc/call-ConvertToCram/NA12878_PLUMBING.cram

Then scroll to the left or right a few times.

**Comment by gevro** [comment]
Note, this is definitely not an issue with the CRAM file. File works fine locally. It is an issue with CRAM files viewed from Gcloud.

**Comment by jrobinso** [comment]
Not so simple to replicate.   I loaded the file, jumped to "myc", then panned around for a while.   If you attach your log file or stack trace, or specific steps to reproduce,  I will look further.   If I can replicate it I will fix it for the upcoming release, which should be out next week.

**Comment by gevro** [comment]
It keeps happening for me. It just happened on "myc" on two separate computers. Perhaps only on my IGV version. I'm using this: https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_MacApp_2.8.13_WithJava.zip
Can you try that?
I'm not sure how to save the log or stack trace, but let me know the steps and I can do that too. Or I can post a screen video if you can't replicate it so you can see the steps, in case I've missed something.

**Comment by jrobinso** [comment]
Well, I can reproduce it with that version.  But only that version, as far as I can tell.    I was testing 2.8.12, and the "snapshot" build which will soon be 2.9.0.    In your original post you said "recent verions" plural,  but at this point it doesn't matter I am not fixing bugs on the 2.8.x branch with 2.9.0 so close.   You can try running the snapshot build, if you can talk your Mac into allowing it.  Snapshot builds are not signed or notarized with apple.   Alternatively 2.8.12 works, or worked in my tests, of course if its a random error that might have been by chance.

**Comment by gevro** [comment]
I was able to run the latest snapshot build, but it's throwing a different error upon GCloud authorization. It's asking me to paste the auth code back into IGV, and then I'm seeing this on terminal and IGV stops responding. This is a separate error, but due to this, I cannot evaluate whether the above issue still occurs on the latest snapshot.

```
INFO [2021-01-09T01:39:00,231]  [TrackLoader.java:122] [pool-3-thread-2]  Loading resource, path https://www.googleapis.com/storage/v1/b/fc-96159657-d5ae-4dda-90fd-00769e94dd22/o/84f7081e-fff3-4615-8a5c-76967ea0900a%2FWholeGenomeGermlineSingleSample%2F23201801-45b7-4f5c-9628-b9ba8541eb0c%2Fcall-BamToCram%2FBamToCram%2Fcb9a1cbe-d3ef-4cd7-8fa4-32581ec485dc%2Fcall-ConvertToCram?alt=media
ERROR [2021-01-09T01:39:08,052]  [OAuthProvider.java:242] [pool-3-thread-2]  java.io.IOException: Server returned HTTP response code: 400 for URL: https://accounts.google.com/o/oauth2/token
java.io.IOException: Server returned HTTP response code: 400 for URL: https://accounts.google.com/o/oauth2/token
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.igv/org.broad.igv.util.HttpUtils.doPost(HttpUtils.java:275)
	at org.igv/org.broad.igv.google.OAuthProvider.fetchTokens(OAuthProvider.java:203)
	at org.igv/org.broad.igv.google.OAuthProvider.setAuthorizationCode(OAuthProvider.java:173)
	at org.igv/org.broad.igv.google.OAuthProvider.openAuthorizationPage(OAuthProvider.java:159)
	at org.igv/org.broad.igv.google.OAuthProvider.doSecureLogin(OAuthProvider.java:424)
	at org.igv/org.broad.igv.google.GoogleUtils.checkLogin(GoogleUtils.java:51)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:862)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:636)
	at org.igv/org.broad.igv.util.HttpUtils.openConnection(HttpUtils.java:632)
	at org.igv/org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:311)
	at org.igv/org.broad.igv.util.HttpUtils.openConnectionStream(HttpUtils.java:305)
	at org.igv/org.broad.igv.util.ParsingUtils.openInputStreamGZ(ParsingUtils.java:110)
	at org.igv/org.broad.igv.util.ParsingUtils.openAsciiReader(ParsingUtils.java:90)
	at org.igv/org.broad.igv.data.expression.ExpressionFileParser.parsableMAGE_TAB(ExpressionFileParser.java:134)
	at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:181)
	at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1411)
	at org.igv/org.broad.igv.ui.IGV.loadResources(IGV.java:1343)
	at org.igv/org.broad.igv.ui.IGV$4.run(IGV.java:475)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by jrobinso** [comment]
If its asking you to paste in an auth code it probably means you are
running another IGV, which grabs the port for the authorization callback.
 Be sure any other IGVs are shutdown before starting up the snapshot.  I'm
aware that the "paste" option is not working, its one of the things on my
2.9.0 list but I'm not sure its fixable.   If not you will see a "please
close other IGVs" message.

**Comment by gevro** [comment]
Thanks. Got it to work. The original issue I posted about is not occurring. I will close the issue, since I assume 2.9.0 will be ok.

**Comment by gevro** [comment]
When is 2.9.0 going to be released, to fix this bug? Thanks.

**Comment by jrobinso** [comment]
Soon, if you need the fix in the meantime the snapshot/development build
has it.
