### ISSUE TITLE
IGV won't start anymore on Mac

### ISSUE THREAD

**Issue by awilcz** [igvteam/igv#903]
Hi, I was running IGV just fine until yesterday, when it started running away with CPU usage, and then after force quitting, it won't launch again. I've tried deleting all the relevant files, reinstalling etc and to no avail. I've tried launching it with Java 14 as well as Java 11... 

Here's my error message: 
`WARN [2021-02-03T12:24:08,520]  [Globals.java:135] [main]  Development mode is enabled
INFO [2021-02-03T12:24:08,536]  [DirectoryManager.java:180] [main]  IGV Directory: /Users/***/igv
INFO [2021-02-03T12:24:09,657]  [Main.java:205] [AWT-EventQueue-0]  Startup  IGV Version 2.9.0 02/01/2021 06:00 PM
INFO [2021-02-03T12:24:09,675]  [Main.java:206] [AWT-EventQueue-0]  Java 11.0.9 (build 11.0.9+11) 2020-10-20
INFO [2021-02-03T12:24:09,676]  [Main.java:209] [AWT-EventQueue-0]  Java Vendor: Oracle Corporation https://openjdk.java.net/
INFO [2021-02-03T12:24:09,677]  [Main.java:211] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM    
INFO [2021-02-03T12:24:09,849]  [Main.java:214] [AWT-EventQueue-0]  Default User Directory: /Users/***
INFO [2021-02-03T12:24:09,850]  [Main.java:215] [AWT-EventQueue-0]  OS: Mac OS X 10.15.5 x86_64
ERROR [2021-02-03T12:24:10,156]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.util.AmazonUtils.GetCognitoAWSCredentials(AmazonUtils.java:101) ~[igv.jar:?]
	at org.broad.igv.util.AmazonUtils.createPresignedURL(AmazonUtils.java:408) ~[igv.jar:?]
	at org.broad.igv.util.AmazonUtils.translateAmazonCloudURL(AmazonUtils.java:438) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.mapURL(HttpUtils.java:146) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.createURL(HttpUtils.java:135) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.resourceAvailable(HttpUtils.java:335) ~[igv.jar:?]
	at org.broad.igv.util.FileUtils.resourceExists(FileUtils.java:56) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.getUserDefinedGenomeMap(GenomeListManager.java:453) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.rebuildGenomeItemMap(GenomeListManager.java:84) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.getGenomeItemMap(GenomeListManager.java:72) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeComboBox.getModelForGenomeListComboBox(GenomeComboBox.java:66) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeComboBox.refreshGenomeListComboBox(GenomeComboBox.java:40) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.lambda$refreshGenomeListComboBox$1(IGVCommandBar.java:212) ~[igv.jar:?]
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.refreshGenomeListComboBox(IGVCommandBar.java:211) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.<init>(IGVCommandBar.java:103) ~[igv.jar:?]
	at org.broad.igv.ui.IGVContentPane.<init>(IGVContentPane.java:73) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.<init>(IGV.java:245) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.createInstance(IGV.java:147) ~[igv.jar:?]
	at org.broad.igv.ui.Main.open(Main.java:341) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:118) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
INFO [2021-02-03T12:24:11,170]  [ShutdownThread.java:47] [Thread-1]  Shutting down

`

**Comment by doncarlos999** [comment]
I get a very similar error:

`Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11)
OpenJDK 64-Bit Server VM (build 11.0.9+11, mixed mode)
WARN [2021-02-03T13:08:21,113]  [Globals.java:135] [main]  Development mode is enabled
INFO [2021-02-03T13:08:21,132]  [DirectoryManager.java:180] [main]  IGV Directory: /Users/user/igv
INFO [2021-02-03T13:08:22,215]  [Main.java:205] [AWT-EventQueue-0]  Startup  IGV Version 2.9.0 02/01/2021 06:00 PM
INFO [2021-02-03T13:08:22,226]  [Main.java:206] [AWT-EventQueue-0]  Java 11.0.9 (build 11.0.9+11) 2020-10-20
INFO [2021-02-03T13:08:22,226]  [Main.java:209] [AWT-EventQueue-0]  Java Vendor: Oracle Corporation https://openjdk.java.net/
INFO [2021-02-03T13:08:22,227]  [Main.java:211] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM
INFO [2021-02-03T13:08:22,375]  [Main.java:214] [AWT-EventQueue-0]  Default User Directory: /Users/carlward
INFO [2021-02-03T13:08:22,376]  [Main.java:215] [AWT-EventQueue-0]  OS: Mac OS X 11.1 x86_64
ERROR [2021-02-03T13:08:22,646]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.util.AmazonUtils.GetCognitoAWSCredentials(AmazonUtils.java:101) ~[igv.jar:?]
	at org.broad.igv.util.AmazonUtils.createPresignedURL(AmazonUtils.java:408) ~[igv.jar:?]
	at org.broad.igv.util.AmazonUtils.translateAmazonCloudURL(AmazonUtils.java:438) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.mapURL(HttpUtils.java:146) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.createURL(HttpUtils.java:135) ~[igv.jar:?]
	at org.broad.igv.util.HttpUtils.resourceAvailable(HttpUtils.java:335) ~[igv.jar:?]
	at org.broad.igv.util.FileUtils.resourceExists(FileUtils.java:56) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.getUserDefinedGenomeMap(GenomeListManager.java:453) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.rebuildGenomeItemMap(GenomeListManager.java:84) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeListManager.getGenomeItemMap(GenomeListManager.java:72) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeComboBox.getModelForGenomeListComboBox(GenomeComboBox.java:66) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.GenomeComboBox.refreshGenomeListComboBox(GenomeComboBox.java:40) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.lambda$refreshGenomeListComboBox$1(IGVCommandBar.java:212) ~[igv.jar:?]
	at org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.refreshGenomeListComboBox(IGVCommandBar.java:211) ~[igv.jar:?]
	at org.broad.igv.ui.commandbar.IGVCommandBar.<init>(IGVCommandBar.java:103) ~[igv.jar:?]
	at org.broad.igv.ui.IGVContentPane.<init>(IGVContentPane.java:73) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.<init>(IGV.java:245) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.createInstance(IGV.java:147) ~[igv.jar:?]
	at org.broad.igv.ui.Main.open(Main.java:341) ~[igv.jar:?]
	at org.broad.igv.ui.Main.lambda$main$0(Main.java:118) ~[igv.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
INFO [2021-02-03T13:08:23,742]  [ShutdownThread.java:47] [Thread-1]  Shutting down`

**Comment by helgathorv** [comment]
@awilcz When you say you deleted all the relevant files, did you try deleting (or renaming) the whole ~/igv directory? Are you using the Mac App or running from the command line? 

Until we can figure this out, does IGV version 2.8.13 still work for you? You can download the 2.8.13 Mac App (with or without Java) from here: 
https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_MacApp_2.8.13_WithJava.zip
https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_MacApp_2.8.13.zip

**Comment by jrobinso** [comment]
@awilcz @doncarlos999 Do you have Amazon cognito set up?   I cannot reproduce this issues, but I do not use Amazon cognito.

**Comment by jrobinso** [comment]
Also @doncarlos999 you do not seem to be running a released version of IGV, is that the case?  Where are you getting the IGV you are running?

**Comment by jrobinso** [comment]
@brainstorm I think this must be related to some updated Amazon jars in the new release.  Its failing at line 101 of AmazonUtils with a null pointer exception.  Looking at that line I suspect response.get("id_token") is returning null

```
JsonObject payload = JWTParser.getPayload(response.get("id_token").getAsString());
```

**Comment by brainstorm** [comment]
Weird, I'll take a look right now ASAP. @awilcz @doncarlos999 would you mind sharing [your IGV json provisioning files](https://github.com/umccr/infrastructure/blob/master/cdk/apps/igv/config/backend/dev/oauth-config.json.gz)?

**Comment by brainstorm** [comment]
By the looks of it, after peeking at the code, both @doncarlos999 and @awilcz might be trying to **access a public, unauthenticated S3 resource**? If so, could you please share it just to rule out if there's something else more particular with that dataset?

**Comment by jrobinso** [comment]
@brainstorm After digging through the cobwebs I got a basic setup going again using these instructions. https://umccr.org/blog/igv-amazon-backend-setup/.   Basic tests work fine, I don't see any errors.

Also, FWIW, nearly all of IGV's genomes and hosted data re on public unauthenticated S3 resources.

**Comment by jrobinso** [comment]
@awilcz @doncarlos999. We aren't able to reproduce this problem, to help we will need further information.   In addition to the answers to the questions already asked, could you paste the contents of, or zip up and attach the file "user-defined-genomes.txt" in the folder <user home directory>/igv/genomes?   If there is senstive information in that file you can just examine it and look for the presence of any S3 urls in the second column, by that I mean any urls that start with. "s3://".

**Comment by awilcz** [comment]
> @awilcz When you say you deleted all the relevant files, did you try deleting (or renaming) the whole ~/igv directory? Are you using the Mac App or running from the command line?
> 
> Until we can figure this out, does IGV version 2.8.13 still work for you? You can download the 2.8.13 Mac App (with or without Java) from here:
> https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_MacApp_2.8.13_WithJava.zip
> https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_MacApp_2.8.13.zip

@helgathorv Sorry for the delayed reply! This applies to all versions I tried...

**Comment by awilcz** [comment]
> @awilcz @doncarlos999 Do you have Amazon cognito set up? I cannot reproduce this issue, but I do not use Amazon cognito.

Yes, that's correct

**Comment by awilcz** [comment]
> By the looks of it, after peeking at the code, both @doncarlos999 and @awilcz might be trying to **access a public, unauthenticated S3 resource**? If so, could you please share it just to rule out if there's something else more particular with that dataset?

We are unable to start the software at all! Repeated downloads have yielded nothing. The icon just bounces on the dock, then disappears.

**Comment by brainstorm** [comment]
Thanks fot the reply! Could you run the following on a terminal:

ls -alh ~/.igv
cat ~/.igv/auth-config.xml

And paste both outputs in this issue? Cheers!

**Comment by jrobinso** [comment]
@awilcz Unable to start what software?   The current IGV release is 2.9.1.

**Comment by jrobinso** [comment]
@awilcz Also, we will need to see your igv.log file,  its located in an "igv" folder in your home directory.    

Based on your previous log output,  from version 2.9.0,  I asked for the following, which we never received.   The log indicates a user defined genome is involved.   I will repeat here. 

 "... In addition to answers to questions already asked, could you paste the contents of, or zip up and attach the file "user-defined-genomes.txt" in the folder /igv/genomes? If there is senstive information in that file you can just examine it and look for the presence of any S3 urls in the second column, by that I mean any urls that start with. "s3://".

**Comment by doncarlos999** [comment]
@jrobinso I removed the "user-defined-genomes.txt" file and now it works!

**Comment by jrobinso** [comment]
@doncarlos999 Is it possible to share the contents of that file?   If there is sensitive information you can email it securely to igvteam (at) broadinstitute.org.

**Comment by doncarlos999** [comment]
[user-defined-genomes.txt](https://github.com/igvteam/igv/files/5989882/user-defined-genomes.txt)

**Comment by jrobinso** [comment]
OK the problem is here, the reference to  a fasta file via an s3:// url.  This is not supported, fasta files cannot be loaded from s3:// urls.   The file types supported are listed in an earlier message in this thread, and also on the UMCCR page..   I'm not sure how this could have occurred but will see what I can do to prevent it in the future.  @awilcz the cause of your issue is likely the same.  You can edit "user-defined-genomes.txt" and remove all s3:// references, or delete it altogether.   

```
20200610_fastacorrected_eTF_and_discovery.fasta	s3://bitbio.igv/20200610_fastacorrected_eTF_and_discovery.fasta	s3://bitbio.igv/20200610_fastacorrected_eTF_and_discovery.fasta
```
