### ISSUE TITLE
Error parsing IUPAC codes when allele is not (A|T|C|G|N)+

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#927]
Hi

I'm reporting an issue that might be easy to fix, or might have to be fixed in htsjdk.
In short, when alleles have IUPAC codes that not just (A|T|C|G|N), IGV reports errors like below

```
Error loading [path_to_vcf]:
The provided VCF file is malformed at approximately line number 13795: 
unparsable vcf record with allele <"problematic_allele">, for input source: 
[path_to_vcf]
```

The site in my example contains a `Y`, which is `C or T` according to IUPAC.

<img width="1070" alt="Screen Shot 2021-03-10 at 3 06 11 PM" src="https://user-images.githubusercontent.com/16310888/110690726-45ca9c00-81b2-11eb-8ea3-9806dcf88b8b.png">

Thanks

Steve

**Comment by jrobinso** [comment]
Hi Steve,  I think this error is thrown by the htsjdk although you see it in IGV.   If you can provide the stacktrace from your igv.log file we can see exactly where its thrown.   I don't know the VCF spec well enough to say if ambiguity codes should be allowed or not,  someone there in Eric Bank's group would probably know.

**Comment by SHuang-Broad** [comment]
(PS I'm in that group :wink:)

This is actually the second time I'm running into this problem (the first time was a while back). But back then we thought this might be such a rare case that we didn't think too much of it. Now I'm seeing two more such cases in one VCF.

To be fair, I don't think this will be much of a problem for small variants, since all the cases I've seen so far are from "corners" where SV people would care more about.

I guess I'll ask @lbergelson for a comment, and see how we can approach this.

**Comment by jrobinso** [comment]
@SHuang-Broad Oh, duh!  I wasn't sure what group your were in, and I'm not sure who does the coding for VCF but @lbergelson would know.   In any event I'm not sure the htsjdk is throwing that, but I suspect it is, the igv.log file should tell us.

**Comment by lbergelson** [comment]
@SHuang-Broad Is the IUPAC code in the reference or in the allele itself?  If you can find the stack trace that would be useful for pinpointing where it's coming from.

**Comment by lbergelson** [comment]
In general vcf doesn't like iupac codes and wants them to be converted to concrete bases or symbolic alleles.

**Comment by SHuang-Broad** [comment]
So, @lbergelson, do you think it'd better a warning be issued by htjdk if it sees IUPAC codes in the VCF, instead of an error?

It's a bit inconvenient that one has to search for specifically this type of errors (the VCF in my case had 3 alleles/records that had this problem), and each time I need to grep out the "offending" bases.

**Comment by SHuang-Broad** [comment]
@jrobinso Jim, this is the relevant section in igv.log


```
INFO [2021-03-15T11:41:40,442] [Main.java:205]  Startup  IGV Version 2.9.2 02/16/2021 01:27 PM
INFO [2021-03-15T11:41:40,451] [Main.java:206]  Java 11.0.10 (build 11.0.10+9) 2021-01-19
INFO [2021-03-15T11:41:40,451] [Main.java:209]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2021-03-15T11:41:40,452] [Main.java:211]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2021-03-15T11:41:40,589] [Main.java:214]  Default User Directory: /Users/shuang
INFO [2021-03-15T11:41:40,590] [Main.java:215]  OS: Mac OS X 10.15.7 x86_64
INFO [2021-03-15T11:41:41,947] [GenomeManager.java:183]  Loading genome: /Users/shuang/igv/genomes/hg38.genome
INFO [2021-03-15T11:41:46,214] [CommandListener.java:121]  Listening on port 60151
INFO [2021-03-15T11:42:01,057] [IGV.java:1316]  Loading 1 resources.
INFO [2021-03-15T11:42:01,063] [TrackLoader.java:122]  Loading resource, path /Users/shuang/Desktop/variants/sv/HG00514.corrected.cutesv.vcf
ERROR [2021-03-15T11:42:01,406] [TrackLoader.java:249]  The provided VCF file is malformed at approximately line number 13795: unparsable vcf record with allele GAATGCACACATCACACAACAGTTACTCAGATAGCTTCTTTCTAGTTTTTAATCCTGGGACATTCACTTTTTTGCCATTGGGGCCAATGAACTCTCAAATGTCCATTCACAGAAGGGACAAAAACAGTGTTTCCAAACTCCTGAATCCAAAGAAGAGTTTAACTCCGTAAGGTGAATGGACACATCATGAAGTAGTTTCTCAGAAAGCTTCTTTGTAGTTGTCATCTGAAGATGTTTCCTATTTCACCATAGGCCTGAAGGCTCTCTGAAATATCCCTTTGTAGATACTACAAAAACAGTGTCTCCAAAATGCTGAATGAAAAGAAAGGTTTAACTCTGTGAATAAATTCACACATCACAAAGCGGTTTTCCAGATAGCCTCCTTCTAGTTTTTATACTGGGATATTTTCTTTTTCACCATTGGCCTCAAAGAGCTCCAAATATCCATTTGCAGAATGGACAAAAACATTGTTTCCAAACTGCAGAATTGAAAGAAAGGTTTAAGTCTGTGAGATGAATGCAAACATCACAATGTAGTTTCTCAGAAAGCTTCTTTCTAGTTTTTATGTGAAGATGTTTCCTTTTTCAACATAGGCCTCAATGCTCTCTGAAATATCCCTTTTCATATTCTACAAAAACAGTTTTTCCTACCTGCTGAATGAAAAGATGGGTTTGCCTCTGAGAGGTGAATGCACACATCACATAGCACTTTCTCAGATAGCTTTCTCCTAGTTTTTATCCTGGGATATTGGCTTTTTCACCATTGGTCTCCATGAGCTCCATAATTTCCATTCACAGAATGGACAAAAACAGTGTTTCCACACTGCTGAACACAAAAAAAGGATTAACTCTGTGAGATGACTGTATCCCTCACAYAGCAGTTTCTAAGATAGATTCAGTCCAGTTTTTTCCTGGGATATTTGCTTTTTCGCCATTGGCCTCAATTAACTCCTAAATGTCCATATGCAGAATGGACGAAAACAGTGTTTTCAATCTGCTGATTACAAAGAAAGGTTTAACTATGTGAGATGAATGCACACATCACAAAGCGGTTTCTCAGATAGCTTCCTTTTAGTTTTTATCCTGGGATATTCACTTTTTCACCATTGGCATCAATGAGCTCTGAAATGTCCATTCACAGAATGGACAAAAACACTTTCCAAGCTACTGAATACAAAGAATGGATTAACTCTGTGAGATA, for input source: /Users/shuang/Desktop/variants/sv/HG00514.corrected.cutesv.vcf
htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 13795: unparsable vcf record with allele GAATGCACACATCACACAACAGTTACTCAGATAGCTTCTTTCTAGTTTTTAATCCTGGGACATTCACTTTTTTGCCATTGGGGCCAATGAACTCTCAAATGTCCATTCACAGAAGGGACAAAAACAGTGTTTCCAAACTCCTGAATCCAAAGAAGAGTTTAACTCCGTAAGGTGAATGGACACATCATGAAGTAGTTTCTCAGAAAGCTTCTTTGTAGTTGTCATCTGAAGATGTTTCCTATTTCACCATAGGCCTGAAGGCTCTCTGAAATATCCCTTTGTAGATACTACAAAAACAGTGTCTCCAAAATGCTGAATGAAAAGAAAGGTTTAACTCTGTGAATAAATTCACACATCACAAAGCGGTTTTCCAGATAGCCTCCTTCTAGTTTTTATACTGGGATATTTTCTTTTTCACCATTGGCCTCAAAGAGCTCCAAATATCCATTTGCAGAATGGACAAAAACATTGTTTCCAAACTGCAGAATTGAAAGAAAGGTTTAAGTCTGTGAGATGAATGCAAACATCACAATGTAGTTTCTCAGAAAGCTTCTTTCTAGTTTTTATGTGAAGATGTTTCCTTTTTCAACATAGGCCTCAATGCTCTCTGAAATATCCCTTTTCATATTCTACAAAAACAGTTTTTCCTACCTGCTGAATGAAAAGATGGGTTTGCCTCTGAGAGGTGAATGCACACATCACATAGCACTTTCTCAGATAGCTTTCTCCTAGTTTTTATCCTGGGATATTGGCTTTTTCACCATTGGTCTCCATGAGCTCCATAATTTCCATTCACAGAATGGACAAAAACAGTGTTTCCACACTGCTGAACACAAAAAAAGGATTAACTCTGTGAGATGACTGTATCCCTCACAYAGCAGTTTCTAAGATAGATTCAGTCCAGTTTTTTCCTGGGATATTTGCTTTTTCGCCATTGGCCTCAATTAACTCCTAAATGTCCATATGCAGAATGGACGAAAACAGTGTTTTCAATCTGCTGATTACAAAGAAAGGTTTAACTATGTGAGATGAATGCACACATCACAAAGCGGTTTCTCAGATAGCTTCCTTTTAGTTTTTATCCTGGGATATTCACTTTTTCACCATTGGCATCAATGAGCTCTGAAATGTCCATTCACAGAATGGACAAAAACACTTTCCAAGCTACTGAATACAAAGAATGGATTAACTCTGTGAGATA, for input source: /Users/shuang/Desktop/variants/sv/HG00514.corrected.cutesv.vcf
	at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:887) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:678) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:640) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:443) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:384) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:328) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:48) ~[htsjdk-2.23.0.jar:?]
	at org.broad.igv.feature.tribble.VCFWrapperCodec.decode(VCFWrapperCodec.java:69) ~[igv.jar:?]
	at org.broad.igv.feature.tribble.VCFWrapperCodec.decode(VCFWrapperCodec.java:43) ~[igv.jar:?]
	at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:375) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:354) ~[htsjdk-2.23.0.jar:?]
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315) ~[htsjdk-2.23.0.jar:?]
	at org.broad.igv.track.TribbleFeatureSource$NonIndexedFeatureSource.<init>(TribbleFeatureSource.java:377) ~[igv.jar:?]
	at org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:123) ~[igv.jar:?]
	at org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:70) ~[igv.jar:?]
	at org.broad.igv.track.TrackLoader.loadVCF(TrackLoader.java:298) ~[igv.jar:?]
	at org.broad.igv.track.TrackLoader.loadTribbleFile(TrackLoader.java:393) ~[igv.jar:?]
	at org.broad.igv.track.TrackLoader.load(TrackLoader.java:208) [igv.jar:?]
	at org.broad.igv.ui.IGV.load(IGV.java:1399) [igv.jar:?]
	at org.broad.igv.ui.IGV.loadResources(IGV.java:1331) [igv.jar:?]
	at org.broad.igv.ui.IGV$4.run(IGV.java:474) [igv.jar:?]
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
ERROR [2021-03-15T11:42:01,412] [IGV.java:1334]  Error loading track
org.broad.igv.exceptions.DataLoadException: The provided VCF file is malformed at approximately line number 13795: unparsable vcf record with allele GAATGCACACATCACACAACAGTTACTCAGATAGCTTCTTTCTAGTTTTTAATCCTGGGACATTCACTTTTTTGCCATTGGGGCCAATGAACTCTCAAATGTCCATTCACAGAAGGGACAAAAACAGTGTTTCCAAACTCCTGAATCCAAAGAAGAGTTTAACTCCGTAAGGTGAATGGACACATCATGAAGTAGTTTCTCAGAAAGCTTCTTTGTAGTTGTCATCTGAAGATGTTTCCTATTTCACCATAGGCCTGAAGGCTCTCTGAAATATCCCTTTGTAGATACTACAAAAACAGTGTCTCCAAAATGCTGAATGAAAAGAAAGGTTTAACTCTGTGAATAAATTCACACATCACAAAGCGGTTTTCCAGATAGCCTCCTTCTAGTTTTTATACTGGGATATTTTCTTTTTCACCATTGGCCTCAAAGAGCTCCAAATATCCATTTGCAGAATGGACAAAAACATTGTTTCCAAACTGCAGAATTGAAAGAAAGGTTTAAGTCTGTGAGATGAATGCAAACATCACAATGTAGTTTCTCAGAAAGCTTCTTTCTAGTTTTTATGTGAAGATGTTTCCTTTTTCAACATAGGCCTCAATGCTCTCTGAAATATCCCTTTTCATATTCTACAAAAACAGTTTTTCCTACCTGCTGAATGAAAAGATGGGTTTGCCTCTGAGAGGTGAATGCACACATCACATAGCACTTTCTCAGATAGCTTTCTCCTAGTTTTTATCCTGGGATATTGGCTTTTTCACCATTGGTCTCCATGAGCTCCATAATTTCCATTCACAGAATGGACAAAAACAGTGTTTCCACACTGCTGAACACAAAAAAAGGATTAACTCTGTGAGATGACTGTATCCCTCACAYAGCAGTTTCTAAGATAGATTCAGTCCAGTTTTTTCCTGGGATATTTGCTTTTTCGCCATTGGCCTCAATTAACTCCTAAATGTCCATATGCAGAATGGACGAAAACAGTGTTTTCAATCTGCTGATTACAAAGAAAGGTTTAACTATGTGAGATGAATGCACACATCACAAAGCGGTTTCTCAGATAGCTTCCTTTTAGTTTTTATCCTGGGATATTCACTTTTTCACCATTGGCATCAATGAGCTCTGAAATGTCCATTCACAGAATGGACAAAAACACTTTCCAAGCTACTGAATACAAAGAATGGATTAACTCTGTGAGATA, for input source: /Users/shuang/Desktop/variants/sv/HG00514.corrected.cutesv.vcf
	at org.broad.igv.track.TrackLoader.load(TrackLoader.java:251) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.load(IGV.java:1399) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.loadResources(IGV.java:1331) [igv.jar:?]
	at org.broad.igv.ui.IGV$4.run(IGV.java:474) [igv.jar:?]
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
INFO [2021-03-15T11:42:01,414] [MessageUtils.java:76]  Error loading /Users/shuang/Desktop/variants/sv/HG00514.corrected.cutesv.vcf: The provided VCF file is malformed at approximately line number 13795: unparsable vcf record with allele GAATGCACACATCACACAACAGTTACTCAGATAGCTTCTTTCTAGTTTTTAATCCTGGGACATTCACTTTTTTGCCATTGGGGCCAATGAACTCTCAAATGTCCATTCACAGAAGGGACAAAAACAGTGTTTCCAAACTCCTGAATCCAAAGAAGAGTTTAACTCCGTAAGGTGAATGGACACATCATGAAGTAGTTTCTCAGAAAGCTTCTTTGTAGTTGTCATCTGAAGATGTTTCCTATTTCACCATAGGCCTGAAGGCTCTCTGAAATATCCCTTTGTAGATACTACAAAAACAGTGTCTCCAAAATGCTGAATGAAAAGAAAGGTTTAACTCTGTGAATAAATTCACACATCACAAAGCGGTTTTCCAGATAGCCTCCTTCTAGTTTTTATACTGGGATATTTTCTTTTTCACCATTGGCCTCAAAGAGCTCCAAATATCCATTTGCAGAATGGACAAAAACATTGTTTCCAAACTGCAGAATTGAAAGAAAGGTTTAAGTCTGTGAGATGAATGCAAACATCACAATGTAGTTTCTCAGAAAGCTTCTTTCTAGTTTTTATGTGAAGATGTTTCCTTTTTCAACATAGGCCTCAATGCTCTCTGAAATATCCCTTTTCATATTCTACAAAAACAGTTTTTCCTACCTGCTGAATGAAAAGATGGGTTTGCCTCTGAGAGGTGAATGCACACATCACATAGCACTTTCTCAGATAGCTTTCTCCTAGTTTTTATCCTGGGATATTGGCTTTTTCACCATTGGTCTCCATGAGCTCCATAATTTCCATTCACAGAATGGACAAAAACAGTGTTTCCACACTGCTGAACACAAAAAAAGGATTAACTCTGTGAGATGACTGTATCCCTCACAYAGCAGTTTCTAAGATAGATTCAGTCCAGTTTTTTCCTGGGATATTTGCTTTTTCGCCATTGGCCTCAATTAACTCCTAAATGTCCATATGCAGAATGGACGAAAACAGTGTTTTCAATCTGCTGATTACAAAGAAAGGTTTAACTATGTGAGATGAATGCACACATCACAAAGCGGTTTCTCAGATAGCTTCCTTTTAGTTTTTATCCTGGGATATTCACTTTTTCACCATTGGCATCAATGAGCTCTGAAATGTCCATTCACAGAATGGACAAAAACACTTTCCAAGCTACTGAATACAAAGAATGGATTAACTCTGTGAGATA, for input source: /Users/shuang/Desktop/variants/sv/HG00514.corrected.cutesv.vcf

```

**Comment by lbergelson** [comment]
@SHuang-Broad Yeah, it's not ideal from a user perspective.  Maybe we could automatically convert the IUPAC bases to something we can handle and give a warning.   Either convert to N or to the alphabetically first option from the pool of ambiguous bases.

**Comment by jrobinso** [comment]
Hi @lbergelson ,  from the VCF spec it looks like IUPAC codes should be allowed, but perhaps only if they are defined in the header?  Or maybe I'm misunderstanding, this is from page 6 of the 4.3 spec

```
IUPAC ambiguity codes
Symbolic alleles can be used also to represent genuinely ambiguous data in VCF, for example:
##ALT=<ID=R,Description="IUPAC code R = A/G">
##ALT=<ID=M,Description="IUPAC code M = A/C">
```

**Comment by jrobinso** [comment]
@lbergelson @SHuang-Broad Actually I think that is a symbolic allele (previous comment).   So are the IUPAC codes defined in the VCF header with ##ALT directives?

**Comment by jrobinso** [comment]
@lbergelson @SHuang-Broad   Hi all, I'm not sure what there is to do here in IGV,  we can either transfer this issue to htsjdk (if that's possible) or just close it.

See my question above re symbolic alleles, my reading of the spec seems to indicate that IUPAC alleles should be defined with an ##ALT line in the header,  worth checking the VCF in question to see if that's done.   The fix might be as simple as adding the required header line.

**Comment by SHuang-Broad** [comment]
Sorry Jim, went off to chase different problems. The "offending" records are actually large deletions (over 1kbp), so the non ATCG bases are in the reference alleles, not the ALT alleles.

And I think the line that actually raising the exception is [here](https://github.com/samtools/htsjdk/blob/7719274fe370a51a24e6067de21bbe7e18c160a9/src/main/java/htsjdk/variant/variantcontext/Allele.java#L331) in htsjdk.

**Comment by jrobinso** [comment]
@SHuang-Broad @lbergelson Should this issue be transferred to the htsjdk, or open a new one there?  There's nothing to be done about it in IGV.

**Comment by SHuang-Broad** [comment]
Just submitted a few seconds ago (should have done it a long time ago...)
